CREATE TABLE `calendar`.`calendar_event` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `STUDY_CALENDAR_ID` INT(11) NULL,
  `SUBJECT_UID` VARCHAR(45) NULL,
  `TITLE` VARCHAR(255) NULL,
  `START` DATETIME NULL,
  `END` DATETIME NULL,
  `CATEGORY` VARCHAR(45) NULL,
  `ALL_DAY` TINYINT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_calendar_event_study_calendar_idx` (`STUDY_CALENDAR_ID` ASC),
  CONSTRAINT `fk_calendar_event_study_calendar`
    FOREIGN KEY (`STUDY_CALENDAR_ID`)
    REFERENCES `study`.`study_calendar` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `calendar`.`calendar_event` 
CHANGE COLUMN `START` `START_TIME` DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN `END` `END_TIME` DATETIME NULL DEFAULT NULL ;

