CREATE TABLE `spark`.`micro_service` (
  `ID` INT(11) NOT NULL,
  `NAME` VARCHAR(20) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `SERVICE_URL` VARCHAR(2083) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

ALTER TABLE `spark`.`micro_service` 
CHANGE COLUMN `ID` `ID` INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE `spark`.`micro_service` 
ADD COLUMN `STUDY_ID` INT(11) NULL AFTER `SERVICE_URL`;
