ALTER TABLE `study`.`phone` 
ADD COLUMN `VALID_FROM` DATE NULL AFTER `SILENT`,
ADD COLUMN `VALID_TO` DATE NULL AFTER `VALID_FROM`;

/**auditing purpose **/
ALTER TABLE `audit`.`aud_phone` 
ADD COLUMN `VALID_FROM` DATE NULL AFTER `SILENT`,
ADD COLUMN `VALID_TO` DATE NULL AFTER `VALID_FROM`;

ALTER TABLE `study`.`address` 
ADD COLUMN `VALID_FROM` DATE NULL AFTER `SOURCE`,
ADD COLUMN `VALID_TO` DATE NULL AFTER `VALID_FROM`;

/**auditing purpose **/
ALTER TABLE `audit`.`aud_address` 
ADD COLUMN `VALID_FROM` DATE NULL AFTER `STATE_ID`,
ADD COLUMN `VALID_TO` DATE NULL AFTER `VALID_FROM`;


