ALTER TABLE `lims`.`inv_site` 
ADD UNIQUE INDEX `UNIQUE_SITE_NAME` (`NAME` ASC);

ALTER TABLE `lims`.`inv_freezer` 
ADD UNIQUE INDEX `UNIQUE_FREEZER_NAME` (`SITE_ID` ASC, `NAME` ASC);

ALTER TABLE `lims`.`inv_rack` 
ADD UNIQUE INDEX `UNIQUE_RACK_NAME` (`FREEZER_ID` ASC, `NAME` ASC);

ALTER TABLE `lims`.`inv_box` 
ADD UNIQUE INDEX `UNIQUE_BOX_NAME` (`RACK_ID` ASC, `NAME` ASC);





