CREATE TABLE `spark`.`computation` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(50) NULL,
  `DESCRIPTION` VARCHAR(255) NULL,
  `STATUS` VARCHAR(25) NULL,
  `MICRO_SERVICE_ID` INT(11) NULL,
  `CHECKSUM` VARCHAR(255) NULL,
  `USER_ID` VARCHAR(100) NULL,
  `PROGRAM_NAME` TEXT NULL,
  `PROGRAM_ID` VARCHAR(1000) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


