USE `audit`;
-- the times 1000 is to shift the timestamp to what Envers sets for the timestamps
-- INSERT INTO REVINFO(ID, TIMESTAMP) values (1, UNIX_TIMESTAMP()*1000);

SET @REV = 1;

INSERT INTO aud_address(ID, REV, REVTYPE, ADDRESS_LINE_1, CITY, COMMENTS, DATE_RECEIVED, OTHER_STATE, POST_CODE, PREFERRED_MAILING_ADDRESS, SOURCE, STREET_ADDRESS, ADDRESS_STATUS_ID, ADDRESS_TYPE_ID, COUNTRY_ID, STATE_ID) 
select ID, @REV, 0, ADDRESS_LINE_1, CITY, COMMENTS, DATE_RECEIVED, OTHER_STATE, POST_CODE, PREFERRED_MAILING_ADDRESS, SOURCE, STREET_ADDRESS, ADDRESS_STATUS_ID, ADDRESS_TYPE_ID, COUNTRY_ID, STATE_ID from `study`.`address`;

INSERT INTO aud_affection(ID, REV, REVTYPE, RECORD_DATE, AFFECTION_STATUS_ID, DISEASE_ID, STUDY_ID, LINKSUBJECTSTUDY_ID)
select ID, @REV, 0, RECORD_DATE, AFFECTION_STATUS_ID, DISEASE_ID, STUDY_ID, LINKSUBJECTSTUDY_ID from `disease`.`affection`;

INSERT INTO aud_affection_custom_field_data (ID, REV, REVTYPE, DATE_DATA_VALUE, ERROR_DATA_VALUE, NUMBER_DATA_VALUE, TEXT_DATA_VALUE, AFFECTION_ID, CUSTOM_FIELD_DISPLAY_ID)
select ID, @REV, 0, DATE_DATA_VALUE, ERROR_DATA_VALUE, NUMBER_DATA_VALUE, TEXT_DATA_VALUE, AFFECTION_ID, CUSTOM_FIELD_DISPLAY_ID from `disease`.`affection_custom_field_data`;

INSERT INTO `aud_affection_position` (`REV`, `AFFECTION_ID`, `POSITION_ID`, `REVTYPE`)
select @REV, `AFFECTION_ID`, `POSITION_ID`, 0 from `disease`.`affection_position`;

INSERT INTO `aud_ark_user_role` (`ID`, `REV`, `REVTYPE`, `ARK_MODULE_ID`, `ARK_ROLE_ID`, `ARK_USER_ID`, `STUDY_ID`)
select `ID`, @REV, 0, `ARK_MODULE_ID`, `ARK_ROLE_ID`, `ARK_USER_ID`, `STUDY_ID` from `study`.`ark_user_role`;

INSERT INTO `aud_barcode_label` (`ID`, `REV`, `REVTYPE`, `BARCODE_PRINTER_NAME`, `DESCRIPTION`, `LABEL_PREFIX`, `LABEL_SUFFIX`, `NAME`, `VERSION`, `STUDY_ID`)
select `ID`, @REV, 0, `BARCODE_PRINTER_NAME`, `DESCRIPTION`, `LABEL_PREFIX`, `LABEL_SUFFIX`, `NAME`, `VERSION`, `STUDY_ID` from `lims`.`barcode_label`;

INSERT INTO `aud_barcode_label_data` (`ID`, `REV`, `REVTYPE`, `X_COORD`, `Y_COORD`, `COMMAND`, `DATA`, `LINE_FEED`, `P1`, `P2`, `P3`, `P4`, `P5`, `P6`, `P7`, `P8`, `QUOTE_LEFT`, `QUOTE_RIGHT`, `BARCODE_LABEL_ID`)
select `ID`, @REV, 0, `X_COORD`, `Y_COORD`, `COMMAND`, `DATA`, `LINE_FEED`, `P1`, `P2`, `P3`, `P4`, `P5`, `P6`, `P7`, `P8`, `QUOTE_LEFT`, `QUOTE_RIGHT`, `BARCODE_LABEL_ID` from `lims`.`barcode_label_data`;

INSERT INTO `aud_bilable_item` (`id`, `REV`, `REVTYPE`, `ATTACHMENT_FILENAME`, `ATTACHMENT_PAYLOAD`, `COMMENCE_DATE`, `DESCRIPTION`, `INVOICE`, `ITEM_COST`, `QUANTITY`, `STUDY_ID`, `TOTAL_COST`, `TOTAL_GST`, `TYPE`, `BILLABLE_TYPE`, `REQUEST_ID`)
select `id`, @REV, 0, `ATTACHMENT_FILENAME`, `ATTACHMENT_PAYLOAD`, `COMMENCE_DATE`, `DESCRIPTION`, `INVOICE`, `ITEM_COST`, `QUANTITY`, `STUDY_ID`, `TOTAL_COST`, `TOTAL_GST`, `TYPE`, `BILLABLE_TYPE`, `REQUEST_ID` from `admin`.`bilable_item`;

INSERT INTO `aud_billable_item_type` (`ID`, `REV`, `REVTYPE`, `DESCRIPTION`, `ITEM_NAME`, `QUANTITY_PER_UNIT`, `QUANTITY_TYPE`, `STUDY_ID`, `TYPE`, `UNIT_PRICE`, `STATUS_ID`)
select `ID`, @REV, 0, `DESCRIPTION`, `ITEM_NAME`, `QUANTITY_PER_UNIT`, `QUANTITY_TYPE`, `STUDY_ID`, `TYPE`, `UNIT_PRICE`, `STATUS_ID` from `admin`.`billable_item_type`;

INSERT INTO `aud_bio_transaction` (`id`, `REV`, `REVTYPE`, `QUANTITY`, `REASON`, `RECORDER`, `TRANSACTION_DATE`, `REQUEST_ID`, `BIOSPECIMEN_ID`, `STATUS_ID`, `UNIT_ID`)
select `id`, @REV, 0, `QUANTITY`, `REASON`, `RECORDER`, `TRANSACTION_DATE`, `REQUEST_ID`, `BIOSPECIMEN_ID`, `STATUS_ID`, `UNIT_ID` from `lims`.`bio_transaction`;

INSERT INTO `aud_biocollection` (`ID`, `REV`, `REVTYPE`, `BIOCOLLECTION_UID`, `COLLECTIONDATE`, `COLLECTIONGROUP`, `COLLECTIONGROUP_ID`, `COMMENTS`, `DELETED`, `DIAG_CATEGORY`, `DIAG_DATE`, `DISCHARGEDATE`, `EPISODE_DESC`, `EPISODE_NUM`, `HOSPITAL`, `HOSPITAL_UR`, `NAME`, `PATHLABNO`, `PATIENTAGE`, `REF_DOCTOR`, `SURGERYDATE`, `TIMESTAMP`, `TISSUECLASS`, `TISSUETYPE`, `LINK_SUBJECT_STUDY_ID`, `STUDY_ID`)
select `ID`, @REV, 0, `BIOCOLLECTION_UID`, `COLLECTIONDATE`, `COLLECTIONGROUP`, `COLLECTIONGROUP_ID`, `COMMENTS`, `DELETED`, `DIAG_CATEGORY`, `DIAG_DATE`, `DISCHARGEDATE`, `EPISODE_DESC`, `EPISODE_NUM`, `HOSPITAL`, `HOSPITAL_UR`, `NAME`, `PATHLABNO`, `PATIENTAGE`, `REF_DOCTOR`, `SURGERYDATE`, `TIMESTAMP`, `TISSUECLASS`, `TISSUETYPE`, `LINK_SUBJECT_STUDY_ID`, `STUDY_ID` from `lims`.`biocollection`;

INSERT INTO `aud_biocollection_custom_field_data` (`ID`, `REV`, `REVTYPE`, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `BIO_COLLECTION_ID`, `CUSTOM_FIELD_DISPLAY_ID`)
select `ID`, @REV, 0, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `BIO_COLLECTION_ID`, `CUSTOM_FIELD_DISPLAY_ID` from `lims`.`biocollection_custom_field_data`;

INSERT INTO `aud_biospecimen` (`id`, `REV`, `REVTYPE`, `BARCODED`, `BIOSPECIMEN_UID`, `COMMENTS`, `CONCENTRATION`, `DELETED`, `DEPTH`, `OLD_ID`, `OTHERID`, `PARENTID`, `PROCESSED_DATE`, `PROCESSED_TIME`, `PURITY`, `QTY_COLLECTED`, `QTY_REMOVED`, `QUANTITY`, `SAMPLE_DATE`, `SAMPLE_TIME`, `SUBSTUDY_ID`, `TIMESTAMP`, `BIOSPECIMEN_ANTICOAGULANT_ID`, `BIOSPECIMEN_PROTOCOL_ID`, `BIOSPECIMEN_GRADE_ID`, `LINK_SUBJECT_STUDY_ID`, `PARENT_ID`, `BIOSPECIMEN_QUALITY_ID`, `SAMPLETYPE_ID`, `BIOSPECIMEN_SPECIES_ID`, `BIOSPECIMEN_STATUS_ID`, `BIOSPECIMEN_STORAGE_ID`, `STUDY_ID`, `TREATMENT_TYPE_ID`, `UNIT_ID`)
select `id`, @REV, 0, `BARCODED`, `BIOSPECIMEN_UID`, `COMMENTS`, `CONCENTRATION`, `DELETED`, `DEPTH`, `OLD_ID`, `OTHERID`, `PARENTID`, `PROCESSED_DATE`, `PROCESSED_TIME`, `PURITY`, `QTY_COLLECTED`, `QTY_REMOVED`, `QUANTITY`, `SAMPLE_DATE`, `SAMPLE_TIME`, `SUBSTUDY_ID`, `TIMESTAMP`, `BIOSPECIMEN_ANTICOAGULANT_ID`, `BIOSPECIMEN_PROTOCOL_ID`, `BIOSPECIMEN_GRADE_ID`, `LINK_SUBJECT_STUDY_ID`, `PARENT_ID`, `BIOSPECIMEN_QUALITY_ID`, `SAMPLETYPE_ID`, `BIOSPECIMEN_SPECIES_ID`, `BIOSPECIMEN_STATUS_ID`, `BIOSPECIMEN_STORAGE_ID`, `STUDY_ID`, `TREATMENT_TYPE_ID`, `UNIT_ID` from `lims`.`biospecimen`;

INSERT INTO `aud_biospecimen_custom_field_data` (`ID`, `REV`, `REVTYPE`, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `BIOSPECIMEN_ID`, `CUSTOM_FIELD_DISPLAY_ID`)
select `ID`, @REV, 0, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `BIOSPECIMEN_ID`, `CUSTOM_FIELD_DISPLAY_ID` from `lims`.`biospecimen_custom_field_data`;

INSERT INTO `aud_biospecimen_species` (`id`, `REV`, `REVTYPE`, `NAME`)
select `id`, @REV, 0, `NAME` from `lims`.`biospecimen_species`;

INSERT INTO `aud_config_fields` (`id`, `REV`, `REVTYPE`, `description`, `name`, `TYPE`)
select `id`, @REV, 0, `description`, `name`, `TYPE` from `config`.`config_fields`;

INSERT INTO `aud_consent` (`ID`, `REV`, `REVTYPE`, `COMMENTS`, `COMPLETED_DATE`, `CONSENT_DATE`, `CONSENTED_BY`, `RECEIVED_DATE`, `REQUESTED_DATE`, `CONSENT_DOWNLOADED_ID`, `CONSENT_STATUS_ID`, `CONSENT_TYPE_ID`, `LINK_SUBJECT_STUDY_ID`, `STUDY_ID`, `STUDY_COMP_ID`, `STUDY_COMP_STATUS_ID`)
select `ID`, @REV, 0, `COMMENTS`, `COMPLETED_DATE`, `CONSENT_DATE`, `CONSENTED_BY`, `RECEIVED_DATE`, `REQUESTED_DATE`, `CONSENT_DOWNLOADED_ID`, `CONSENT_STATUS_ID`, `CONSENT_TYPE_ID`, `LINK_SUBJECT_STUDY_ID`, `STUDY_ID`, `STUDY_COMP_ID`, `STUDY_COMP_STATUS_ID` from `study`.`consent`;

INSERT INTO `aud_correspondences` (`ID`, `REV`, `REVTYPE`, `ATTACHMENT_CHECKSUM`, `ATTACHMENT_FILE_ID`, `ATTACHMENT_FILENAME`, `ATTACHMENT_PAYLOAD`, `COMMENTS`, `DATE`, `DETAILS`, `REASON`, `TIME`, `BILLABLE_ITEM_ID`, `DIRECTION_TYPE_ID`, `MODE_TYPE_ID`, `OUTCOME_TYPE_ID`, `LINK_SUBJECT_STUDY_ID`, `ARK_USER_ID`)
select `ID`, @REV, 0, `ATTACHMENT_CHECKSUM`, `ATTACHMENT_FILE_ID`, `ATTACHMENT_FILENAME`, `ATTACHMENT_PAYLOAD`, `COMMENTS`, `DATE`, `DETAILS`, `REASON`, `TIME`, `BILLABLE_ITEM_ID`, `DIRECTION_TYPE_ID`, `MODE_TYPE_ID`, `OUTCOME_TYPE_ID`, `LINK_SUBJECT_STUDY_ID`, `ARK_USER_ID` from `study`.`correspondences`;

INSERT INTO `aud_custom_field` (`ID`, `REV`, `REVTYPE`, `HAS_DATA`, `DEFAULT_VALUE`, `description`, `ENCODED_VALUES`, `CUSTOM_FIELD_LABEL`, `MAX_VALUE`, `MIN_VALUE`, `MISSING_VALUE`, `NAME`, `UNIT_TYPE_IN_TEXT`, `ARK_FUNCTION_ID`, `CATEGORY_ID`, `FIELD_TYPE_ID`, `STUDY_ID`, `UNIT_TYPE_ID`)
select `ID`, @REV, 0, `HAS_DATA`, `DEFAULT_VALUE`, `description`, `ENCODED_VALUES`, `CUSTOM_FIELD_LABEL`, `MAX_VALUE`, `MIN_VALUE`, `MISSING_VALUE`, `NAME`, `UNIT_TYPE_IN_TEXT`, `ARK_FUNCTION_ID`, `CATEGORY_ID`, `FIELD_TYPE_ID`, `STUDY_ID`, `UNIT_TYPE_ID` from `study`.`custom_field`;

INSERT INTO `aud_custom_field_display` (`ID`, `REV`, `REVTYPE`, `ALLOW_MULTIPLE_SELECTION`, `REQUIRED`, `REQUIRED_MESSAGE`, `SEQUENCE`, `CUSTOM_FIELD_ID`, `CUSTOM_FIELD_GROUP_ID`)
select `ID`, @REV, 0, `ALLOW_MULTIPLE_SELECTION`, `REQUIRED`, `REQUIRED_MESSAGE`, `SEQUENCE`, `CUSTOM_FIELD_ID`, `CUSTOM_FIELD_GROUP_ID` from `study`.`custom_field_display`;

INSERT INTO `aud_custom_field_group` (`ID`, `REV`, `REVTYPE`, `DESCRIPTION`, `NAME`, `PUBLISHED`, `ARK_FUNCTION_ID`, `STUDY_ID`)
select `ID`, @REV, 0, `DESCRIPTION`, `NAME`, `PUBLISHED`, `ARK_FUNCTION_ID`, `STUDY_ID` from `study`.`custom_field_group`;

INSERT INTO `aud_disease` (`ID`, `REV`, `REVTYPE`, `NAME`, `STUDY_ID`)
select `ID`, @REV, 0, `NAME`, `STUDY_ID` from `disease`.`disease`;

INSERT INTO `aud_disease_custom_fields` (`REV`, `DISEASE_ID`, `CUSTOM_FIELD_ID`, `REVTYPE`)
select @REV, `DISEASE_ID`, `CUSTOM_FIELD_ID`, 0 from `disease`.`disease_custom_fields`;

INSERT INTO `aud_gene` (`ID`, `REV`, `REVTYPE`, `NAME`, `STUDY_ID`)
select `ID`, @REV, 0, `NAME`, `STUDY_ID` from `disease`.`gene`;

INSERT INTO `aud_gene_disease` (`REV`, `GENE_ID`, `DISEASE_ID`, `REVTYPE`)
select @REV, `GENE_ID`, `DISEASE_ID`, 0 from `disease`.`gene_disease`;

INSERT INTO `aud_inv_box` (`id`, `REV`, `REVTYPE`, `AVAILABLE`, `CAPACITY`, `DELETED`, `NAME`, `NOOFCOL`, `NOOFROW`, `TIMESTAMP`, `TRANSFER_ID`, `TYPE`, `COLNOTYPE_ID`, `RACK_ID`, `ROWNOTYPE_ID`)
select `id`, @REV, 0, `AVAILABLE`, `CAPACITY`, `DELETED`, `NAME`, `NOOFCOL`, `NOOFROW`, `TIMESTAMP`, `TRANSFER_ID`, `TYPE`, `COLNOTYPE_ID`, `RACK_ID`, `ROWNOTYPE_ID` from `lims`.`inv_box`;

INSERT INTO `aud_inv_cell` (`id`, `REV`, `REVTYPE`, `COLNO`, `DELETED`, `ROWNO`, `STATUS`, `TIMESTAMP`, `BIOSPECIMEN_ID`, `BOX_ID`)
select `id`, @REV, 0, `COLNO`, `DELETED`, `ROWNO`, `STATUS`, `TIMESTAMP`, `BIOSPECIMEN_ID`, `BOX_ID` from `lims`.`inv_cell`;

INSERT INTO `aud_inv_freezer` (`id`, `REV`, `REVTYPE`, `AVAILABLE`, `CAPACITY`, `COMMISSIONDATE`, `DECOMMISSIONDATE`, `DELETED`, `DESCRIPTION`, `LASTSERVICEDATE`, `LASTSERVICENOTE`, `LOCATION`, `NAME`, `STATUS`, `TIMESTAMP`, `SITE_ID`)
select `id`, @REV, 0, `AVAILABLE`, `CAPACITY`, `COMMISSIONDATE`, `DECOMMISSIONDATE`, `DELETED`, `DESCRIPTION`, `LASTSERVICEDATE`, `LASTSERVICENOTE`, `LOCATION`, `NAME`, `STATUS`, `TIMESTAMP`, `SITE_ID` from `lims`.`inv_freezer`;

INSERT INTO `aud_inv_rack` (`id`, `REV`, `REVTYPE`, `AVAILABLE`, `CAPACITY`, `DELETED`, `DESCRIPTION`, `NAME`, `TIMESTAMP`, `FREEZER_ID`)
select `id`, @REV, 0, `AVAILABLE`, `CAPACITY`, `DELETED`, `DESCRIPTION`, `NAME`, `TIMESTAMP`, `FREEZER_ID` from `lims`.`inv_rack`;

INSERT INTO `aud_inv_site` (`id`, `REV`, `REVTYPE`, `ADDRESS`, `CONTACT`, `DELETED`, `LDAP_GROUP`, `NAME`, `PHONE`, `TIMESTAMP`)
select `id`, @REV, 0, `ADDRESS`, `CONTACT`, `DELETED`, `LDAP_GROUP`, `NAME`, `PHONE`, `TIMESTAMP` from `lims`.`inv_site`;

INSERT INTO `aud_link_study_studycomp` (`ID`, `REV`, `REVTYPE`, `STUDY_ID`, `STUDY_COMP_ID`, `STUDY_COMP_STATUS_ID`)
select `ID`, @REV, 0, `STUDY_ID`, `STUDY_COMP_ID`, `STUDY_COMP_STATUS_ID` from `study`.`link_study_studycomp`;

INSERT INTO `aud_link_subject_contact` (`ID`, `REV`, `REVTYPE`, `FAMILY_ID`, `PERSON_CONTACT_ID`, `PERSON_SUBJECT_ID`, `RELATIONSHIP_ID`, `STUDY_ID`)
select `ID`, @REV, 0, `FAMILY_ID`, `PERSON_CONTACT_ID`, `PERSON_SUBJECT_ID`, `RELATIONSHIP_ID`, `STUDY_ID` from `study`.`link_subject_contact`;

INSERT INTO `aud_link_subject_study` (`ID`, `REV`, `REVTYPE`, `COMMENTS`, `CONSENT_DATE`, `HEARD_ABOUT_STUDY`, `SUBJECT_UID`, `CONSENT_DOWNLOADED`, `CONSENT_STATUS_ID`, `CONSENT_TO_ACTIVE_CONTACT_ID`, `CONSENT_TO_PASSIVE_DATA_GATHERING_ID`, `CONSENT_TO_USE_DATA_ID`, `CONSENT_TYPE_ID`, `PERSON_ID`, `STUDY_ID`, `SUBJECT_STATUS_ID`)
select `ID`, @REV, 0, `COMMENTS`, `CONSENT_DATE`, `HEARD_ABOUT_STUDY`, `SUBJECT_UID`, `CONSENT_DOWNLOADED`, `CONSENT_STATUS_ID`, `CONSENT_TO_ACTIVE_CONTACT_ID`, `CONSENT_TO_PASSIVE_DATA_GATHERING_ID`, `CONSENT_TO_USE_DATA_ID`, `CONSENT_TYPE_ID`, `PERSON_ID`, `STUDY_ID`, `SUBJECT_STATUS_ID` from `study`.`link_subject_study`;

INSERT INTO `aud_link_subject_studycomp` (`ID`, `REV`, `REVTYPE`, `PERSON_SUBJECT_ID`, `STUDY_ID`, `STUDY_COMP_ID`, `STUDY_COMP_STATUS_ID`)
select `ID`, @REV, 0, `PERSON_SUBJECT_ID`, `STUDY_ID`, `STUDY_COMP_ID`, `STUDY_COMP_STATUS_ID` from `study`.`link_subject_studycomp`;

INSERT INTO `aud_mutation` (`ID`, `REV`, `REVTYPE`, `screened`, `tested`, `DISEASE_ID`, `LINK_SUBJECT_STUDY_ID`)
select `ID`, @REV, 0, `screened`, `tested`, `DISEASE_ID`, `LINKSUBJECTSTUDY_ID` from `disease`.`mutation`;

INSERT INTO `aud_otherid` (`ID`, `REV`, `REVTYPE`, `OtherID`, `OtherID_Source`, `PersonID`)
select `ID`, @REV, 0, `OtherID`, `OtherID_Source`, `PersonID` from `study`.`otherid`;

INSERT INTO `aud_person` (`ID`, `REV`, `REVTYPE`, `CAUSE_OF_DEATH`, `DATE_LAST_KNOWN_ALIVE`, `DATE_OF_BIRTH`, `DATE_OF_DEATH`, `FIRST_NAME`, `LAST_NAME`, `MIDDLE_NAME`, `OTHER_EMAIL`, `PREFERRED_EMAIL`, `PREFERRED_NAME`, `GENDER_TYPE_ID`, `MARITAL_STATUS_ID`, `OTHER_EMAIL_STATUS`, `PERSON_CONTACT_METHOD_ID`, `PREFERRED_EMAIL_STATUS`, `TITLE_TYPE_ID`, `VITAL_STATUS_ID`)
select `ID`, @REV, 0, `CAUSE_OF_DEATH`, `DATE_LAST_KNOWN_ALIVE`, `DATE_OF_BIRTH`, `DATE_OF_DEATH`, `FIRST_NAME`, `LAST_NAME`, `MIDDLE_NAME`, `OTHER_EMAIL`, `PREFERRED_EMAIL`, `PREFERRED_NAME`, `GENDER_TYPE_ID`, `MARITAL_STATUS_ID`, `OTHER_EMAIL_STATUS`, `PERSON_CONTACT_METHOD_ID`, `PREFERRED_EMAIL_STATUS`, `TITLE_TYPE_ID`, `VITAL_STATUS_ID` from `study`.`person`;

INSERT INTO `aud_person_lastname_history` (`ID`, `REV`, `REVTYPE`, `LASTNAME`, `PERSON_ID`)
select `ID`, @REV, 0, `LASTNAME`, `PERSON_ID` from `study`.`person_lastname_history`;

INSERT INTO `aud_pheno_collection` (`ID`, `REV`, `REVTYPE`, `DESCRIPTION`, `RECORD_DATE`, `REVIEWED_DATE`, `LINK_SUBJECT_STUDY_ID`, `CUSTOM_FIELD_GROUP_ID`, `REVIEWED_BY_ID`, `QUESTIONNAIRE_STATUS_ID`)
select `ID`, @REV, 0, `DESCRIPTION`, `RECORD_DATE`, `REVIEWED_DATE`, `LINK_SUBJECT_STUDY_ID`, `CUSTOM_FIELD_GROUP_ID`, `REVIEWED_BY_ID`, `QUESTIONNAIRE_STATUS_ID` from `pheno`.`pheno_collection`;

INSERT INTO `aud_pheno_data` (`ID`, `REV`, `REVTYPE`, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `CUSTOM_FIELD_DISPLAY_ID`, `PHENO_COLLECTION_ID`)
select `ID`, @REV, 0, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `CUSTOM_FIELD_DISPLAY_ID`, `PHENO_COLLECTION_ID` from `pheno`.`pheno_data`;

INSERT INTO `aud_phone` (`ID`, `REV`, `REVTYPE`, `AREA_CODE`, `COMMENT`, `DATE_RECEIVED`, `PHONE_NUMBER`, `SOURCE`, `PERSON_ID`, `PHONE_TYPE_ID`)
select `ID`, @REV, 0, `AREA_CODE`, `COMMENT`, `DATE_RECEIVED`, `PHONE_NUMBER`, `SOURCE`, `PERSON_ID`, `PHONE_TYPE_ID` from `study`.`phone`;

INSERT INTO `aud_position` (`ID`, `REV`, `REVTYPE`, `NAME`, `GENE_ID`)
select `ID`, @REV, 0, `NAME`, `GENE_ID` from `disease`.`position`;

INSERT INTO `aud_researcher` (`ID`, `REV`, `REVTYPE`, `ACCOUNT_NAME`, `ACCOUNT_NUMBER`, `ADDRESS`, `BANK`, `BSB`, `COMMENT`, `CREATED_DATE`, `EMAIL`, `FAX`, `FIRST_NAME`, `LAST_NAME`, `MOBILE`, `OFFICE_PHONE`, `ORGANIZATION`, `STUDY_ID`, `BILLING_TYPE_ID`, `ROLE_ID`, `STATUS_ID`, `TITLE_TYPE_ID`)
select `ID`, @REV, 0, `ACCOUNT_NAME`, `ACCOUNT_NUMBER`, `ADDRESS`, `BANK`, `BSB`, `COMMENT`, `CREATED_DATE`, `EMAIL`, `FAX`, `FIRST_NAME`, `LAST_NAME`, `MOBILE`, `OFFICE_PHONE`, `ORGANIZATION`, `STUDY_ID`, `BILLING_TYPE_ID`, `ROLE_ID`, `STATUS_ID`, `TITLE_TYPE_ID` from `admin`.`researcher`;

INSERT INTO `aud_study` (`ID`, `REV`, `REVTYPE`, `AUTO_CONSENT`, `AUTO_GENERATE_BIOCOLLECTIONUID`, `AUTO_GENERATE_BIOSPECIMENUID`, `AUTO_GENERATE_SUBJECTUID`, `CHIEF_INVESTIGATOR`, `CO_INVESTIGATOR`, `CONTACT_PERSON`, `CONTACT_PERSON_PHONE`, `DATE_OF_APPLICATION`, `DESCRIPTION`, `ESTIMATED_YEAR_OF_COMPLETION`, `FILENAME`, `LDAP_GROUP_NAME`, `NAME`, `STUDY_LOGO`, `SUB_STUDY_BIOSPECIMEN_PREFIX`, `SUBJECTUID_PREFIX`, `SUBJECTUID_START`, `PARENT_ID`, `STUDY_STATUS_ID`, `SUBJECTUID_PADCHAR_ID`, `SUBJECTUID_TOKEN_ID`)
select `ID`, @REV, 0, `AUTO_CONSENT`, `AUTO_GENERATE_BIOCOLLECTIONUID`, `AUTO_GENERATE_BIOSPECIMENUID`, `AUTO_GENERATE_SUBJECTUID`, `CHIEF_INVESTIGATOR`, `CO_INVESTIGATOR`, `CONTACT_PERSON`, `CONTACT_PERSON_PHONE`, `DATE_OF_APPLICATION`, `DESCRIPTION`, `ESTIMATED_YEAR_OF_COMPLETION`, `FILENAME`, `LDAP_GROUP_NAME`, `NAME`,  `STUDY_LOGO`, `SUB_STUDY_BIOSPECIMEN_PREFIX`, `SUBJECTUID_PREFIX`, `SUBJECTUID_START`, `PARENT_ID`, `STUDY_STATUS_ID`, `SUBJECTUID_PADCHAR_ID`, `SUBJECTUID_TOKEN_ID` from `study`.`study`;


INSERT INTO `aud_study_comp` (`ID`, `REV`, `REVTYPE`, `DESCRIPTION`, `KEYWORD`, `NAME`, `STUDY_ID`)
select `ID`, @REV, 0, `DESCRIPTION`, `KEYWORD`, `NAME`, `STUDY_ID` from `study`.`study_comp`;

INSERT INTO `aud_study_comp_status` (`ID`, `REV`, `REVTYPE`, `DESCRIPTION`, `NAME`)
select `ID`, @REV, 0, `DESCRIPTION`, `NAME` from `study`.`study_comp_status`;

INSERT INTO `aud_study_inv_site` (`id`, `REV`, `REVTYPE`, `INV_SITE_ID`, `STUDY_ID`)
select `id`, @REV, 0, `INV_SITE_ID`, `STUDY_ID` from `lims`.`study_inv_site`;

INSERT INTO `aud_subject_custom_field_data` (`ID`, `REV`, `REVTYPE`, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `CUSTOM_FIELD_DISPLAY_ID`, `LINK_SUBJECT_STUDY_ID`)
select `ID`, @REV, 0, `DATE_DATA_VALUE`, `ERROR_DATA_VALUE`, `NUMBER_DATA_VALUE`, `TEXT_DATA_VALUE`, `CUSTOM_FIELD_DISPLAY_ID`, `LINK_SUBJECT_STUDY_ID` from `study`.`subject_custom_field_data`;

INSERT INTO `aud_user_config` (`id`, `REV`, `REVTYPE`, `value`, `USER_ID`, `FIELD_ID`)
select `id`, @REV, 0, `value`, `USER_ID`, `FIELD_ID` from `config`.`user_config`;

INSERT INTO `aud_work_request` (`ID`, `REV`, `REVTYPE`, `COMMENCED_DATE`, `COMPLETED_DATE`, `DESCRIPTION`, `GST`, `GST_ALLOW`, `NAME`, `REQUESTED_DATE`, `STUDY_ID`, `STATUS_ID`, `RESEARCHER_ID`)
select `ID`, @REV, 0, `COMMENCED_DATE`, `COMPLETED_DATE`, `DESCRIPTION`, `GST`, `GST_ALLOW`, `NAME`, `REQUESTED_DATE`, `STUDY_ID`, `STATUS_ID`, `RESEARCHER_ID` from `admin`.`work_request`;
