use study;
ALTER TABLE `phone` 
ADD COLUMN `PREFERRED_PHONE_NUMBER` INT(11) NOT NULL AFTER `SILENT`;

use audit;
ALTER TABLE `aud_phone` 
ADD COLUMN `PREFERRED_PHONE_NUMBER` TINYINT(1) NULL AFTER `SILENT`;

