ALTER TABLE `study`.`custom_field_category` 
ADD COLUMN `CUSTOM_FIELD_TYPE_ID` INT(11) NULL AFTER `DESCRIPTION`,
ADD INDEX `FK_CUSTOMFIELD_CUSTOM_FIELD_TYPE_ID_idx` (`CUSTOM_FIELD_TYPE_ID` ASC);
ALTER TABLE `study`.`custom_field_category` 
ADD CONSTRAINT `FK_CUSTOMFIELDCATEGORY_CUSTOM_FIELD_TYPE_ID`
  FOREIGN KEY (`CUSTOM_FIELD_TYPE_ID`)
  REFERENCES `study`.`custom_field_type` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

ALTER TABLE `audit`.`aud_custom_field_category` 
ADD COLUMN `CUSTOM_FIELD_TYPE_ID` BIGINT(20) NULL AFTER `DESCRIPTION`;
