ALTER TABLE `spark`.`analysis` 
ADD COLUMN `CHECKSUM` VARCHAR(255) NULL AFTER `JOB_ID`,
ADD COLUMN `SCRIPT_NAME` TEXT NULL AFTER `CHECKSUM`,
ADD COLUMN `SCRIPT_ID` VARCHAR(1000) NULL AFTER `SCRIPT_NAME`;

