ALTER TABLE `study`.`custom_field` 
DROP FOREIGN KEY `FK_CUSTOM_FIELD_CATEGORY`;

ALTER TABLE `study`.`custom_field` 
ADD CONSTRAINT `FK_CUSTOM_FIELD_CUSTOM_FIELD_CATEGORY_ID`
  FOREIGN KEY (`CATEGORY_ID`)
  REFERENCES `study`.`custom_field_category` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

