ALTER TABLE `lims`.`biocollection` ADD `NATURAL_UID` VARCHAR(500)  NULL  DEFAULT NULL  AFTER `BIOCOLLECTION_UID`;
ALTER TABLE `lims`.`biospecimen` ADD `NATURAL_UID` VARCHAR(500)  NULL  DEFAULT NULL  AFTER `BIOSPECIMEN_UID`;
