use pheno;
ALTER TABLE `pheno`.`pheno_dataset_field` 
CHANGE COLUMN `ALLOW_MULTIPLE_SELECTION` `ALLOW_MULTIPLE_SELECTION` TINYINT(1) NOT NULL DEFAULT 0 ;

use audit;
ALTER TABLE `audit`.`aud_pheno_dataset_field` 
ADD COLUMN `REQUIRED` BIGINT(20) NULL AFTER `UNIT_TYPE_IN_TEXT`,
ADD COLUMN `ALLOW_MULTIPLE_SELECTION` TINYINT(20) NOT NULL DEFAULT 0 AFTER `REQUIRED`;


use audit;
ALTER TABLE `audit`.`aud_pheno_dataset_field_display` 
ADD COLUMN `PHENO_DATASET_CATEGORY_ID` INT(11) NULL AFTER `PHENO_DATASET_FIELD_GROUP_ID`,
ADD COLUMN `PHENO_DATASET_CATEGORY_ORDER_NUMBER` INT(11) NULL AFTER `PHENO_DATASET_CATEGORY_ID`,
ADD COLUMN `PHENO_DATASET_FIELD_ORDER_NUMBER` INT(11) NULL AFTER `PHENO_DATASET_FIELD_ID`;



