CREATE TABLE `study`.`link_calendar_custom_field` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CALENDAR_ID` INT(11) NOT NULL,
  `CUSTOM_FIELD_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_CALENDAR_ID_idx` (`CALENDAR_ID` ASC),
  INDEX `FK_CUSTOM_FIELD_ID_idx` (`CUSTOM_FIELD_ID` ASC),
  CONSTRAINT `FK_CALENDAR_ID`
    FOREIGN KEY (`CALENDAR_ID`)
    REFERENCES `study`.`study_calendar` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_CUSTOM_FIELD_ID`
    FOREIGN KEY (`CUSTOM_FIELD_ID`)
    REFERENCES `study`.`custom_field` (`ID`)
    ON DELETE CASCADE
    ON UPDATE CASCADE);



