ALTER TABLE `config`.`user_config` 
DROP FOREIGN KEY `FKF893C6361DA086E1`;
ALTER TABLE `config`.`user_config` 
ADD CONSTRAINT `FKF893C6361DA086E1`
  FOREIGN KEY (`USER_ID`)
  REFERENCES `study`.`ark_user` (`ID`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;
