DROP TABLE IF EXISTS `pheno`.`pheno_field_category_upload`;
CREATE TABLE `pheno`.`pheno_field_category_upload` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `UPLOAD_ID` INT(11) NOT NULL,
  `PHENO_FIELD_CATEGORY_ID` INT(11) NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_PHENO_FIELD_CATEGORY_ID_idx` (`PHENO_FIELD_CATEGORY_ID` ASC),
  INDEX `FK_PHENO_UPLOAD_ID_idx` (`UPLOAD_ID` ASC),
  CONSTRAINT `FK_PHENO_FIELD_CATEGORY_ID` FOREIGN KEY (`PHENO_FIELD_CATEGORY_ID`) REFERENCES `pheno`.`pheno_dataset_category` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_PHENO_UPLOAD_ID` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `study`.`upload` (`ID`)ON DELETE NO ACTION
    ON UPDATE NO ACTION);

