ALTER TABLE `study`.`study` 
ADD COLUMN `STUDY_LOGO_CHECKSUM` VARCHAR(50) NULL DEFAULT NULL AFTER `AUTO_GENERATE_BIOCOLLECTIONUID`,
ADD COLUMN `STUDY_LOGO_FILE_ID` VARCHAR(1000) NULL DEFAULT NULL AFTER `STUDY_LOGO_CHECKSUM`;


ALTER TABLE `audit`.`aud_study` 
ADD COLUMN `STUDY_LOGO_CHECKSUM` VARCHAR(50) NULL DEFAULT NULL AFTER `SUBJECTUID_TOKEN_ID`,
ADD COLUMN `STUDY_LOGO_FILE_ID` VARCHAR(1000) NULL DEFAULT NULL AFTER `STUDY_LOGO_CHECKSUM`;


