
SET @EMAIL_STATUS_UNKNOWN=(SELECT ID FROM study.email_status WHERE NAME="Unknown");

UPDATE study.person SET OTHER_EMAIL_STATUS=@EMAIL_STATUS_UNKNOWN WHERE OTHER_EMAIL_STATUS IS NULL;
UPDATE study.person SET OTHER_EMAIL_STATUS=@EMAIL_STATUS_UNKNOWN WHERE OTHER_EMAIL_STATUS=0;
UPDATE study.person SET PREFERRED_EMAIL_STATUS=@EMAIL_STATUS_UNKNOWN WHERE PREFERRED_EMAIL_STATUS IS NULL;
UPDATE study.person SET PREFERRED_EMAIL_STATUS=@EMAIL_STATUS_UNKNOWN WHERE PREFERRED_EMAIL_STATUS=0;

INSERT INTO study.email_account (NAME, PRIMARY_ACCOUNT, PERSON_ID, EMAIL_ACCOUNT_TYPE_ID, EMAIL_STATUS_ID)
select p.PREFERRED_EMAIL as NAME, 1 as PRIMARY_ACCOUNT, p.id as PERSON_ID, 1 as EMAIL_ACCOUNT_TYPE_ID,p.PREFERRED_EMAIL_STATUS as EMAIL_STATUS_ID
from study.person p 
where (p.preferred_email is not null and p.preferred_email <> '');

INSERT INTO study.email_account (NAME, PRIMARY_ACCOUNT, PERSON_ID, EMAIL_ACCOUNT_TYPE_ID, EMAIL_STATUS_ID)
select p.OTHER_EMAIL as Name, 0 as PRIMARY_ACCOUNT, p.id as PERSON_ID, 1 as EMAIL_ACCOUNT_TYPE_ID, p.OTHER_EMAIL_STATUS as EMAIL_STATUS_ID
from study.person p 
where (p.other_email is not null and p.other_email <> '');
