ALTER TABLE `spark`.`data_source` 
ADD COLUMN `CHIP` VARCHAR(100) NULL AFTER `DIRECTORY`,
ADD COLUMN `SNP_COUNT` INT(11) NULL AFTER `CHIP`,
ADD COLUMN `SIZE` VARCHAR(45) NULL AFTER `SNP_COUNT`,
ADD COLUMN `OWNER` VARCHAR(100) NULL AFTER `SIZE`;

