ALTER TABLE `study`.`link_subject_study` 
ADD COLUMN `CONSENT_DATE_OF_CHANGE` DATE NULL AFTER `CONSENT_TO_USE_DATA_ID`;

ALTER TABLE `audit`.`aud_link_subject_study` 
ADD COLUMN `CONSENT_DATE_OF_CHANGE` DATE NULL AFTER `CONSENT_TO_USE_DATA_ID`;
