ALTER TABLE `study`.`link_subject_study` 
CHANGE COLUMN `FAMILY_ID` `FAMILY_UID` VARCHAR(50) NULL DEFAULT NULL ;

ALTER TABLE `study`.`link_subject_contact` 
CHANGE COLUMN `FAMILY_ID` `FAMILY_UID` INT(11) NOT NULL ;

ALTER TABLE `audit`.`aud_link_subject_study` 
CHANGE COLUMN `FAMILY_ID` `FAMILY_UID` VARCHAR(50) NULL DEFAULT NULL ;




