package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;

/**
 * Admissions generated by hbm2java
 */
public class Admissions implements java.io.Serializable {

	// Fields    

	/**
	 * 
	 */
	private static final long serialVersionUID = 1826957627188777613L;
	private BigDecimal admissionkey;
	private String timestamp;
	private BigDecimal deleted;
	private String comments;
	private String admissionid;
	private BigDecimal patientkey;
	private String hospital;
	private Date surgerydate;
	private String diagCategory;
	private String refDoctor;
	private Date admissiondate;
	private BigDecimal patientage;
	private Date dischargedate;
	private String hospitalUr;
	private Date diagDate;
	private BigDecimal collectiongroupkey;
	private String episodeNum;
	private String episodeDesc;
	private String collectiongroup;
	private String tissuetype;
	private String tissueclass;
	private String pathlabno;

	// Constructors

	/** default constructor */
	public Admissions() {
	}

	/** minimal constructor */
	public Admissions(BigDecimal admissionkey, BigDecimal patientkey) {
		this.admissionkey = admissionkey;
		this.patientkey = patientkey;
	}

	/** full constructor */
	public Admissions(BigDecimal admissionkey, BigDecimal deleted,
			String comments, String admissionid, BigDecimal patientkey,
			String hospital, Date surgerydate, String diagCategory,
			String refDoctor, Date admissiondate, BigDecimal patientage,
			Date dischargedate, String hospitalUr, Date diagDate,
			BigDecimal collectiongroupkey, String episodeNum,
			String episodeDesc, String collectiongroup, String tissuetype,
			String tissueclass, String pathlabno) {
		this.admissionkey = admissionkey;
		this.deleted = deleted;
		this.comments = comments;
		this.admissionid = admissionid;
		this.patientkey = patientkey;
		this.hospital = hospital;
		this.surgerydate = surgerydate;
		this.diagCategory = diagCategory;
		this.refDoctor = refDoctor;
		this.admissiondate = admissiondate;
		this.patientage = patientage;
		this.dischargedate = dischargedate;
		this.hospitalUr = hospitalUr;
		this.diagDate = diagDate;
		this.collectiongroupkey = collectiongroupkey;
		this.episodeNum = episodeNum;
		this.episodeDesc = episodeDesc;
		this.collectiongroup = collectiongroup;
		this.tissuetype = tissuetype;
		this.tissueclass = tissueclass;
		this.pathlabno = pathlabno;
	}

	// Property accessors
	public BigDecimal getAdmissionkey() {
		return this.admissionkey;
	}

	public void setAdmissionkey(BigDecimal admissionkey) {
		this.admissionkey = admissionkey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getDeleted() {
		return this.deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getAdmissionid() {
		return this.admissionid;
	}

	public void setAdmissionid(String admissionid) {
		this.admissionid = admissionid;
	}

	public BigDecimal getPatientkey() {
		return this.patientkey;
	}

	public void setPatientkey(BigDecimal patientkey) {
		this.patientkey = patientkey;
	}

	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	public Date getSurgerydate() {
		return this.surgerydate;
	}

	public void setSurgerydate(Date surgerydate) {
		this.surgerydate = surgerydate;
	}

	public String getDiagCategory() {
		return this.diagCategory;
	}

	public void setDiagCategory(String diagCategory) {
		this.diagCategory = diagCategory;
	}

	public String getRefDoctor() {
		return this.refDoctor;
	}

	public void setRefDoctor(String refDoctor) {
		this.refDoctor = refDoctor;
	}

	public Date getAdmissiondate() {
		return this.admissiondate;
	}

	public void setAdmissiondate(Date admissiondate) {
		this.admissiondate = admissiondate;
	}

	public BigDecimal getPatientage() {
		return this.patientage;
	}

	public void setPatientage(BigDecimal patientage) {
		this.patientage = patientage;
	}

	public Date getDischargedate() {
		return this.dischargedate;
	}

	public void setDischargedate(Date dischargedate) {
		this.dischargedate = dischargedate;
	}

	public String getHospitalUr() {
		return this.hospitalUr;
	}

	public void setHospitalUr(String hospitalUr) {
		this.hospitalUr = hospitalUr;
	}

	public Date getDiagDate() {
		return this.diagDate;
	}

	public void setDiagDate(Date diagDate) {
		this.diagDate = diagDate;
	}

	public BigDecimal getCollectiongroupkey() {
		return this.collectiongroupkey;
	}

	public void setCollectiongroupkey(BigDecimal collectiongroupkey) {
		this.collectiongroupkey = collectiongroupkey;
	}

	public String getEpisodeNum() {
		return this.episodeNum;
	}

	public void setEpisodeNum(String episodeNum) {
		this.episodeNum = episodeNum;
	}

	public String getEpisodeDesc() {
		return this.episodeDesc;
	}

	public void setEpisodeDesc(String episodeDesc) {
		this.episodeDesc = episodeDesc;
	}

	public String getCollectiongroup() {
		return this.collectiongroup;
	}

	public void setCollectiongroup(String collectiongroup) {
		this.collectiongroup = collectiongroup;
	}

	public String getTissuetype() {
		return this.tissuetype;
	}

	public void setTissuetype(String tissuetype) {
		this.tissuetype = tissuetype;
	}

	public String getTissueclass() {
		return this.tissueclass;
	}

	public void setTissueclass(String tissueclass) {
		this.tissueclass = tissueclass;
	}

	public String getPathlabno() {
		return this.pathlabno;
	}

	public void setPathlabno(String pathlabno) {
		this.pathlabno = pathlabno;
	}

}
