package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;

/**
 * Site generated by hbm2java
 */
public class Site implements java.io.Serializable {

	// Fields    

	private BigDecimal sitekey;
	private String timestamp;
	private BigDecimal deleted;
	private String contact;
	private String address;
	private String name;
	private String phone;

	// Constructors

	/** default constructor */
	public Site() {
	}

	/** minimal constructor */
	public Site(BigDecimal sitekey, String name) {
		this.sitekey = sitekey;
		this.name = name;
	}

	/** full constructor */
	public Site(BigDecimal sitekey, BigDecimal deleted, String contact,
			String address, String name, String phone) {
		this.sitekey = sitekey;
		this.deleted = deleted;
		this.contact = contact;
		this.address = address;
		this.name = name;
		this.phone = phone;
	}

	// Property accessors
	public BigDecimal getSitekey() {
		return this.sitekey;
	}

	public void setSitekey(BigDecimal sitekey) {
		this.sitekey = sitekey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getDeleted() {
		return this.deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}

	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
