package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;

/**
 * Tray generated by hbm2java
 */
public class Tray implements java.io.Serializable {

	// Fields    

	private BigDecimal traykey;
	private String timestamp;
	private BigDecimal deleted;
	private BigDecimal noofcol;
	private String colnotype;
	private BigDecimal capacity;
	private String name;
	private BigDecimal boxkey;
	private BigDecimal available;
	private BigDecimal noofrow;
	private String rownotype;

	// Constructors

	/** default constructor */
	public Tray() {
	}

	/** minimal constructor */
	public Tray(BigDecimal traykey, BigDecimal noofcol, String colnotype,
			BigDecimal boxkey, BigDecimal noofrow, String rownotype) {
		this.traykey = traykey;
		this.noofcol = noofcol;
		this.colnotype = colnotype;
		this.boxkey = boxkey;
		this.noofrow = noofrow;
		this.rownotype = rownotype;
	}

	/** full constructor */
	public Tray(BigDecimal traykey, BigDecimal deleted,
			BigDecimal noofcol, String colnotype, BigDecimal capacity,
			String name, BigDecimal boxkey, BigDecimal available,
			BigDecimal noofrow, String rownotype) {
		this.traykey = traykey;
		this.deleted = deleted;
		this.noofcol = noofcol;
		this.colnotype = colnotype;
		this.capacity = capacity;
		this.name = name;
		this.boxkey = boxkey;
		this.available = available;
		this.noofrow = noofrow;
		this.rownotype = rownotype;
	}

	// Property accessors
	public BigDecimal getTraykey() {
		return this.traykey;
	}

	public void setTraykey(BigDecimal traykey) {
		this.traykey = traykey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getDeleted() {
		return this.deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}

	public BigDecimal getNoofcol() {
		return this.noofcol;
	}

	public void setNoofcol(BigDecimal noofcol) {
		this.noofcol = noofcol;
	}

	public String getColnotype() {
		return this.colnotype;
	}

	public void setColnotype(String colnotype) {
		this.colnotype = colnotype;
	}

	public BigDecimal getCapacity() {
		return this.capacity;
	}

	public void setCapacity(BigDecimal capacity) {
		this.capacity = capacity;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getBoxkey() {
		return this.boxkey;
	}

	public void setBoxkey(BigDecimal boxkey) {
		this.boxkey = boxkey;
	}

	public BigDecimal getAvailable() {
		return this.available;
	}

	public void setAvailable(BigDecimal available) {
		this.available = available;
	}

	public BigDecimal getNoofrow() {
		return this.noofrow;
	}

	public void setNoofrow(BigDecimal noofrow) {
		this.noofrow = noofrow;
	}

	public String getRownotype() {
		return this.rownotype;
	}

	public void setRownotype(String rownotype) {
		this.rownotype = rownotype;
	}

}
