package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.util.Date;

/**
 * IxBiospecimen generated by hbm2java
 */
public class Biospecimen implements java.io.Serializable {

	// Fields    

	private long biospecimenkey;
	private String timestamp;
	private long deleted;
	private String encounter;
	private String otherid;
	private String storedIn;
	private Date sampleTime;
	private String grade;
	private long cellkey;
	private long depth;
	private String biospecimenid;
	private long parentkey;
	private Date sampledate;
	private long studykey;
	private Date extractedTime;
	private String parentid;
	private String location;
	private String sampletype;
	private String subtypedesc;
	private String species;
	private long patientkey;
	private Double qtyCollected;
	private Date dateextracted;
	private Double qtyRemoved;
	private Double gestat;
	private String comments;
	private String samplesubtype;
	private Date datedistributed;
	private String collaborator;
	private long admissionkey;
	private Double dnaconc;
	private Double purity;
	private String anticoag;
	private String extractMethod;

	// Constructors

	/** default constructor */
	public Biospecimen() {
	}

	/** minimal constructor */
	public Biospecimen(long biospecimenkey, String biospecimenid,
			String sampletype) {
		this.biospecimenkey = biospecimenkey;
		this.biospecimenid = biospecimenid;
		this.sampletype = sampletype;
	}

	/** full constructor */
	public Biospecimen(long biospecimenkey, long deleted,
			String encounter, String otherid, String storedIn, Date sampleTime,
			String grade, long cellkey, long depth,
			String biospecimenid, long parentkey, Date sampledate,
			long studykey, Date extractedTime, String parentid,
			String location, String sampletype, String subtypedesc,
			String species, long patientkey, Double qtyCollected,
			Date dateextracted, Double qtyRemoved, Double gestat,
			String comments, String samplesubtype, Date datedistributed,
			String collaborator, long admissionkey, Double dnaconc,
			Double purity, String anticoag, String extractMethod) {
		this.biospecimenkey = biospecimenkey;
		this.deleted = deleted;
		this.encounter = encounter;
		this.otherid = otherid;
		this.storedIn = storedIn;
		this.sampleTime = sampleTime;
		this.grade = grade;
		this.cellkey = cellkey;
		this.depth = depth;
		this.biospecimenid = biospecimenid;
		this.parentkey = parentkey;
		this.sampledate = sampledate;
		this.studykey = studykey;
		this.extractedTime = extractedTime;
		this.parentid = parentid;
		this.location = location;
		this.sampletype = sampletype;
		this.subtypedesc = subtypedesc;
		this.species = species;
		this.patientkey = patientkey;
		this.qtyCollected = qtyCollected;
		this.dateextracted = dateextracted;
		this.qtyRemoved = qtyRemoved;
		this.gestat = gestat;
		this.comments = comments;
		this.samplesubtype = samplesubtype;
		this.datedistributed = datedistributed;
		this.collaborator = collaborator;
		this.admissionkey = admissionkey;
		this.dnaconc = dnaconc;
		this.purity = purity;
		this.anticoag = anticoag;
		this.extractMethod = extractMethod;
	}

	// Property accessors
	public long getBiospecimenkey() {
		return this.biospecimenkey;
	}

	public void setBiospecimenkey(long biospecimenkey) {
		this.biospecimenkey = biospecimenkey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public long getDeleted() {
		return this.deleted;
	}

	public void setDeleted(long deleted) {
		this.deleted = deleted;
	}

	public String getEncounter() {
		return this.encounter;
	}

	public void setEncounter(String encounter) {
		this.encounter = encounter;
	}

	public String getOtherid() {
		return this.otherid;
	}

	public void setOtherid(String otherid) {
		this.otherid = otherid;
	}

	public String getStoredIn() {
		return this.storedIn;
	}

	public void setStoredIn(String storedIn) {
		this.storedIn = storedIn;
	}

	public Date getSampleTime() {
		return this.sampleTime;
	}

	public void setSampleTime(Date sampleTime) {
		this.sampleTime = sampleTime;
	}

	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	public long getCellkey() {
		return this.cellkey;
	}

	public void setCellkey(long cellkey) {
		this.cellkey = cellkey;
	}

	public long getDepth() {
		return this.depth;
	}

	public void setDepth(long depth) {
		this.depth = depth;
	}

	public String getBiospecimenid() {
		return this.biospecimenid;
	}

	public void setBiospecimenid(String biospecimenid) {
		this.biospecimenid = biospecimenid;
	}

	public long getParentkey() {
		return this.parentkey;
	}

	public void setParentkey(long parentkey) {
		this.parentkey = parentkey;
	}

	public Date getSampledate() {
		return this.sampledate;
	}

	public void setSampledate(Date sampledate) {
		this.sampledate = sampledate;
	}

	public long getStudykey() {
		return this.studykey;
	}

	public void setStudykey(long studykey) {
		this.studykey = studykey;
	}

	public Date getExtractedTime() {
		return this.extractedTime;
	}

	public void setExtractedTime(Date extractedTime) {
		this.extractedTime = extractedTime;
	}

	public String getParentid() {
		return this.parentid;
	}

	public void setParentid(String parentid) {
		this.parentid = parentid;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getSampletype() {
		return this.sampletype;
	}

	public void setSampletype(String sampletype) {
		this.sampletype = sampletype;
	}

	public String getSubtypedesc() {
		return this.subtypedesc;
	}

	public void setSubtypedesc(String subtypedesc) {
		this.subtypedesc = subtypedesc;
	}

	public String getSpecies() {
		return this.species;
	}

	public void setSpecies(String species) {
		this.species = species;
	}

	public long getPatientkey() {
		return this.patientkey;
	}

	public void setPatientkey(long patientkey) {
		this.patientkey = patientkey;
	}

	public Double getQtyCollected() {
		return this.qtyCollected;
	}

	public void setQtyCollected(Double qtyCollected) {
		this.qtyCollected = qtyCollected;
	}

	public Date getDateextracted() {
		return this.dateextracted;
	}

	public void setDateextracted(Date dateextracted) {
		this.dateextracted = dateextracted;
	}

	public Double getQtyRemoved() {
		return this.qtyRemoved;
	}

	public void setQtyRemoved(Double qtyRemoved) {
		this.qtyRemoved = qtyRemoved;
	}

	public Double getGestat() {
		return this.gestat;
	}

	public void setGestat(Double gestat) {
		this.gestat = gestat;
	}

	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	public String getSamplesubtype() {
		return this.samplesubtype;
	}

	public void setSamplesubtype(String samplesubtype) {
		this.samplesubtype = samplesubtype;
	}

	public Date getDatedistributed() {
		return this.datedistributed;
	}

	public void setDatedistributed(Date datedistributed) {
		this.datedistributed = datedistributed;
	}

	public String getCollaborator() {
		return this.collaborator;
	}

	public void setCollaborator(String collaborator) {
		this.collaborator = collaborator;
	}

	public long getAdmissionkey() {
		return this.admissionkey;
	}

	public void setAdmissionkey(long admissionkey) {
		this.admissionkey = admissionkey;
	}

	public Double getDnaconc() {
		return this.dnaconc;
	}

	public void setDnaconc(Double dnaconc) {
		this.dnaconc = dnaconc;
	}

	public Double getPurity() {
		return this.purity;
	}

	public void setPurity(Double purity) {
		this.purity = purity;
	}

	public String getAnticoag() {
		return this.anticoag;
	}

	public void setAnticoag(String anticoag) {
		this.anticoag = anticoag;
	}

	public String getExtractMethod() {
		return this.extractMethod;
	}

	public void setExtractMethod(String extractMethod) {
		this.extractMethod = extractMethod;
	}

}
