USE study;
SET FOREIGN_KEY_CHECKS=0;
ALTER TABLE `consent` DROP FOREIGN KEY `fk_link_subject_study`;
ALTER TABLE `consent` ADD CONSTRAINT `fk_link_subject_study` FOREIGN KEY (`LINK_SUBJECT_STUDY_ID`) REFERENCES `link_subject_study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `consent` DROP FOREIGN KEY `fk_study`;
ALTER TABLE `consent` ADD CONSTRAINT `fk_study` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `correspondences` DROP FOREIGN KEY `correspondences_study_id`;
ALTER TABLE `correspondences` ADD CONSTRAINT `correspondences_study_id` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `custom_field` DROP FOREIGN KEY `FK_CUSTOM_FIELD_STUDY_ID`;
ALTER TABLE `custom_field` ADD CONSTRAINT `FK_CUSTOM_FIELD_STUDY_ID` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `custom_field_display` DROP FOREIGN KEY `FK_CUSTOM_FIELD_GROUP_CUSTOM_FIELD_ID`;
ALTER TABLE `custom_field_display` ADD CONSTRAINT `FK_CUSTOM_FIELD_GROUP_CUSTOM_FIELD_ID` FOREIGN KEY (`CUSTOM_FIELD_ID`) REFERENCES `custom_field` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `custom_field_display` DROP FOREIGN KEY `FK_CUSTOM_FIELD_GROUP_ID`;
ALTER TABLE `custom_field_display` ADD CONSTRAINT `FK_CUSTOM_FIELD_GROUP_ID` FOREIGN KEY (`CUSTOM_FIELD_GROUP_ID`) REFERENCES `custom_field_group` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `custom_field_group` DROP FOREIGN KEY `FK_CUSTOM_FIELD_GROUP_STUDY_ID`;
ALTER TABLE `custom_field_group` ADD CONSTRAINT `FK_CUSTOM_FIELD_GROUP_STUDY_ID` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `custom_field_upload` DROP FOREIGN KEY `FK_CFU_CUSTOM_FIELD_ID`;
ALTER TABLE `custom_field_upload` ADD CONSTRAINT `FK_CFU_CUSTOM_FIELD_ID` FOREIGN KEY (`CUSTOM_FIELD_ID`) REFERENCES `custom_field` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `custom_field_upload` DROP FOREIGN KEY `FK_CFU_UPLOAD_ID`;
ALTER TABLE `custom_field_upload` ADD CONSTRAINT `FK_CFU_UPLOAD_ID` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `upload` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `link_study_substudy` DROP FOREIGN KEY `link_study_substudy_ibfk_1`;
ALTER TABLE `link_study_substudy` ADD CONSTRAINT `link_study_substudy_ibfk_1` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `link_subject_study` DROP INDEX `FK_LINK_SUBJECT_STUDY_COUNTRY`;
ALTER TABLE `link_subject_study` DROP INDEX `FK_LINK_SUBJECT_STUDY_STATE`;
ALTER TABLE `link_subject_study` DROP FOREIGN KEY `FK_LINK_SUBJECT_STUDY_STATE`;
ALTER TABLE `link_subject_study` DROP FOREIGN KEY `FK_LINK_SUBJECT_STUDY_COUNTRY`;
ALTER TABLE `link_subject_study` MODIFY COLUMN `CONSENT_TO_ACTIVE_CONTACT_ID`  int(11) NULL DEFAULT NULL AFTER `SUBJECT_UID`;
ALTER TABLE `link_subject_study` DROP COLUMN `AMDRF_ID`;
ALTER TABLE `link_subject_study` DROP COLUMN `STUDY_APPROACH_DATE`;
ALTER TABLE `link_subject_study` DROP COLUMN `SEND_NEWS_LETTER`;
ALTER TABLE `link_subject_study` DROP COLUMN `YEAR_OF_FIRST_MAMOGRAM`;
ALTER TABLE `link_subject_study` DROP COLUMN `YEAR_OF_RECENT_MAMOGRAM`;
ALTER TABLE `link_subject_study` DROP COLUMN `TOTAL_MAMOGRAMS`;
ALTER TABLE `link_subject_study` DROP COLUMN `SITE_STREET_ADDRESS`;
ALTER TABLE `link_subject_study` DROP COLUMN `SITE_CITY`;
ALTER TABLE `link_subject_study` DROP COLUMN `SITE_POST`;
ALTER TABLE `link_subject_study` DROP COLUMN `COUNTRY_ID`;
ALTER TABLE `link_subject_study` DROP COLUMN `STATE_ID`;
ALTER TABLE `link_subject_study` DROP PRIMARY KEY;
ALTER TABLE `link_subject_study` ADD PRIMARY KEY (`ID`);
ALTER TABLE `link_subject_study` DROP FOREIGN KEY `FK_LINK_SUBJECT_STUDY_STUDY_FK`;
ALTER TABLE `link_subject_study` ADD CONSTRAINT `FK_LINK_SUBJECT_STUDY_STUDY_FK` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE `padding_character` (
`ID`  int(11) NOT NULL ,
`NAME`  varchar(45) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL ,
PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
ROW_FORMAT=Compact
;
ALTER TABLE `person` ADD COLUMN `OTHER_ID`  int(11) NULL DEFAULT NULL AFTER `DATE_LAST_KNOWN_ALIVE`;
ALTER TABLE `person_lastname_history` ADD COLUMN `date_inserted`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP AFTER `LASTNAME`;
ALTER TABLE `study_comp` DROP FOREIGN KEY `study_comp_ibfk_1`;
ALTER TABLE `study_comp` ADD CONSTRAINT `study_comp_ibfk_1` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `subject_custom_field_data` DROP FOREIGN KEY `FK_CFD_LINK_SUBJECT_STUDY_ID`;
ALTER TABLE `subject_custom_field_data` ADD CONSTRAINT `FK_CFD_LINK_SUBJECT_STUDY_ID` FOREIGN KEY (`LINK_SUBJECT_STUDY_ID`) REFERENCES `link_subject_study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `subject_custom_field_data` DROP FOREIGN KEY `FK_CFD_CUSTOM_FIELD_DISPLAY_ID`;
ALTER TABLE `subject_custom_field_data` ADD CONSTRAINT `FK_CFD_CUSTOM_FIELD_DISPLAY_ID` FOREIGN KEY (`CUSTOM_FIELD_DISPLAY_ID`) REFERENCES `custom_field_display` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `subject_file` DROP FOREIGN KEY `fk_subject_file_subject`;
ALTER TABLE `subject_file` ADD CONSTRAINT `fk_subject_file_subject` FOREIGN KEY (`LINK_SUBJECT_STUDY_ID`) REFERENCES `link_subject_study` (`ID`) ON DELETE CASCADE ON UPDATE NO ACTION;
ALTER TABLE `upload` ADD COLUMN `STATUS`  enum('UPLOADED','PROCESSING','COMPLETE','ERRORS') CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL AFTER `ARK_FUNCTION_ID`;
ALTER TABLE `upload` DROP FOREIGN KEY `fk_upload_study`;
ALTER TABLE `upload` ADD CONSTRAINT `fk_upload_study` FOREIGN KEY (`STUDY_ID`) REFERENCES `study` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE `upload_error` (
`ID`  int(11) NOT NULL ,
`UPLOAD_ID`  int(11) NULL DEFAULT NULL ,
`ERROR_MSG`  varchar(256) CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL ,
`ROW_NUMBER`  int(11) NULL DEFAULT NULL ,
`ORIGINAL_ROW_DATA`  text CHARACTER SET latin1 COLLATE latin1_swedish_ci NULL ,
PRIMARY KEY (`ID`),
CONSTRAINT `FK_UPLOAD_ERROR_UPLOAD` FOREIGN KEY (`UPLOAD_ID`) REFERENCES `upload` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
INDEX `FK_UPLOAD_ERROR_UPLOAD` USING BTREE (`UPLOAD_ID`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=latin1 COLLATE=latin1_swedish_ci
ROW_FORMAT=Compact;
