use lims;
delete from `lims`.`bio_sampletype`;
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (1,'Blood','Blood');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (2,'Blood','Buffy Coat');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (3,'Blood','Buffy Coat (ACD)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (4,'Blood','Buffy Coat (EDTA)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (5,'Blood','Buffy Coat (LH)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (6,'Blood','Cord blood');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (7,'Blood','EDTA Blood');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (8,'Blood','Frozen Lymphocytes (F)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (9,'Blood','Lithium Heparin');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (10,'Blood','Mothers Blood');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (11,'Blood','Plasma');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (12,'Blood','Plasma (ACD)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (13,'Blood','Plasma (EDTA)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (14,'Blood','Plasma (LH)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (15,'Blood','Protein from TL');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (16,'Blood','Red Blood Cells');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (17,'Blood','Serum');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (18,'Blood','Transformed lymphoblasts (T)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (19,'Blood','Unprocessed');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (20,'Blood','Whole Blood');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (21,'Blood','Whole Blood (EDTA)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (22,'Blood','Whole Blood (LH)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (23,'Nucleic Acid','Buccal Swab');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (24,'Nucleic Acid','DNA');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (25,'Nucleic Acid','DNA from BC');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (26,'Nucleic Acid','DNA from TL');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (27,'Nucleic Acid','DNA from Tissue');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (28,'Nucleic Acid','Paxgene RNA');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (29,'Nucleic Acid','RNA');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (30,'Nucleic Acid','Saliva');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (31,'Protein from TL',null);
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (32,'Saliva','Buccal Swab');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (33,'Saliva','Buccal Swab (SB)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (34,'Saliva','Oragene (OS)');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (35,'Saliva','Throat Swab');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (36,'Saliva',null);
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (37,'Tissue','Anus');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (38,'Tissue','Appendix');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (39,'Tissue','Brain');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (40,'Tissue','Breast');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (41,'Tissue','Breast,Lt');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (42,'Tissue','Breast,Rt');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (43,'Tissue','Caecum');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (44,'Tissue','Colon');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (45,'Tissue','Colon, ascending');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (46,'Tissue','Colon, descending');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (47,'Tissue','Colon, hepatic flexure');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (48,'Tissue','Colon, nos');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (49,'Tissue','Colon, sigmoid');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (50,'Tissue','Colon, spenic flexure');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (51,'Tissue','Colon, splenic flexure');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (52,'Tissue','Colon, transverse');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (53,'Tissue','Descending Colon');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (54,'Tissue','Duodenum');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (55,'Tissue','Endometrium');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (56,'Tissue','Ileum');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (57,'Tissue','Left Tube');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (58,'Tissue','Liver');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (59,'Tissue','Lung');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (60,'Tissue','Lymph Node');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (61,'Tissue','Mesentary');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (62,'Tissue','Oesophagus');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (63,'Tissue','Omentum');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (64,'Tissue','Ovarian Cyst L');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (65,'Tissue','Ovarian L');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (66,'Tissue','Ovarian R');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (67,'Tissue','Ovary');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (68,'Tissue','Pancreas');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (69,'Tissue','Peritoneum, pelvic');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (70,'Tissue','Placenta');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (71,'Tissue','Rectal Peritoneal Mass');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (72,'Tissue','Recto-sigmoid');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (73,'Tissue','Rectum');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (74,'Tissue','Right Tube');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (75,'Tissue','Small Bowel');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (76,'Tissue','Spleen');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (77,'Tissue','Stomach');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (78,'Tissue','Tissue');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (79,'Tissue','Uterus');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (80,'Tissue','Uterus, endometrium');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (81,'Urine','Urine');
insert into `lims`.`bio_sampletype` (ID,SAMPLETYPE,SAMPLESUBTYPE) values (82,'Urine',null);