<?xml version="1.0"?>
<!-- CHelloWorld.ssl, part of the HelloWorld example channel -->

<?xml-stylesheet
    href="normal_netscape.xsl"
    title="normal"
    type="text/xsl"
    media="netscape"?>

<?xml-stylesheet
    href="normal_explorer.xsl"
    title="normal"
    type="text/xsl"
    media="explorer"?>

<?xml-stylesheet
    href="about.xsl"
    title="about"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_attachments.xsl"
    title="biospecimen_attachments"
    type="text/xsl"
    default="true"?>
    
 <?xml-stylesheet
    href="biospecimen_action_denied.xsl"
    title="biospecimen_action_denied"
    type="text/xsl"
    default="true"?>   
 <?xml-stylesheet
   href="BatchAllocation/batch_allocate.xsl"
   title="batch_allocate"
   type="text/xsl"
   default="true"?>
<?xml-stylesheet
    href="search_protein.xsl"
    title="search_protein"
    type="text/xsl"
    default="true"?>
<?xml-stylesheet
    href="search_antibody.xsl"
    title="search_antibody"
    type="text/xsl"
    default="true"?>
<?xml-stylesheet
    href="analysis.xsl"
    title="analysis"
    type="text/xsl"
    default="true"?>
<?xml-stylesheet
    href="add_analysis.xsl"
    title="add_analysis"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
href="VialCalculation/confirm_vial_calculation.xsl"
title="confirm_vial_calculation"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_add.xsl"
    title="biospecimen_add"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_confirmLocation.xsl"
    title="bp_clone_confirmLocation"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_report.xsl"
    title="bp_clone_report"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_displayLocations.xsl"
    title="bp_clone_displayLocations"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_displayReceipt.xsl"
    title="bp_clone_displayReceipt"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_getOptions.xsl"
    title="bp_clone_getOptions"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_foundAllocations.xsl"
    title="bp_clone_foundAllocations"
    type="text/xsl"
    default="true"?>


<?xml-stylesheet
    href="BatchProcessing/bp_clone_getIDs.xsl"
    title="bp_clone_getIDs"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_displayCellLocations.xsl"
    title="bp_clone_displayCellLocations"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_clone_generationReport.xsl"
    title="bp_clone_generationReport"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="BatchProcessing/bp_quantity_allocmode.xsl"
    title="bp_quantity_allocmode"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_search.xsl"
    title="biospecimen_search"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_results.xsl"
    title="biospecimen_results"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_view.xsl"
    title="biospecimen_view"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="security.xsl"
    title="securityerror"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_tree_view.xsl"
    title="biospecimen_tree_view"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="biospecimen_study.xsl"
    title="biospecimen_study"
    type="text/xsl"
    default="true"?>
    
    <?xml-stylesheet
    href="VialCalculation/get_allocation_option.xsl"
    title="get_allocation_option"
    type="text/xsl"
    default="true"?>


<?xml-stylesheet
   href="VialCalculation/vial_calculation.xsl"
    title="vial_calculation"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
   href="VialCalculation/available_tray_list.xsl"
    title="available_tray_list"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
   href="VialCalculation/create_sub_specimen.xsl"
    title="create_sub_specimen"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
   href="VialCalculation/vial_history.xsl"
   title="vial_history"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
   href="VialCalculation/confirm_allocation_option.xsl"
   title="confirm_allocation_option"
    type="text/xsl"
    default="true"?>
    


<?xml-stylesheet
    href="/neuragenix/genix/isearch/build_isearch.xsl"
    title="build_isearch"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="/neuragenix/genix/isearch/build_isearch_normal.xsl"
    title="build_isearch_normal"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="/neuragenix/genix/isearch/build_isearch_simplified.xsl"
    title="build_isearch_simplified"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="/neuragenix/genix/isearch/isearch_result.xsl"
    title="isearch_result"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchProcessing/bp_quantity_confirmAlloc.xsl"
    title="bp_quantity_confirmAlloc"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchProcessing/bp_quantity_finishAlloc.xsl"
    title="bp_quantity_finishAlloc"
    type="text/xsl"
    default="true"?>


<?xml-stylesheet
    href="./batchactions/batch_get_options.xsl"
    title="batch_get_options"
    type="text/xsl"
    default="true"?>


<?xml-stylesheet
    href="./batchactions/allocate_inventory.xsl"
    title="allocate_inventory"
    type="text/xsl"
    default="true"?>
    
    
<?xml-stylesheet
    href="./batchactions/ID_generation.xsl"
    title="generate_id"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./batchactions/report.xsl"
    title="report"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchSFResultsGeneration/creation_type.xsl"
    title="creation_type"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchSFResultsGeneration/specimen_selection.xsl"
    title="specimen_selection"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchSFResultsGeneration/header.xsl"
    title="header"
    type="text/xsl"
    default="true"?>


<?xml-stylesheet
    href="./BatchSFResultsGeneration/generation_report.xsl"
    title="generation_report"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchSFResultsGeneration/select_sf_fields.xsl"
    title="select_sf_fields"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchSFResultsGeneration/clone_fields_data.xsl"
    title="clone_fields_data"
    type="text/xsl"
    default="true"?>

<?xml-stylesheet
    href="./BatchSFResultsGeneration/standalone_fields_data.xsl"
    title="standalone_fields_data"
    type="text/xsl"
    default="true"?>

<document>
</document>
 
