# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "vagrant-ark"

	config.vm.network "private_network", ip: "192.168.33.10"

	config.vm.synced_folder "~/.m2/repository", "/home/vagrant/.m2/repository"
	config.vm.synced_folder "~/.m2/repository", "/root/.m2/repository"

	config.vm.provider "virtualbox" do |vb|
		vb.cpus = 4
		vb.memory = "2048"
	end
	
	config.vm.provision :shell, inline: "rm -rf /home/vagrant/ark"
	config.vm.provision "file", source: "../", destination: "/home/vagrant/ark"

	config.vm.provision :puppet do |puppet|
		puppet.manifests_path = "puppet/manifests"
		puppet.manifest_file = "ark.pp"
		puppet.module_path = "puppet/modules"
	end
end
