ALTER TABLE `admin`.`bilable_item` DROP COLUMN `GST_ALLOW` , DROP COLUMN `GST` ;

ALTER TABLE `admin`.`work_request` ADD COLUMN `GST` DOUBLE NULL  AFTER `STUDY_ID` , ADD COLUMN `GST_ALLOW` TINYINT NULL  AFTER `GST` ;


