CREATE  TABLE `study`.`LINK_SUBJECT_PEDIGREE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `FAMILY_ID` INT(11) NOT NULL ,
  `LINK_SUBJECT_STUDY_ID` INT(11) NULL ,
  `RELATIVE_ID` INT(11) NULL ,
  `RELATIONSHIP_ID` INT(11) NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

