/*
-- Query: select * from study.study where name  = 'PMH'
LIMIT 0, 50000

-- Date: 2014-10-28 15:00
*/
INSERT INTO `study` (`ID`,`NAME`,`DESCRIPTION`,
`DATE_OF_APPLICATION`,`ESTIMATED_YEAR_OF_COMPLETION`,`CHIEF_INVESTIGATOR`,`CO_INVESTIGATOR`,
`AUTO_GENERATE_SUBJECTUID`,`SUBJECTUID_START`,`STUDY_STATUS_ID`,`SUBJECTUID_PREFIX`,`CONTACT_PERSON`,
`CONTACT_PERSON_PHONE`,`LDAP_GROUP_NAME`,`AUTO_CONSENT`,`SUB_STUDY_BIOSPECIMEN_PREFIX`,`STUDY_LOGO`,`FILENAME`,
`SUBJECTUID_TOKEN_ID`,`SUBJECTUID_PADCHAR_ID`,`SUBJECT_KEY_PREFIX`,`SUBJECT_KEY_START`,`PARENT_ID`,`AUTO_GENERATE_BIOSPECIMENUID`,
`AUTO_GENERATE_BIOCOLLECTIONUID`) 
VALUES (590,'PMH','PMH study - brought over from PMH Biogenix instance.  Contains T1D, T2D, Obesity consented patients.',
NULL,NULL,'Tim Jones',NULL,1,3680,1,NULL,'Tim Jones & Tegan McNab',NULL,NULL,1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,0,1);

SELECT min(id) FROM lims.unit WHERE name = 'mL'

select * from lims.biospecimen