SELECT * FROM lims.bio_sampletype ;




update pmhdiaendo.ix_biospecimen
set samplesubtype = 'DNA',
sampletype = 'Nucleic Acid'
where sampletype='DNA';

update pmhdiaendo.ix_biospecimen
set samplesubtype = 'Whole Blood',
sampletype = 'Blood'
where sampletype='Whole Blood' and samplesubtype='Blood';

update pmhdiaendo.ix_biospecimen
set samplesubtype ='Whole Blood (EDTA)',
sampletype =  'Blood'
where sampletype like'%Blood (EDTA)';

update pmhdiaendo.ix_biospecimen
set samplesubtype = 'Serum',
sampletype = 'Blood'
where sampletype='Serum'
or samplesubtype='Serum';

select distinct sampletype from pmhdiaendo.ix_biospecimen

select distinct samplesubtype from pmhdiaendo.ix_biospecimen
'DNA'				'24','Nucleic Acid / DNA','Nucleic Acid','DNA','29'
'Serum'				'17','Blood / Serum','Blood','Serum','21'
'Blood (EDTA)'		'21','Blood / Whole Blood (EDTA)','Blood','Whole Blood (EDTA)','24'
'Whole Blood'       '20','Blood / Whole Blood','Blood','Whole Blood','1'

'1','Blood / Blood','Blood','Blood','4'
'2','Blood / Buffy Coat','Blood','Buffy Coat','5'
'3','Blood / Buffy Coat (ACD)','Blood','Buffy Coat (ACD)','6'
'4','Blood / Buffy Coat (EDTA)','Blood','Buffy Coat (EDTA)','7'
'5','Blood / Buffy Coat (LH)','Blood','Buffy Coat (LH)','8'
'6','Blood / Cord blood','Blood','Cord blood','9'
'7','Blood / EDTA Blood','Blood','EDTA Blood','10'
'8','Blood / Frozen Lymphocytes (F)','Blood','Frozen Lymphocytes (F)','11'
'9','Blood / Lithium Heparin','Blood','Lithium Heparin','12'
'10','Blood / Mothers Blood','Blood','Mothers Blood','13'
'11','Blood / Plasma','Blood','Plasma','15'
'12','Blood / Plasma (ACD)','Blood','Plasma (ACD)','16'
'13','Blood / Plasma (EDTA)','Blood','Plasma (EDTA)','17'
'14','Blood / Plasma (LH)','Blood','Plasma (LH)','18'
'15','Blood / Protein from TL','Blood','Protein from TL','19'
'16','Blood / Red Blood Cells','Blood','Red Blood Cells','20'
'17','Blood / Serum','Blood','Serum','21'
'18','Blood / Transformed lymphoblasts (T)','Blood','Transformed lymphoblasts (T)','22'
'19','Blood / Unprocessed','Blood','Unprocessed','23'
'20','Blood / Whole Blood','Blood','Whole Blood','1'
'21','Blood / Whole Blood (EDTA)','Blood','Whole Blood (EDTA)','24'
'22','Blood / Whole Blood (LH)','Blood','Whole Blood (LH)','25'
'23','Nucleic Acid / Buccal Swab','Nucleic Acid','Buccal Swab','28'
'24','Nucleic Acid / DNA','Nucleic Acid','DNA','29'
'25','Nucleic Acid / DNA from BC','Nucleic Acid','DNA from BC','30'
'26','Nucleic Acid / DNA from TL','Nucleic Acid','DNA from TL','34'
'27','Nucleic Acid / DNA from Tissue','Nucleic Acid','DNA from Tissue','33'
'28','Nucleic Acid / Paxgene RNA','Nucleic Acid','Paxgene RNA','35'
'29','Nucleic Acid / RNA','Nucleic Acid','RNA','36'
'30','Nucleic Acid / Saliva','Nucleic Acid','Saliva','37'
'31','Protein from TL','Protein from TL','wasNull','39'
'32','Saliva / Buccal Swab','Saliva','Buccal Swab','41'
'33','Saliva / Buccal Swab (SB)','Saliva','Buccal Swab (SB)','42'
'34','Saliva / Oragene (OS)','Saliva','Oragene (OS)','43'
'35','Saliva / Throat Swab','Saliva','Throat Swab','44'
'36','Saliva','Saliva','wasNull','40'
'37','Tissue / Anus','Tissue','Anus','48'
'38','Tissue / Appendix','Tissue','Appendix','49'
'39','Tissue / Brain','Tissue','Brain','52'
'40','Tissue / Breast','Tissue','Breast','53'
'41','Tissue / Breast,Lt','Tissue','Breast,Lt','54'
'42','Tissue / Breast,Rt','Tissue','Breast,Rt','55'
'43','Tissue / Caecum','Tissue','Caecum','56'
'44','Tissue / Colon','Tissue','Colon','57'
'45','Tissue / Colon, ascending','Tissue','Colon, ascending','58'
'46','Tissue / Colon, descending','Tissue','Colon, descending','59'
'47','Tissue / Colon, hepatic flexure','Tissue','Colon, hepatic flexure','60'
'48','Tissue / Colon, nos','Tissue','Colon, nos','61'
'49','Tissue / Colon, sigmoid','Tissue','Colon, sigmoid','63'
'50','Tissue / Colon, spenic flexure','Tissue','Colon, spenic flexure','64'
'51','Tissue / Colon, splenic flexure','Tissue','Colon, splenic flexure','65'
'52','Tissue / Colon, transverse','Tissue','Colon, transverse','66'
'53','Tissue / Descending Colon','Tissue','Descending Colon','67'
'54','Tissue / Duodenum','Tissue','Duodenum','68'
'55','Tissue / Endometrium','Tissue','Endometrium','69'
'56','Tissue / Ileum','Tissue','Ileum','72'
'57','Tissue / Left Tube','Tissue','Left Tube','75'
'58','Tissue / Liver','Tissue','Liver','77'
'59','Tissue / Lung','Tissue','Lung','78'
'60','Tissue / Lymph Node','Tissue','Lymph Node','79'
'61','Tissue / Mesentary','Tissue','Mesentary','80'
'62','Tissue / Oesophagus','Tissue','Oesophagus','82'
'63','Tissue / Omentum','Tissue','Omentum','83'
'64','Tissue / Ovarian Cyst L','Tissue','Ovarian Cyst L','87'
'65','Tissue / Ovarian L','Tissue','Ovarian L','88'
'66','Tissue / Ovarian R','Tissue','Ovarian R','89'
'67','Tissue / Ovary','Tissue','Ovary','90'
'68','Tissue / Pancreas','Tissue','Pancreas','93'
'69','Tissue / Peritoneum, pelvic','Tissue','Peritoneum, pelvic','95'
'70','Tissue / Placenta','Tissue','Placenta','96'
'71','Tissue / Rectal Peritoneal Mass','Tissue','Rectal Peritoneal Mass','98'
'72','Tissue / Recto-sigmoid','Tissue','Recto-sigmoid','99'
'73','Tissue / Rectum','Tissue','Rectum','100'
'74','Tissue / Right Tube','Tissue','Right Tube','102'
'75','Tissue / Small Bowel','Tissue','Small Bowel','105'
'76','Tissue / Spleen','Tissue','Spleen','107'
'77','Tissue / Stomach','Tissue','Stomach','108'
'78','Tissue / Tissue','Tissue','Tissue','109'
'79','Tissue / Uterus','Tissue','Uterus','110'
'80','Tissue / Uterus, endometrium','Tissue','Uterus, endometrium','111'
'81','Urine / Urine','Urine','Urine','114'
'82','Urine','Urine','wasNull','113'
'83','Blood / Peripheral Blood Lysed','Blood','Peripheral Blood Lysed','2'
'84','Blood / Peripheral Blood DNA','Blood','Peripheral Blood DNA','3'
'85','DNA / DNA','DNA','DNA','26'
'86','Nucleic Acid / DNA from SF Tissue','Nucleic Acid','DNA from SF Tissue','32'
'87','Tissue / Small bowel, nos','Tissue','Small bowel, nos','106'
'88','Tissue / Peritoneum','Tissue','Peritoneum','94'
'89','Tissue / Ovary, left','Tissue','Ovary, left','91'
'90','Tissue / Fallopian tube, left','Tissue','Fallopian tube, left','70'
'91','Tissue / Fallopian tube, right','Tissue','Fallopian tube, right','71'
'92','Tissue / Whole Blood','Tissue','Whole Blood','112'
'93','Tissue / Bone','Tissue','Bone','51'
'94','Tissue / Ovary, right','Tissue','Ovary, right','92'
'95','Tissue / Colon, rectosigmoid','Tissue','Colon, rectosigmoid','62'
'96','Tears / Tears (left eye)','Tears','Tears (left eye)','45'
'97','Tears / Tears (right eye)','Tears','Tears (right eye)','46'
'98','Tissue / Lens (L)','Tissue','Lens (L)','76'
'99','Tissue / Neurosensory Retina (R)','Tissue','Neurosensory Retina (R)','81'
'100','Tissue / RPE/Choroid (C)','Tissue','RPE/Choroid (C)','103'
'101','Tissue / Optic Nerve (O) ','Tissue','Optic Nerve (O) ','84'
'102','Blood / PBMC-EDTA','Blood','PBMC-EDTA','14'
'103','Tissue / Adrenal Gland','Tissue','Adrenal Gland','47'
'105','Tissue / Orbital Fat (F)','Tissue','Orbital Fat (F)','85'
'106','Tissue / Iris (I)','Tissue','Iris (I)','73'
'107','Tissue / Sacrum','Tissue','Sacrum','104'
'108','Tissue / Bladder','Tissue','Bladder','50'
'109','Tissue / Prostate','Tissue','Prostate','97'
'110','Nucleic Acid / Whole Blood ','Nucleic Acid','Whole Blood ','38'
'111','Tissue / Right Eye','Tissue','Right Eye','101'
'112','Tissue / Other','Tissue','Other','86'
'113','Tissue / Left Eye','Tissue','Left Eye','74'
'114','Nucleic Acid / DNA from FFPE ','Nucleic Acid','DNA from FFPE ','31'
'117','Nucleic Acid / Adrenal Gland','Nucleic Acid','Adrenal Gland','27'

select distinct sampletype from lims.bio_sampletype 
'Blood'
'Nucleic Acid'
'Protein from TL'
'Saliva'
'Tissue'
'Urine'
'DNA'
'Tears'

