

SET @STUDYKEY = 17;

select * from lims.biospecimen where biospecimen_uid = '0199SCZ00150F1';

SELECT 
    PAT.SUBJECTID as 'SUBJECTUID',
    BIO.BIOSPECIMENID AS 'BIOSPECIMENUID',
   DATE_FORMAT(BIO.SAMPLEDATE, '%d/%m/%Y') AS 'Sample Date',
 TIME_FORMAT(BIO.SAMPLE_TIME, '%h:%m:%s') AS 'Sample Time',
   DATE_FORMAT(BIO.DATEEXTRACTED,'%d/%m/%Y')  AS 'Processed Date',
  TIME_FORMAT(BIO.EXTRACTED_TIME, '%h:%m:%s') AS 'Processed Time',
  --  BIO.COLLABORATOR AS 'COLLABORATOR',
    (ifnull(BIO.QTY_REMOVED, 0) + ifnull(BIO.QTY_COLLECTED, 0) ) AS 'Quantity',
   --  BIO.QTY_REMOVED  AS 'QuantityRem',
   -- BIO.QTY_COLLECTED  AS 'QuantityCol',
    BIO.DNACONC AS 'Concentration',
    BIO.PURITY AS 'Purity',
    BIO.GRADE AS 'Grade',
    BIO.COMMENTS AS 'Comments',
    UPPER(ifnull(BIO.UNITS, 'unit')) AS 'UNIT',  -- then case as upper in both reports
    IFNULL(BIO.TREATMENT, 'Unknown') AS 'Treatment Type',
    BIO.QUALITY AS 'Quality',
    BIO.ANTICOAG AS 'Anticoagulant',
    BIO.STATUS AS 'Status',
    BIO.PROTOCOL AS 'Protocol',
  --  BIO.QTY_COLLECTED AS 'QTY_COLLECTED',
    BIO.ENCOUNTER AS 'BiocollectionUid',
    BIO.STORED_IN AS 'Stored In'
 --  BIO.EXTRACTED_TIME  AS 'EXTRACTED_TIME_real',
 --   BIO.GESTAT AS 'GESTAT',   never used at all
--  !this is bad we dont extract this...in there interim could manually run something to compare...be very thorough!!!!!!!    BIO.PARENTID AS 'PARENTID'
FROM
    ZEUS.SUBJECT PAT,
    WAGERLAB.IX_BIOSPECIMEN BIO
WHERE
    PAT.STUDYKEY = @STUDYKEY
        AND PAT.SUBJECTKEY = BIO.PATIENTKEY
        AND BIO.DELETED = 0
        AND BIO.STUDYKEY = @STUDYKEY
ORDER BY (PAT.SUBJECTID + 0) , BIO.BIOSPECIMENID;

/* doctored to match ark formating friom this lims report
SELECT PAT.SUBJECTID, BIO.ANTICOAG AS "ANTICOAG", BIO.BIOSPECIMENID AS "BIOSPECIMENID", BIO.COLLABORATOR AS "COLLABORATOR", BIO.COMMENTS AS "COMMENTS", TO_CHAR(BIO.DATEEXTRACTED, 'DD/MM/YYYY') AS "DATEEXTRACTED", BIO.DNACONC AS "DNACONC", BIO.ENCOUNTER AS "ENCOUNTER", TO_CHAR(BIO.EXTRACTED_TIME, 'HH:mm:ss') AS "EXTRACTED_TIME", BIO.GRADE AS "GRADE", BIO.PROTOCOL AS "PROTOCOL", BIO.PURITY AS "PURITY", BIO.QTY_COLLECTED AS "QTY_COLLECTED", BIO.QTY_REMOVED AS "QTY_REMOVED", BIO.QUALITY AS "QUALITY", BIO.QUANTITY AS "QUANTITY", TO_CHAR(BIO.SAMPLEDATE, 'DD/MM/YYYY') AS "SAMPLEDATE", TO_CHAR(BIO.SAMPLE_TIME, 'HH:mm:ss') AS "SAMPLE_TIME", BIO.STATUS AS "STATUS", BIO.STORED_IN AS "STORED_IN", BIO.TREATMENT AS "TREATMENT", BIO.UNITS AS "UNITS", BIO.GESTAT AS "GESTAT", BIO.PARENTID AS "PARENTID"
FROM ZEUS.SUBJECT PAT , WAGERLAB.IX_BIOSPECIMEN BIO 
WHERE PAT.STUDYKEY = 17
AND PAT.SUBJECTKEY = BIO.PATIENTKEY
AND BIO.DELETED = 0
AND BIO.STUDYKEY = 17
ORDER BY PAT.SUBJECTID, BIO.BIOSPECIMENID
*/