ALTER DATABASE study
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE study
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE admin
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE admin
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE audit
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE audit
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE lims
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE lims
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE pheno
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE pheno
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE reporting
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE reporting
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE calendar
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE calendar
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE config
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE config
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE disease
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE disease
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE spark
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE spark
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE geno
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE geno
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE sys
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE sys
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;
