ALTER TABLE `study`.`custom_field` 
ADD COLUMN `CATEGORY_ID` INT(11) NULL DEFAULT NULL AFTER `UNIT_TYPE_IN_TEXT`;

ALTER TABLE `study`.`custom_field_display` 
DROP COLUMN `CATEGORY_ID`;

ALTER TABLE `study`.`custom_field` 
ADD INDEX `FK_CUSTOM_FIELD_CATEGORY_idx` (`CATEGORY_ID` ASC);
ALTER TABLE `study`.`custom_field` 
ADD CONSTRAINT `FK_CUSTOM_FIELD_CATEGORY`
  FOREIGN KEY (`CATEGORY_ID`)
  REFERENCES `study`.`category` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
