USE reporting;

ALTER TABLE `reporting`.`report_template` 
  ADD CONSTRAINT `FK_REPORTTEMPLATE_ARKFUNCTION`
  FOREIGN KEY (`FUNCTION_ID` )
  REFERENCES `study`.`ark_function` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_REPORTTEMPLATE_ARKFUNCTION` (`FUNCTION_ID` ASC) ;
