use study;

DROP TABLE IF EXISTS `link_study_arkmodule`;
CREATE  TABLE `study`.`link_study_arkmodule` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `STUDY_ID` INT NOT NULL ,
  `ARK_MODULE_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_LINK_STUDY_ARKMODULE_STUDY_ID` (`STUDY_ID` ASC) ,
  INDEX `FK_LINK_STUDY_ARKMODULE_ARK_MODULE_ID` (`ARK_MODULE_ID` ASC) ,
  CONSTRAINT `FK_LINK_STUDY_ARKMODULE_STUDY_ID`
    FOREIGN KEY (`STUDY_ID` )
    REFERENCES `study`.`study` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_LINK_STUDY_ARKMODULE_ARK_MODULE_ID`
    FOREIGN KEY (`ARK_MODULE_ID` )
    REFERENCES `study`.`ark_module` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


