use study;
CREATE  TABLE `study`.`ark_user` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `STUDY_ID` INT NULL ,
  `LDAP_USER_NAME` VARCHAR(500) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_STUDY_ID` (`STUDY_ID` ASC) ,
  CONSTRAINT `FK_STUDY_ID`
    FOREIGN KEY (`STUDY_ID` )
    REFERENCES `study`.`study` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE  TABLE `study`.`ark_module` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` VARCHAR(1000) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;

CREATE  TABLE `study`.`ark_role` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` VARCHAR(1000) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;

CREATE  TABLE `study`.`ark_permission` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) )
ENGINE = InnoDB;


CREATE  TABLE `study`.`ark_role_permission` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `ARK_ROLE_ID` INT NOT NULL ,
  `ARK_PERMISSION_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_ROLE_ID` (`ARK_ROLE_ID` ASC) ,
  INDEX `FK_PERMISSION_ID` (`ARK_PERMISSION_ID` ASC) ,
  CONSTRAINT `FK_ROLE_ID`
    FOREIGN KEY (`ARK_ROLE_ID` )
    REFERENCES `study`.`ark_role` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_PERMISSION_ID`
    FOREIGN KEY (`ARK_PERMISSION_ID` )
    REFERENCES `study`.`ark_permission` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE  TABLE `study`.`ark_user_role` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `ARK_USER_ID` INT NOT NULL ,
  `ARK_ROLE_ID` INT NOT NULL ,
  `ARK_MODULE_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_ARK_USER_ID` (`ARK_USER_ID` ASC) ,
  INDEX `FK_ARK_ROLE_ID` (`ARK_ROLE_ID` ASC) ,
  INDEX `FK_ARK_MODULE_ID` (`ARK_MODULE_ID` ASC) ,
  CONSTRAINT `FK_ARK_USER_ID`
    FOREIGN KEY (`ARK_USER_ID` )
    REFERENCES `study`.`ark_user` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ARK_ROLE_ID`
    FOREIGN KEY (`ARK_ROLE_ID` )
    REFERENCES `study`.`ark_role` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ARK_MODULE_ID`
    FOREIGN KEY (`ARK_MODULE_ID` )
    REFERENCES `study`.`ark_module` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

