use study;
drop table `study`.`link_correspondence_person` ;

ALTER TABLE `study`.`correspondence_attachment` DROP COLUMN `SIZE` , ADD COLUMN `CHECKSUM` VARCHAR(50) NOT NULL  AFTER `PAYLOAD` , ADD COLUMN `USER_ID` VARCHAR(100) NOT NULL  AFTER `CHECKSUM` , ADD COLUMN `COMMENTS` TEXT NULL  AFTER `USER_ID` , CHANGE COLUMN `FILENAME` `FILENAME` TEXT NOT NULL  , CHANGE COLUMN `CONTENTS` `PAYLOAD` LONGBLOB NOT NULL  ;

ALTER TABLE `study`.`correspondence_audit_attachment` ADD COLUMN `USER_ID` VARCHAR(100) NOT NULL  AFTER `CHECKSUM` , ADD COLUMN `COMMENTS` TEXT NULL  AFTER `USER_ID` , CHANGE COLUMN `FILENAME` `FILENAME` TEXT NOT NULL  , CHANGE COLUMN `SIZE` `PAYLOAD` LONGBLOB NOT NULL  , CHANGE COLUMN `CONTENTS` `CHECKSUM` VARCHAR(50) NOT NULL  ;

