use study;
DROP TABLE IF EXISTS `ark_module_role`;
CREATE  TABLE `study`.`ark_module_role` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `ARK_MODULE_ID` INT NOT NULL ,
  `ARK_ROLE_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_ARK_MODULE_ID` (`ARK_MODULE_ID` ASC) ,
  INDEX `FK_ARK_ROLE_ID` (`ARK_ROLE_ID` ASC) ,
  CONSTRAINT `FK_ARK_MODULE_ID`
    FOREIGN KEY (`ARK_MODULE_ID` )
    REFERENCES `study`.`ark_module` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ARK_ROLE_ID`
    FOREIGN KEY (`ARK_ROLE_ID` )
    REFERENCES `study`.`ark_role` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
