USE study;
ALTER TABLE `study`.`delimiter_type` CHANGE COLUMN `DELIMITER_CHARACTER` `DELIMITER_CHARACTER` VARCHAR(1) NOT NULL DEFAULT ',';
UPDATE `study`.`delimiter_type` SET `NAME`='AT SYMBOL', `DESCRIPTION`='At characer', `DELIMITER_CHARACTER`='@' WHERE `ID`='5';