USE audit;
DELETE FROM consent_history;
DELETE FROM lss_consent_history;

INSERT INTO `audit`.`consent_history`
(`LINK_SUBJECT_STUDY_ID`,
`STUDY_COMP_ID`, 
`STUDY_COMP_STATUS_ID`,
`CONSENT_STATUS_ID`,
`CONSENT_TYPE_ID`,
`CONSENT_DATE`,
`CONSENTED_BY`,
`COMMENTS`,
`REQUESTED_DATE`,
`RECEIVED_DATE`,
`COMPLETED_DATE`,
`CONSENT_DOWNLOADED_ID`)
SELECT 
`LINK_SUBJECT_STUDY_ID`,
`STUDY_COMP_ID`,
`STUDY_COMP_STATUS_ID`,
`CONSENT_STATUS_ID`,
`CONSENT_TYPE_ID`,
`CONSENT_DATE`,
`CONSENTED_BY`,
`COMMENTS`,
`REQUESTED_DATE`,
`RECEIVED_DATE`,
`COMPLETED_DATE`,
`CONSENT_DOWNLOADED_ID`
FROM study.consent
WHERE `CONSENT_STATUS_ID` IS NOT NULL;

INSERT INTO `audit`.`lss_consent_history`
(`LINK_SUBJECT_STUDY_ID`,
`CONSENT_TO_ACTIVE_CONTACT_ID`,
`CONSENT_TO_PASSIVE_DATA_GATHERING_ID`,
`CONSENT_TO_USE_DATA_ID`,
`CONSENT_STATUS_ID`,
`CONSENT_TYPE_ID`,
`CONSENT_DATE`,
`CONSENT_DOWNLOADED`)
SELECT 
`ID`,
`CONSENT_TO_ACTIVE_CONTACT_ID`,
`CONSENT_TO_PASSIVE_DATA_GATHERING_ID`,
`CONSENT_TO_USE_DATA_ID`,
`CONSENT_STATUS_ID`,
`CONSENT_TYPE_ID`,
`CONSENT_DATE`,
`CONSENT_DOWNLOADED`
FROM study.link_subject_study
WHERE `CONSENT_STATUS_ID` IS NOT NULL;