USE study;

CREATE TABLE `consent_option` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 ROW_FORMAT=COMPACT;

INSERT INTO `consent_option` (ID, NAME) VALUES (1, 'Yes');
INSERT INTO `consent_option` (ID, NAME) VALUES (2, 'No');
INSERT INTO `consent_option` (ID, NAME) VALUES (3, 'Pending');
INSERT INTO `consent_option` (ID, NAME) VALUES (4, 'Unavailable');

ALTER TABLE `link_subject_study`
	DROP FOREIGN KEY `fk_link_subject_study_1`,
	DROP FOREIGN KEY `FK_LINK_SUBJECT_STUDY_CNS_PASS_DATA`,
	DROP FOREIGN KEY `FK_LINK_SUBJECT_STUDY_CNS_USE_DATA`,
	DROP FOREIGN KEY `FK_LINK_SUBJECT_STUDY_CNS_ACT_CTNT`;

ALTER TABLE `link_subject_study`
	ADD CONSTRAINT `FK_CONSENT_DOWNLOADED_YES_NO` FOREIGN KEY (`CONSENT_DOWNLOADED` ) REFERENCES `study`.`yes_no` (`ID` ),
	ADD CONSTRAINT `FK_LINK_SUBJECT_STUDY_CNS_PASS_DATA` FOREIGN KEY (`CONSENT_TO_PASSIVE_DATA_GATHERING_ID`) REFERENCES `study`.`consent_option` (`ID`),
	ADD CONSTRAINT `FK_LINK_SUBJECT_STUDY_CNS_USE_DATA` FOREIGN KEY (`CONSENT_TO_USE_DATA_ID`) REFERENCES `study`.`consent_option` (`ID`),
	ADD CONSTRAINT `FK_LINK_SUBJECT_STUDY_CNS_ACT_CTNT` FOREIGN KEY (`CONSENT_TO_ACTIVE_CONTACT_ID`) REFERENCES `study`.`consent_option` (`ID`);