<?xml version="1.0"?>


<?xml-stylesheet
    href="start_page.xsl"
    type="text/xsl"
    title="start"?>

<?xml-stylesheet
    href="verify_page.xsl"
    type="text/xsl"
    title="verify"?>

<?xml-stylesheet
    href="confirm_page.xsl"
    type="text/xsl"
    title="confirm"?>


<?xml-stylesheet
    href="success_page.xsl"
    type="text/xsl"
    title="success"?>
    
    <document>
    </document>
    
    
