package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;

/**
 * IxInvCell generated by hbm2java
 */
public class Cell implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1912438970156771898L;
	// Fields    

	
	private BigDecimal cellkey;
	private String timestamp;
	private BigDecimal deleted;
	private BigDecimal rowno;
	private BigDecimal colno;
	private BigDecimal biospecimenkey;
	private BigDecimal traykey;
	private BigDecimal patientkey;
	private String status;

	// Constructors

	/** default constructor */
	public Cell() {
	}

	/** minimal constructor */
	public Cell(BigDecimal cellkey, BigDecimal traykey) {
		this.cellkey = cellkey;
		this.traykey = traykey;
	}

	/** full constructor */
	public Cell(BigDecimal cellkey, BigDecimal deleted, BigDecimal rowno,
			BigDecimal colno, BigDecimal biospecimenkey, BigDecimal traykey,
			BigDecimal patientkey, String status) {
		this.cellkey = cellkey;
		this.deleted = deleted;
		this.rowno = rowno;
		this.colno = colno;
		this.biospecimenkey = biospecimenkey;
		this.traykey = traykey;
		this.patientkey = patientkey;
		this.status = status;
	}

	// Property accessors
	public BigDecimal getCellkey() {
		return this.cellkey;
	}

	public void setCellkey(BigDecimal cellkey) {
		this.cellkey = cellkey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getDeleted() {
		return this.deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}

	public BigDecimal getRowno() {
		return this.rowno;
	}

	public void setRowno(BigDecimal rowno) {
		this.rowno = rowno;
	}

	public BigDecimal getColno() {
		return this.colno;
	}

	public void setColno(BigDecimal colno) {
		this.colno = colno;
	}

	public BigDecimal getBiospecimenkey() {
		return this.biospecimenkey;
	}

	public void setBiospecimenkey(BigDecimal biospecimenkey) {
		this.biospecimenkey = biospecimenkey;
	}

	public BigDecimal getTraykey() {
		return this.traykey;
	}

	public void setTraykey(BigDecimal traykey) {
		this.traykey = traykey;
	}

	public BigDecimal getPatientkey() {
		return this.patientkey;
	}

	public void setPatientkey(BigDecimal patientkey) {
		this.patientkey = patientkey;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
