package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;

/**
 * IxStudy generated by hbm2java
 */
public class Study implements java.io.Serializable {

	// Fields    

	private BigDecimal studykey;
	private String timestamp;
	private BigDecimal deleted;
	private Date studyStart;
	private String studycode;
	private String studyName;
	private String studyOwner;
	private String studyDescription;
	private BigDecimal actualPatientNo;
	private Date studyEnd;
	private BigDecimal targetPatientNo;

	// Constructors

	/** default constructor */
	public Study() {
	}

	/** minimal constructor */
	public Study(BigDecimal studykey, String studyName, String studyOwner) {
		this.studykey = studykey;
		this.studyName = studyName;
		this.studyOwner = studyOwner;
	}

	/** full constructor */
	public Study(BigDecimal studykey, BigDecimal deleted, Date studyStart,
			String studycode, String studyName, String studyOwner,
			String studyDescription, BigDecimal actualPatientNo, Date studyEnd,
			BigDecimal targetPatientNo) {
		this.studykey = studykey;
		this.deleted = deleted;
		this.studyStart = studyStart;
		this.studycode = studycode;
		this.studyName = studyName;
		this.studyOwner = studyOwner;
		this.studyDescription = studyDescription;
		this.actualPatientNo = actualPatientNo;
		this.studyEnd = studyEnd;
		this.targetPatientNo = targetPatientNo;
	}

	// Property accessors
	public BigDecimal getStudykey() {
		return this.studykey;
	}

	public void setStudykey(BigDecimal studykey) {
		this.studykey = studykey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getDeleted() {
		return this.deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}

	public Date getStudyStart() {
		return this.studyStart;
	}

	public void setStudyStart(Date studyStart) {
		this.studyStart = studyStart;
	}

	public String getStudycode() {
		return this.studycode;
	}

	public void setStudycode(String studycode) {
		this.studycode = studycode;
	}

	public String getStudyName() {
		return this.studyName;
	}

	public void setStudyName(String studyName) {
		this.studyName = studyName;
	}

	public String getStudyOwner() {
		return this.studyOwner;
	}

	public void setStudyOwner(String studyOwner) {
		this.studyOwner = studyOwner;
	}

	public String getStudyDescription() {
		return this.studyDescription;
	}

	public void setStudyDescription(String studyDescription) {
		this.studyDescription = studyDescription;
	}

	public BigDecimal getActualPatientNo() {
		return this.actualPatientNo;
	}

	public void setActualPatientNo(BigDecimal actualPatientNo) {
		this.actualPatientNo = actualPatientNo;
	}

	public Date getStudyEnd() {
		return this.studyEnd;
	}

	public void setStudyEnd(Date studyEnd) {
		this.studyEnd = studyEnd;
	}

	public BigDecimal getTargetPatientNo() {
		return this.targetPatientNo;
	}

	public void setTargetPatientNo(BigDecimal targetPatientNo) {
		this.targetPatientNo = targetPatientNo;
	}

}
