package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5

import java.math.BigDecimal;
import java.util.Date;

/**
 * Tank generated by hbm2java
 */
public class Tank implements java.io.Serializable {

	// Fields    

	private BigDecimal tankkey;
	private String timestamp;
	private BigDecimal deleted;
	private String location;
	private String status;
	private BigDecimal sitekey;
	private BigDecimal capacity;
	private String lastservicenote;
	private String name;
	private BigDecimal available;
	private Date decommissiondate;
	private Date commissiondate;
	private Date lastservicedate;
	private String description;

	// Constructors

	/** default constructor */
	public Tank() {
	}

	/** minimal constructor */
	public Tank(BigDecimal tankkey, BigDecimal sitekey, String name) {
		this.tankkey = tankkey;
		this.sitekey = sitekey;
		this.name = name;
	}

	/** full constructor */
	public Tank(BigDecimal tankkey, BigDecimal deleted, String location,
			String status, BigDecimal sitekey, BigDecimal capacity,
			String lastservicenote, String name, BigDecimal available,
			Date decommissiondate, Date commissiondate, Date lastservicedate,
			String description) {
		this.tankkey = tankkey;
		this.deleted = deleted;
		this.location = location;
		this.status = status;
		this.sitekey = sitekey;
		this.capacity = capacity;
		this.lastservicenote = lastservicenote;
		this.name = name;
		this.available = available;
		this.decommissiondate = decommissiondate;
		this.commissiondate = commissiondate;
		this.lastservicedate = lastservicedate;
		this.description = description;
	}

	// Property accessors
	public BigDecimal getTankkey() {
		return this.tankkey;
	}

	public void setTankkey(BigDecimal tankkey) {
		this.tankkey = tankkey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public BigDecimal getDeleted() {
		return this.deleted;
	}

	public void setDeleted(BigDecimal deleted) {
		this.deleted = deleted;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public BigDecimal getSitekey() {
		return this.sitekey;
	}

	public void setSitekey(BigDecimal sitekey) {
		this.sitekey = sitekey;
	}

	public BigDecimal getCapacity() {
		return this.capacity;
	}

	public void setCapacity(BigDecimal capacity) {
		this.capacity = capacity;
	}

	public String getLastservicenote() {
		return this.lastservicenote;
	}

	public void setLastservicenote(String lastservicenote) {
		this.lastservicenote = lastservicenote;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public BigDecimal getAvailable() {
		return this.available;
	}

	public void setAvailable(BigDecimal available) {
		this.available = available;
	}

	public Date getDecommissiondate() {
		return this.decommissiondate;
	}

	public void setDecommissiondate(Date decommissiondate) {
		this.decommissiondate = decommissiondate;
	}

	public Date getCommissiondate() {
		return this.commissiondate;
	}

	public void setCommissiondate(Date commissiondate) {
		this.commissiondate = commissiondate;
	}

	public Date getLastservicedate() {
		return this.lastservicedate;
	}

	public void setLastservicedate(Date lastservicedate) {
		this.lastservicedate = lastservicedate;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
