drop table ix_barcodeengine;
  CREATE TABLE "WAGERLAB"."IX_BARCODEENGINE" 
   (	"BARCODEKEY" NUMBER NOT NULL ENABLE, 
	"SITEKEY" NUMBER NOT NULL ENABLE, 
	"CLASS" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DOMAIN" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STUDYKEY" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "IX_BARCODEENGINE_PK" PRIMARY KEY ("BARCODEKEY")
 );

  CREATE OR REPLACE TRIGGER "WAGERLAB"."IX_BARCODEENGINE_PK" before insert on "IX_BARCODEENGINE"    for each row begin     if inserting then       if :NEW."BARCODEKEY" is null then          select IX_BARCODEENGINE_SEQ.nextval into :NEW."BARCODEKEY" from dual;       end if;    end if; end;
/
ALTER TRIGGER "WAGERLAB"."IX_BARCODEENGINE_PK" ENABLE;

Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (1,0,'org.wager.barcode.DNABankBarcode','SINGLE_BIOSPECIMEN',0);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (5,0,'org.wager.barcode.WAFSSBiospecimenBarcode','SINGLE_BIOSPECIMEN',17);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (7,0,'org.wager.barcode.WAFSSBiospecimenBarcode','MULTIPLE_BIOSPECIMEN',17);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (9,7,'org.wager.barcode.BDSBiospecimenBarcode','SINGLE_BIOSPECIMEN',65);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (10,7,'org.wager.barcode.BDSBiospecimenBarcode','MULTIPLE_BIOSPECIMEN',65);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (13,0,'org.wager.barcode.PlateBarcode','PLATE',0);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (14,0,'org.wager.barcode.DNABankBarcode','INVENTORY',0);
Insert into IX_BARCODEENGINE (BARCODEKEY,SITEKEY,CLASS,DOMAIN,STUDYKEY) values (6,0,'org.wager.barcode.DNABankBarcode','MULTIPLE_BIOSPECIMEN',0);
