USE lims;
ALTER TABLE `lims`.`biospecimenuid_template` CHANGE COLUMN `BIOSPECIMENUID_PREFIX` `BIOSPECIMENUID_PREFIX` VARCHAR(45) NULL DEFAULT NULL  AFTER `STUDY_ID` ;
DELETE FROM `lims`.`biospecimenuid_template`;
INSERT INTO `lims`.`biospecimenuid_template`
(`STUDY_ID`,
`BIOSPECIMENUID_PREFIX`,
`BIOSPECIMENUID_TOKEN_ID`,
`BIOSPECIMENUID_PADCHAR_ID`)
SELECT ID, SUBJECTUID_PREFIX, SUBJECTUID_TOKEN_ID, SUBJECTUID_PADCHAR_ID FROM study.study;
