use study;

CREATE  TABLE `study`.`custom_field_upload` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CUSTOM_FIELD_ID` INT NOT NULL ,
  `UPLOAD_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_CFU_CUSTOM_FIELD_ID` (`CUSTOM_FIELD_ID` ASC) ,
  INDEX `FK_CFU_UPLOAD_ID` (`UPLOAD_ID` ASC) ,
  CONSTRAINT `FK_CFU_CUSTOM_FIELD_ID`
    FOREIGN KEY (`CUSTOM_FIELD_ID` )
    REFERENCES `study`.`custom_field` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CFU_UPLOAD_ID`
    FOREIGN KEY (`UPLOAD_ID` )
    REFERENCES `study`.`upload` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

