#Author: Anton Kattan
#Created: 24 feb 2006

#This is a temporary script while building the first biogenix5

#Purpose: clean subfolder recursivly from any CVS, .#,  etc ... unnecessary files
#files to clean:
#  .#* :files generated when overriding folders
#  CVS : folders generated by CVS checout


#update the starting point - normally the 
cd ..


#clean pages folder
find pages/ -name "\.#*" -exec rm {} \;
find pages/ -name "CVS" -exec rm -r {} \;

#clean stylesheet folder
find stylesheets/ -name "\.#*" -exec rm {} \;
find stylesheets/ -name "CVS" -exec rm -r {} \;

#clean src folder
find src/ -name "\.#*" -exec rm {} \;
find src/ -name "CVS" -exec rm -r {} \;

#clean src folder
find properties/ -name "\.#*" -exec rm {} \;
find properties/ -name "CVS" -exec rm -r {} \;

find . -name "\.nbattrs" -exec rm {} \;
find . -name "*~" -exec rm {} \;