use study;
CREATE  TABLE `study`.`custom_field_display` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CUSTOM_FIELD_ID` INT NOT NULL ,
  `CUSTOM_FIELD_GROUP_ID` INT NULL ,
  `SEQUENCE` INT NULL ,
  `REQUIRED` INT NULL ,
  `REQUIRED_MESSAGE` VARCHAR(45) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_CUSTOM_FIELD_GROUP_ID` (`CUSTOM_FIELD_GROUP_ID` ASC) ,
  CONSTRAINT `FK_CUSTOM_FIELD_GROUP_ID`
    FOREIGN KEY (`CUSTOM_FIELD_GROUP_ID` )
    REFERENCES `study`.`custom_field_group` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
