use study;
CREATE  TABLE `study`.`custom_field` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` TEXT NULL ,
  `FIELD_TYPE_ID` INT NULL ,
  `STUDY_ID` INT NULL ,
  `UNITS` VARCHAR(50) NULL ,
  `SEQ_NUM` INT NULL ,
  `MIN_VALUE` VARCHAR(100) NULL ,
  `MAX_VALUE` VARCHAR(100) NULL ,
  `ENCODED_VALUES` TEXT NULL ,
  `MISSING_VALUE` VARCHAR(100) NULL ,
  PRIMARY KEY (`ID`) ,
  INDEX `FK_STUDY_ID` (`STUDY_ID` ASC) ,
  INDEX `FK_FIELD_TYPE_ID` (`FIELD_TYPE_ID` ASC) ,
  CONSTRAINT `FK_STUDY_ID`
    FOREIGN KEY (`STUDY_ID` )
    REFERENCES `study`.`study` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_FIELD_TYPE_ID`
    FOREIGN KEY (`FIELD_TYPE_ID` )
    REFERENCES `study`.`field_type` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
