use study;
CREATE  TABLE `study`.`custom_field` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` TEXT NULL ,
  `FIELD_TYPE` INT NOT NULL ,
  `STUDY_ID` INT NOT NULL ,
  `ARK_MODULE_ID` INT NOT NULL ,
  `UNIT_TYPE_ID` INT NULL ,
  `MIN_VALUE` VARCHAR(45) NULL ,
  `MAX_VALUE` VARCHAR(45) NULL ,
  `ENCODED_VALUES` TEXT NULL ,
  `MISSING_VALUE` VARCHAR(45) NULL ,
  `DATA_TYPE_ID` INT NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC) ,
  UNIQUE INDEX `STUDY_ID_UNIQUE` (`STUDY_ID` ASC) ,
  UNIQUE INDEX `MODULE_ID_UNIQUE` (`ARK_MODULE_ID` ASC) ,
  INDEX `FK_STUDY_ID` (`STUDY_ID` ASC) ,
  INDEX `FK_ARK_MODULE_ID` (`ARK_MODULE_ID` ASC) ,
  INDEX `FK_UNIT_TYPE_ID` (`UNIT_TYPE_ID` ASC) ,
  INDEX `FK_DATA_TYPE_ID` (`DATA_TYPE_ID` ASC) ,
  CONSTRAINT `FK_CUSTOM_FIELD_STUDY_ID`
    FOREIGN KEY (`STUDY_ID` )
    REFERENCES `study`.`study` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CUSTOM_FIELD_ARK_MODULE_ID`
    FOREIGN KEY (`ARK_MODULE_ID` )
    REFERENCES `study`.`ark_module` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CUSTOM_FIELD_UNIT_TYPE_ID`
    FOREIGN KEY (`UNIT_TYPE_ID` )
    REFERENCES `study`.`unit_type` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_CUSTOM_FIELD_DATA_TYPE_ID`
    FOREIGN KEY (`DATA_TYPE_ID` )
    REFERENCES `study`.`data_type` (`ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



ALTER TABLE `study`.`custom_field` ADD COLUMN `HAS_DATA` INT NULL  AFTER `DATA_TYPE_ID` ;
ALTER TABLE `study`.`custom_field` CHANGE COLUMN `HAS_DATA` `HAS_DATA` INT(11) NOT NULL DEFAULT 0  ;

ALTER TABLE `study`.`custom_field` CHANGE COLUMN `HAS_DATA` `HAS_DATA` TINYINT NOT NULL DEFAULT '0'  ;


