use study;
ALTER TABLE `study`.`subject_custom_field_data` ADD COLUMN `ERROR_DATA_VALUE` TEXT NULL  AFTER `DATE_DATA_VALUE` ;

ALTER TABLE `study`.`subject_custom_field_data` ADD COLUMN `NUMBER_DATA_VALUE` DOUBLE NULL  AFTER `ERROR_DATA_VALUE` , CHANGE COLUMN `DATA_VALUE` `TEXT_DATA_VALUE` TEXT NULL DEFAULT NULL  ;


