
USE study;

-- Default list of unit types for Custom fields
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'mm', 'Millimetres');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'cm', 'Centimetres');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'm', 'Metres');
insert INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES (NULL,'g','Grams');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'kg', 'Kilograms');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'L', 'Litres');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'Days', '');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'Months', '');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'Years', '');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'hrs', 'Hours');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 'min', 'Minutes');
insert into `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) values (NULL, 's', 'Seconds');

-- Default list of unit types for BioCollection Custom fields
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'ug/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'bpm',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'g/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'fL',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'feet',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'IU/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'U',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'Age',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'m/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'pg',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'pred',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'Gy',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'%',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mS',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mm/hr',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mg/dl',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mn',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mg/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'kgm2',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mm Hg',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'kg/m2',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'Pipes',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'S',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='LIMS_COLLECTION'),'mm/hg',NULL);

-- Default list of unit types for Biospeicmen Custom fields
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'ug/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'bpm',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'g/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'fL',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'feet',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'IU/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'U',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'Age',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'m/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'pg',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'pred',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'Gy',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'%',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mS',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mm/hr',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mg/dl',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mn',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mg/L',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'kgm2',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mm Hg',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'kg/m2',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'Pipes',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'S',NULL);
INSERT INTO `unit_type` (ARK_FUNCTION_ID, NAME, DESCRIPTION) VALUES ((SELECT id FROM ark_function WHERE NAME='BIOSPECIMEN'),'mm/hg',NULL);