ALTER TABLE `lims`.`inv_site` ADD COLUMN `STUDY_ID` INT(11) NOT NULL  AFTER `LDAP_GROUP` , 
  ADD CONSTRAINT `FK_INV_SITE_STUDY`
  FOREIGN KEY (`STUDY_ID` )
  REFERENCES `study`.`study` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_INV_SITE_STUDY` (`STUDY_ID` ASC) ;