ALTER DATABASE study
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE study
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE admin
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE admin
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

ALTER DATABASE audit
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE audit
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;


ALTER DATABASE lims
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE lims
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;


ALTER DATABASE pheno
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE pheno
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;


ALTER DATABASE reporting
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE reporting
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;

/*
ALTER DATABASE geno
 CHARACTER SET utf8
  COLLATE utf8_unicode_ci; 
ALTER DATABASE geno
 DEFAULT CHARACTER SET utf8
 DEFAULT COLLATE utf8_unicode_ci;
*/