CREATE TABLE "IX_AUDIT_LOG" 
   (	"AUDITLOGKEY" NUMBER, 
	"REASON" VARCHAR2(50 BYTE), 
	"USER" VARCHAR2(50 BYTE), 
	"DATE" DATE, 
	"DELETED" NUMBER
   );
    CREATE TABLE "IX_AUDIT_ITEMS" 
   (	"AUDITITEMKEY" NUMBER, 
	"DOMAIN" VARCHAR2(50 BYTE), 
	"FIELD" VARCHAR2(50 BYTE), 
	"ORIGINALVALUE" VARCHAR2(4000 BYTE), 
	"NEWVALUE" VARCHAR2(4000 BYTE), 
	"ROWKEY" NUMBER, 
	"AUDITLOGKEY" NUMBER
   );
   
    CREATE TABLE "IX_SYSCONFIG" 
   (	"SYSCONFIGKEY" NUMBER, 
	"CONFIGNAME" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"VALUE" VARCHAR2(50 BYTE), 
	"DELETED" NUMBER, 
	"TIMESTAMP" VARCHAR2(55 BYTE)
   );
   CREATE SEQUENCE "IX_AUDIT_ITEMS_SEQ";
   CREATE SEQUENCE "IX_AUDIT_LOG_SEQ";
   CREATE SEQUENCE "IX_SYS_CFG_SEQ";
   