alter table ix_protein drop column "DISPLAYNAME";
alter table ix_protein add column "DISPLAYNAME" character varying(50);

update ix_protein set "DISPLAYNAME" = '#a 1 syntrophin' where "NAME" = 'a 1 syntrophin';
update ix_protein set "DISPLAYNAME" = '#a 7 integrin' where "NAME" = 'a 7 integrin'; 
update ix_protein set "DISPLAYNAME" = '#a 7 integrinA' where "NAME" = 'a 7 integrinA'; 
update ix_protein set "DISPLAYNAME" = '#a 7 integrinB' where "NAME" = 'a 7 integrinB'; 
update ix_protein set "DISPLAYNAME" = '#a actinin 1' where "NAME" = 'a actinin 1';
update ix_protein set "DISPLAYNAME" = '#a actinin 2' where "NAME" = 'a actinin 2'; 
update ix_protein set "DISPLAYNAME" = '#a actinin 3' where "NAME" = 'a actinin 3'; 
update ix_protein set "DISPLAYNAME" = '#a actinin 4' where "NAME" = 'a actinin 4';
update ix_protein set "DISPLAYNAME" = '#a actinin, sarcomeric' where "NAME" = 'a actinin, sarcomeric';
update ix_protein set "DISPLAYNAME" = '#a dystrobrevin 1' where "NAME" = 'a dystrobrevin 1'; 
update ix_protein set "DISPLAYNAME" = '#a dystrobrevin 2' where "NAME" = 'a dystrobrevin 2';
update ix_protein set "DISPLAYNAME" = '#a dystroglycan' where "NAME" = 'a dystroglycan'; 
update ix_protein set "DISPLAYNAME" = '#a sarcoglycan (adhalin)' where "NAME" = 'a sarcoglycan (adhalin)';
update ix_protein set "DISPLAYNAME" = 'Acetylcholine receptor subunit-#a' where "NAME" = 'Acetylcholine receptor subunit-a';
update ix_protein set "DISPLAYNAME" = 'Acetylcholine receptor subunit-#g' where "NAME" = 'Acetylcholine receptor subunit-g';
update ix_protein set "DISPLAYNAME" = 'Actin, #a-cardiac' where "NAME" = 'Actin, a-cardiac';
update ix_protein set "DISPLAYNAME" = 'Actin, #a-sarcomeric' where "NAME" = 'Actin, a-sarcomeric';
update ix_protein set "DISPLAYNAME" = 'Actin, #a-skeletal' where "NAME" = 'Actin, a-skeletal';
update ix_protein set "DISPLAYNAME" = '#b 1 syntrophin' where "NAME" = 'b 1 syntrophin'; 
update ix_protein set "DISPLAYNAME" = '#b 2 syntrophin' where "NAME" = 'b 2 syntrophin'; 
update ix_protein set "DISPLAYNAME" = '#b dystrobrevin' where "NAME" = 'b dystrobrevin';
update ix_protein set "DISPLAYNAME" = '#b dystroglycan' where "NAME" = 'b dystroglycan';
update ix_protein set "DISPLAYNAME" = '#b sarcoglycan' where "NAME" = 'b sarcoglycan'; 
update ix_protein set "DISPLAYNAME" = 'Calcium channel #a1C subunit (DHPR)' where "NAME" = 'Calcium channel a1C subunit (DHPR)';
update ix_protein set "DISPLAYNAME" = 'Collagen VI, #a3 chain' where "NAME" = 'Collagen VI, a3 chain'; 
update ix_protein set "DISPLAYNAME" = '#d sarcoglycan' where "NAME" = 'd sarcoglycan';
update ix_protein set "DISPLAYNAME" = '#g actin' where "NAME" = 'g actin';
update ix_protein set "DISPLAYNAME" = '#g sarcoglycan' where "NAME" = 'g sarcoglycan'; 
update ix_protein set "DISPLAYNAME" = 'Laminin #a 2 (Merosin)' where "NAME" = 'Laminin a 2 (Merosin)';
update ix_protein set "DISPLAYNAME" = 'Laminin #b 1' where "NAME" = 'Laminin b 1';