package org.wager.lims.biodata;

// Generated 22/10/2009 4:41:14 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Criteria generated by hbm2java
 */
@Entity
@Table(name = "IX_BD_CRITERIA")
public class Criteria implements java.io.Serializable {

	private BigDecimal criteriakey;
	private String domain;
	private String field;
	private String value;
	private String description;
	private List<Group> groups = new ArrayList<Group>();

	public Criteria() {
	}

	public Criteria(BigDecimal criteriakey) {
		this.criteriakey = criteriakey;
	}

	public Criteria(BigDecimal criteriakey, String domain, String field,
			String value, String description) {
		this.criteriakey = criteriakey;
		this.domain = domain;
		this.field = field;
		this.value = value;
		this.description = description;
	
	}

	@Id
	@Column(name = "CRITERIAKEY", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getCriteriakey() {
		return this.criteriakey;
	}

	public void setCriteriakey(BigDecimal criteriakey) {
		this.criteriakey = criteriakey;
	}

	@Column(name = "DOMAIN", length = 30)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "FIELD", length = 30)
	public String getField() {
		return this.field;
	}

	public void setField(String field) {
		this.field = field;
	}

	@Column(name = "VALUE")
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@ManyToMany
	@JoinTable(
	name = "IX_BD_GROUP_CRITERIA",
	joinColumns = {@JoinColumn(name = "CRITERIAKEY")},
	inverseJoinColumns = {@JoinColumn(name = "GROUPKEY")}
	)
	public List<Group> getGroups() {
		return groups;
	}

	public void setGroups(List<Group> g)
	{
		this.groups = g;
	}
}
