package org.wager.lims.biodata;

// Generated 20/10/2009 12:25:58 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Data generated by hbm2java
 */
@Entity
@Table(name = "IX_BIODATA", uniqueConstraints = @UniqueConstraint(columnNames = {
		"BIOSPECIMENKEY", "FIELDKEY" }))
public class Data implements java.io.Serializable {

	private BigDecimal biospecimenkey;
	private Long biodatakey;
	private Field field;
	private Date dateCollected;
	private String stringValue;
	private BigDecimal numberValue;
	private Date dateValue;

	public Data() {
	}

	public Data(BigDecimal biospecimenkey, Field field, Date dateCollected) {
		this.biospecimenkey = biospecimenkey;
		this.field = field;
		this.dateCollected = dateCollected;
	}

	public Data(BigDecimal biospecimenkey, Field field, Date dateCollected,
			String stringValue, BigDecimal numberValue, Date dateValue) {
		this.biospecimenkey = biospecimenkey;
		this.field = field;
		this.dateCollected = dateCollected;
		this.stringValue = stringValue;
		this.numberValue = numberValue;
		this.dateValue = dateValue;
	}


	@Column(name = "BIOSPECIMENKEY", unique = false, nullable = false, precision = 22, scale = 0)
	public BigDecimal getBiospecimenkey() {
		return this.biospecimenkey;
	}
	
	@Id
	@GeneratedValue(generator="DataSeq")
    @SequenceGenerator(name="DataSeq",sequenceName="IX_BIODATA_BIODATAKEY_SEQ", allocationSize=1)
	@Column(name = "BIODATAKEY", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getBiodatakey() {
		return this.biodatakey;
	}

	public void setBiodatakey(Long biodatakey) {
		this.biodatakey = biodatakey;
	}
	
	public void setBiospecimenkey(BigDecimal biospecimenkey) {
		this.biospecimenkey = biospecimenkey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELDKEY", nullable = false)
	public Field getField() {
		return this.field;
	}

	public void setField(Field field) {
		this.field = field;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_COLLECTED", nullable = false, length = 7)
	public Date getDateCollected() {
		return this.dateCollected;
	}

	public void setDateCollected(Date dateCollected) {
		this.dateCollected = dateCollected;
	}

	@Column(name = "STRING_VALUE", length = 1024)
	public String getStringValue() {
		return this.stringValue;
	}

	public void setStringValue(String stringValue) {
		this.stringValue = stringValue;
	}

	@Column(name = "NUMBER_VALUE", precision = 22, scale = 0)
	public BigDecimal getNumberValue() {
		return this.numberValue;
	}
	

	public void setNumberValue(BigDecimal numberValue) {
		this.numberValue = numberValue;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_VALUE", length = 7)
	public Date getDateValue() {
		return this.dateValue;
	}

	public void setDateValue(Date dateValue) {
		this.dateValue = dateValue;
	}

}
