package org.wager.lims.biodata;

// Generated 20/10/2009 12:25:58 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Field generated by hbm2java
 */
@Entity
@Table(name = "IX_BIODATA_FIELD")
public class Field implements java.io.Serializable {

	private BigDecimal fieldkey;
	private Type type;
	private Unit unit;
	private String format;
	private String fieldname;
	private String studykey;
	private Set<Data> datas = new HashSet<Data>(0);

	public Field() {
	}

	public Field(BigDecimal fieldkey, Type type, Unit unit, String fieldname,
			String studykey) {
		this.fieldkey = fieldkey;
		this.type = type;
		this.unit = unit;
		this.fieldname = fieldname;
		this.studykey = studykey;
	}

	public Field(BigDecimal fieldkey, Type type, Unit unit, String format,
			BigDecimal groupkey, String fieldname, String studykey,
			Set<Data> datas) {
		this.fieldkey = fieldkey;
		this.type = type;
		this.unit = unit;
		this.format = format;
		this.fieldname = fieldname;
		this.studykey = studykey;
		this.datas = datas;
	}

	@Id
	@Column(name = "FIELDKEY", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getFieldkey() {
		return this.fieldkey;
	}

	public void setFieldkey(BigDecimal fieldkey) {
		this.fieldkey = fieldkey;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TYPEKEY", nullable = false)
	public Type getType() {
		return this.type;
	}

	public void setType(Type type) {
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNITKEY", nullable = false)
	public Unit getUnit() {
		return this.unit;
	}

	public void setUnit(Unit unit) {
		this.unit = unit;
	}

	@Column(name = "FORMAT", length = 20)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	

	@Column(name = "FIELDNAME", nullable = false, length = 20)
	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	@Column(name = "STUDYKEY", nullable = false, length = 20)
	public String getStudykey() {
		return this.studykey;
	}

	public void setStudykey(String studykey) {
		this.studykey = studykey;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "field")
	public Set<Data> getDatas() {
		return this.datas;
	}

	public void setDatas(Set<Data> datas) {
		this.datas = datas;
	}

}
