package org.wager.lims.biodata;

// Generated 20/10/2009 12:25:58 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "IX_BIODATA_TYPES")
public class Type implements java.io.Serializable {

	private BigDecimal typekey;
	private String typename;
	private Set<Field> fields = new HashSet<Field>(0);

	public Type() {
	}

	public Type(BigDecimal typekey, String typename) {
		this.typekey = typekey;
		this.typename = typename;
	}

	public Type(BigDecimal typekey, String typename, Set<Field> fields) {
		this.typekey = typekey;
		this.typename = typename;
		this.fields = fields;
	}

	@Id
	@Column(name = "TYPEKEY", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getTypekey() {
		return this.typekey;
	}

	public void setTypekey(BigDecimal typekey) {
		this.typekey = typekey;
	}

	@Column(name = "TYPENAME", nullable = false, length = 20)
	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set<Field> getFields() {
		return this.fields;
	}

	public void setFields(Set<Field> fields) {
		this.fields = fields;
	}

}
