package org.wager.lims.biodata;

// Generated 20/10/2009 12:25:58 PM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name = "IX_BIODATA_UNITS")
public class Unit implements java.io.Serializable {

	private BigDecimal unitkey;
	private String unitname;
	private Set<Field> fields = new HashSet<Field>(0);

	public Unit() {
	}

	public Unit(BigDecimal unitkey, String unitname) {
		this.unitkey = unitkey;
		this.unitname = unitname;
	}

	public Unit(BigDecimal unitkey, String unitname, Set<Field> fields) {
		this.unitkey = unitkey;
		this.unitname = unitname;
		this.fields = fields;
	}

	@Id
	@Column(name = "UNITKEY", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getUnitkey() {
		return this.unitkey;
	}

	public void setUnitkey(BigDecimal unitkey) {
		this.unitkey = unitkey;
	}

	@Column(name = "UNITNAME", nullable = false, length = 50)
	public String getUnitname() {
		return this.unitname;
	}

	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "unit")
	public Set<Field> getFields() {
		return this.fields;
	}

	public void setFields(Set<Field> fields) {
		this.fields = fields;
	}

}
