#Author: Anton Kattan
#Created: 24 feb 2006

#This is a temporary script while building the first biogenix5

#Purpose: clean subfolder recursivly from any CVS, .#,  etc ... unnecessary files
#files to clean:
#  .svn : folders generated by CVS checout



#update the starting point - normally the 
cd ..


#clean pages folder
find pages/ -name ".svn" -exec rm -r -f {} \;

#clean stylesheet folder
find stylesheets/ -name ".svn" -exec rm -r -f {} \;

#clean src folder
find src/ -name ".svn" -exec rm -r -f {} \;

#clean src folder
find properties/ -name ".svn" -exec rm -r -f {} \;