create database if not exists `disease`;

use `disease`;

DROP TABLE IF EXISTS `Affection_status`;

CREATE TABLE `Affection_status` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`ID`)
) ENGINE=InnoDB charset=latin1;

INSERT INTO `Affection_status` (`NAME`) VALUES ("Yes");
INSERT INTO `Affection_status` (`NAME`) VALUES ("No");
INSERT INTO `Affection_status` (`NAME`) VALUES ("Carrier");

DROP TABLE IF EXISTS `Disease`;

CREATE TABLE `Disease` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`STUDY_ID` int(11) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	`CUSTOM_FIELD_GROUP_ID` int(11) DEFAULT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK_STUDY_ID` (`STUDY_ID`),
	KEY `FK_CUSTOM_FIELD_GROUP_ID` (`CUSTOM_FIELD_GROUP_ID`),
	CONSTRAINT `FK_STUDY_ID` FOREIGN KEY (`STUDY_ID`) REFERENCES `STUDY`.`STUDY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_CUSTOM_FIELD_GROUP_ID` FOREIGN KEY (`CUSTOM_FIELD_GROUP_ID`) REFERENCES `STUDY`.`CUSTOM_FIELD_GROUP` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=latin1;

DROP TABLE IF EXISTS `Affection`;

CREATE TABLE `Affection` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`DISEASE_ID` int(11) NOT NULL,
	`LINKSUBJECTSTUDY_ID` int(11) NOT NULL,
	`AFFECTION_STATUS_ID` int(11) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK_DISEASE_ID` (`DISEASE_ID`),
	KEY `FK_LINKSUBJECTSTUDY_ID` (`LINKSUBJECTSTUDY_ID`),
	KEY `FK_AFFECTION_STATUS_ID` (`AFFECTION_STATUS_ID`),
	CONSTRAINT `FK_DISEASE_ID` FOREIGN KEY (`DISEASE_ID`) REFERENCES `Disease` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_LINKSUBJECTSTUDY_ID` FOREIGN KEY (`LINKSUBJECTSTUDY_ID`) REFERENCES `STUDY`.`LINK_SUBJECT_STUDY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_AFFECTION_STATUS_ID` FOREIGN KEY (`AFFECTION_STATUS_ID`) REFERENCES `Affection_status` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB charset=latin1;

DROP TABLE IF EXISTS `AFFECTION_CUSTOM_FIELD_DATA`;

CREATE TABLE `AFFECTION_CUSTOM_FIELD_DATA` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AFFECTION_ID` int(11) NOT NULL,
  `CUSTOM_FIELD_DISPLAY_ID` int(11) NOT NULL,
  `TEXT_DATA_VALUE` text,
  `DATE_DATA_VALUE` datetime DEFAULT NULL,
  `ERROR_DATA_VALUE` text,
  `NUMBER_DATA_VALUE` double DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UQ_SCFD_CFD_LSS` (`AFFECTION_ID`,`CUSTOM_FIELD_DISPLAY_ID`) USING BTREE,
  KEY `FK_CFD_LINK_SUBJECT_STUDY_ID` (`AFFECTION_ID`),
  KEY `FK_CFD_CUSTOM_FIELD_DISPLAY_ID` (`CUSTOM_FIELD_DISPLAY_ID`),
  CONSTRAINT `FK_CFD_CUSTOM_FIELD_DISPLAY_ID` FOREIGN KEY (`CUSTOM_FIELD_DISPLAY_ID`) REFERENCES `STUDY`.`custom_field_display` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_CFD_LINK_SUBJECT_STUDY_ID` FOREIGN KEY (`AFFECTION_ID`) REFERENCES `AFFECTION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB CHARSET=latin1;

DROP TABLE IF EXISTS `MUTATION`;

CREATE TABLE `MUTATION` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`LINKSUBJECTSTUDY_ID` int(11) NOT NULL,
	`DISEASE_ID` int(11) NOT NULL,
	`SCREENED` boolean NOT NULL,
	`TESTED` boolean NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK_DISEASE_ID` (`DISEASE_ID`),
	KEY `FK_LINK_SUBJECT_STUDY_ID` (`LINKSUBJECTSTUDY_ID`),
	CONSTRAINT `FK_MUT_DISEASE_ID` FOREIGN KEY (`DISEASE_ID`) REFERENCES `DISEASE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_MUT_LINK_SUBJECT_STUDY_ID` FOREIGN KEY (`LINKSUBJECTSTUDY_ID`) REFERENCES `STUDY`.`link_subject_study` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=latin1;

DROP TABLE IF EXISTS `GENE`;

CREATE TABLE `GENE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`STUDY_ID` int(11) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK_STUDY_ID` (`STUDY_ID`),
	CONSTRAINT `FK_GENE_STUDY_ID` FOREIGN KEY (`STUDY_ID`) REFERENCES `STUDY`.`STUDY` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=latin1;

DROP TABLE IF EXISTS `POSITION`;

CREATE TABLE `POSITION` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`GENE_ID` int(11) NOT NULL,
	`NAME` varchar(100) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK_GENE_ID` (`GENE_ID`),
	CONSTRAINT `FK_POS_GENE_ID` FOREIGN KEY (`GENE_ID`) REFERENCES `GENE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=latin1;

CREATE TABLE `GENE_DISEASE` (
	`ID` int(11) NOT NULL AUTO_INCREMENT,
	`GENE_ID` int(11) NOT NULL,
	`DISEASE_ID` int(11) NOT NULL,
	PRIMARY KEY (`ID`),
	KEY `FK_GENE_ID` (`GENE_ID`),
	KEY `FK_DISEASE_ID` (`DISEASE_ID`),
	CONSTRAINT `FK_GENE_D_ID` FOREIGN KEY (`GENE_ID`) REFERENCES `GENE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `FK_DISEASE_G_ID` FOREIGN KEY (`DISEASE_ID`) REFERENCES `DISEASE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB CHARSET=latin1;

USE `study`;

INSERT INTO `ark_module` (`NAME`) VALUES ("Disease");

SET @module_id = (select id from `ark_module` where `NAME` = "Disease");

INSERT INTO `ark_user_role` (`ark_user_id`, `ark_role_id`, `ark_module_id`, `study_id`) VALUES (1,1,@module_id,NULL);

INSERT INTO `ark_function` (`NAME`, `ARK_FUNCTION_TYPE_ID`, `RESOURCE_KEY`) VALUES ("GENE", 1, "tab.module.disease.gene");
SET @function_id = (select id from `ark_function` where `name` = "GENE");
INSERT INTO `ark_module_function` (`ark_module_id`, `ark_function_id`, `function_sequence`) VALUES (@module_id, @function_id, 1);

INSERT INTO `ark_function` (`NAME`, `ARK_FUNCTION_TYPE_ID`, `RESOURCE_KEY`) VALUES ("POSITION", 1, "tab.module.disease.position");
SET @function_id = (select id from `ark_function` where `name` = "POSITION");
INSERT INTO `ark_module_function` (`ark_module_id`, `ark_function_id`, `function_sequence`) VALUES (@module_id, @function_id, 1);

INSERT INTO `ark_function` (`NAME`, `ARK_FUNCTION_TYPE_ID`, `RESOURCE_KEY`) VALUES ("DISEASE", 1, "tab.module.disease.disease");
SET @function_id = (select id from `ark_function` where `name` = "DISEASE");
INSERT INTO `ark_module_function` (`ark_module_id`, `ark_function_id`, `function_sequence`) VALUES (@module_id, @function_id, 1);
