/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class au_org_theark_core_jni_ArkMadelineProxy */

#ifndef _Included_au_org_theark_core_jni_ArkMadelineProxy
#define _Included_au_org_theark_core_jni_ArkMadelineProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef au_org_theark_core_jni_ArkMadelineProxy_serialVersionUID
#define au_org_theark_core_jni_ArkMadelineProxy_serialVersionUID 1LL
/*
 * Class:     au_org_theark_core_jni_ArkMadelineProxy
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_au_org_theark_core_jni_ArkMadelineProxy_connect
  (JNIEnv *, jobject);

/*
 * Class:     au_org_theark_core_jni_ArkMadelineProxy
 * Method:    generatePedigree
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_au_org_theark_core_jni_ArkMadelineProxy_generatePedigree
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
