/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class au_org_theark_core_jni_MadelineArkProxy */

#ifndef _Included_au_org_theark_core_jni_MadelineArkProxy
#define _Included_au_org_theark_core_jni_MadelineArkProxy
#ifdef __cplusplus
extern "C" {
#endif
#undef au_org_theark_core_jni_MadelineArkProxy_serialVersionUID
#define au_org_theark_core_jni_MadelineArkProxy_serialVersionUID 1LL
/*
 * Class:     au_org_theark_core_jni_MadelineArkProxy
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_au_org_theark_core_jni_MadelineArkProxy_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     au_org_theark_core_jni_MadelineArkProxy
 * Method:    generatePedigree
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_au_org_theark_core_jni_MadelineArkProxy_generatePedigree
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
