package au.org.theark.core.model.report.entity;

public enum FieldCategory {
	DEMOGRAPHIC_FIELD, 
	BIOSPECIMEN_FIELD, 
	BIOCOLLECTION_FIELD, 
	BIOCOLLECTION_CFD, 
	BIOSPECIMEN_CFD, 
	SUBJECT_CFD, 
	PHENO_FD,
	GENO, 
	CONSENT_STATUS_FIELD
}

