use study;

-- NOTE: when applying on ArkTestDB had to DROP INDEX 'FK_CUSTOMFIELD_FIELD_TYPE_ID' beforehand
ALTER TABLE `study`.`custom_field` 
  ADD CONSTRAINT `FK_CUSTOMFIELD_FIELD_TYPE_ID`
  FOREIGN KEY (`FIELD_TYPE_ID` )
  REFERENCES `study`.`field_type` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_CUSTOMFIELD_FIELD_TYPE_ID` (`FIELD_TYPE_ID` ASC) ;

