package au.org.theark.core.model.lims.entity;

// Generated Jun 14, 2011 3:39:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

import au.org.theark.core.model.Constants;

/**
 * Admission generated by hbm2java
 */
@Entity
@Table(name = "admission", schema = Constants.LIMS_TABLE_SCHEMA)
public class Admission implements java.io.Serializable {

	private String id;
	private String timestamp;
	private int admissionId;
	private int patientId;
	private Integer studyId;
	private Date admissiondate;
	private Integer deleted;
	private String comments;
	private String hospital;
	private Date surgerydate;
	private String diagCategory;
	private String refDoctor;
	private Integer patientage;
	private Date dischargedate;
	private String hospitalUr;
	private Date diagDate;
	private Integer collectiongroupId;
	private String episodeNum;
	private String episodeDesc;
	private String collectiongroup;
	private String tissuetype;
	private String tissueclass;
	private String pathlabno;
	private Set<Biospecimen> biospecimens = new HashSet<Biospecimen>(0);

	public Admission() {
	}

	public Admission(String id, int admissionId, int patientId) {
		this.id = id;
		this.admissionId = admissionId;
		this.patientId = patientId;
	}

	public Admission(String id, int admissionId, int patientId,
			Integer studyId, Date admissiondate, Integer deleted,
			String comments, String hospital, Date surgerydate,
			String diagCategory, String refDoctor, Integer patientage,
			Date dischargedate, String hospitalUr, Date diagDate,
			Integer collectiongroupId, String episodeNum, String episodeDesc,
			String collectiongroup, String tissuetype, String tissueclass,
			String pathlabno, Set<Biospecimen> biospecimens) {
		this.id = id;
		this.admissionId = admissionId;
		this.patientId = patientId;
		this.studyId = studyId;
		this.admissiondate = admissiondate;
		this.deleted = deleted;
		this.comments = comments;
		this.hospital = hospital;
		this.surgerydate = surgerydate;
		this.diagCategory = diagCategory;
		this.refDoctor = refDoctor;
		this.patientage = patientage;
		this.dischargedate = dischargedate;
		this.hospitalUr = hospitalUr;
		this.diagDate = diagDate;
		this.collectiongroupId = collectiongroupId;
		this.episodeNum = episodeNum;
		this.episodeDesc = episodeDesc;
		this.collectiongroup = collectiongroup;
		this.tissuetype = tissuetype;
		this.tissueclass = tissueclass;
		this.pathlabno = pathlabno;
		this.biospecimens = biospecimens;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Version
	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "ADMISSION_ID", nullable = false)
	public int getAdmissionId() {
		return this.admissionId;
	}

	public void setAdmissionId(int admissionId) {
		this.admissionId = admissionId;
	}

	@Column(name = "PATIENT_ID", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "STUDY_ID")
	public Integer getStudyId() {
		return this.studyId;
	}

	public void setStudyId(Integer studyId) {
		this.studyId = studyId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ADMISSIONDATE", length = 19)
	public Date getAdmissiondate() {
		return this.admissiondate;
	}

	public void setAdmissiondate(Date admissiondate) {
		this.admissiondate = admissiondate;
	}

	@Column(name = "DELETED")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Column(name = "COMMENTS", length = 65535)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

	@Column(name = "HOSPITAL", length = 50)
	public String getHospital() {
		return this.hospital;
	}

	public void setHospital(String hospital) {
		this.hospital = hospital;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SURGERYDATE", length = 19)
	public Date getSurgerydate() {
		return this.surgerydate;
	}

	public void setSurgerydate(Date surgerydate) {
		this.surgerydate = surgerydate;
	}

	@Column(name = "DIAG_CATEGORY", length = 50)
	public String getDiagCategory() {
		return this.diagCategory;
	}

	public void setDiagCategory(String diagCategory) {
		this.diagCategory = diagCategory;
	}

	@Column(name = "REF_DOCTOR", length = 50)
	public String getRefDoctor() {
		return this.refDoctor;
	}

	public void setRefDoctor(String refDoctor) {
		this.refDoctor = refDoctor;
	}

	@Column(name = "PATIENTAGE")
	public Integer getPatientage() {
		return this.patientage;
	}

	public void setPatientage(Integer patientage) {
		this.patientage = patientage;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DISCHARGEDATE", length = 19)
	public Date getDischargedate() {
		return this.dischargedate;
	}

	public void setDischargedate(Date dischargedate) {
		this.dischargedate = dischargedate;
	}

	@Column(name = "HOSPITAL_UR", length = 50)
	public String getHospitalUr() {
		return this.hospitalUr;
	}

	public void setHospitalUr(String hospitalUr) {
		this.hospitalUr = hospitalUr;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DIAG_DATE", length = 19)
	public Date getDiagDate() {
		return this.diagDate;
	}

	public void setDiagDate(Date diagDate) {
		this.diagDate = diagDate;
	}

	@Column(name = "COLLECTIONGROUP_ID")
	public Integer getCollectiongroupId() {
		return this.collectiongroupId;
	}

	public void setCollectiongroupId(Integer collectiongroupId) {
		this.collectiongroupId = collectiongroupId;
	}

	@Column(name = "EPISODE_NUM", length = 50)
	public String getEpisodeNum() {
		return this.episodeNum;
	}

	public void setEpisodeNum(String episodeNum) {
		this.episodeNum = episodeNum;
	}

	@Column(name = "EPISODE_DESC", length = 50)
	public String getEpisodeDesc() {
		return this.episodeDesc;
	}

	public void setEpisodeDesc(String episodeDesc) {
		this.episodeDesc = episodeDesc;
	}

	@Column(name = "COLLECTIONGROUP", length = 50)
	public String getCollectiongroup() {
		return this.collectiongroup;
	}

	public void setCollectiongroup(String collectiongroup) {
		this.collectiongroup = collectiongroup;
	}

	@Column(name = "TISSUETYPE", length = 50)
	public String getTissuetype() {
		return this.tissuetype;
	}

	public void setTissuetype(String tissuetype) {
		this.tissuetype = tissuetype;
	}

	@Column(name = "TISSUECLASS", length = 50)
	public String getTissueclass() {
		return this.tissueclass;
	}

	public void setTissueclass(String tissueclass) {
		this.tissueclass = tissueclass;
	}

	@Column(name = "PATHLABNO", length = 20)
	public String getPathlabno() {
		return this.pathlabno;
	}

	public void setPathlabno(String pathlabno) {
		this.pathlabno = pathlabno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "admission")
	public Set<Biospecimen> getBiospecimens() {
		return this.biospecimens;
	}

	public void setBiospecimens(Set<Biospecimen> biospecimens) {
		this.biospecimens = biospecimens;
	}

}
