package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * Barcodeformat generated by hbm2java
 */
@Entity
@Table(name = "barcodeformat", schema = Constants.LIMS_TABLE_SCHEMA)
public class Barcodeformat implements java.io.Serializable
{

	private Long		id;
	private Integer	studyId;
	private String		fieldname;
	private String		const_;
	private Integer	type;
	private Integer	length;
	private String		format;
	private Integer	order;

	public Barcodeformat()
	{
	}

	public Barcodeformat(Long id)
	{
		this.id = id;
	}

	public Barcodeformat(Long id, Integer studyId, String fieldname, String const_, Integer type, Integer length, String format, Integer order)
	{
		this.id = id;
		this.studyId = studyId;
		this.fieldname = fieldname;
		this.const_ = const_;
		this.type = type;
		this.length = length;
		this.format = format;
		this.order = order;
	}

	@Id
	@SequenceGenerator(name = "barcodeformat_generator", sequenceName = "BARCODEFORMAT_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "barcodeformat_generator")
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	@Column(name = "STUDY_ID")
	public Integer getStudyId()
	{
		return this.studyId;
	}

	public void setStudyId(Integer studyId)
	{
		this.studyId = studyId;
	}

	@Column(name = "FIELDNAME", length = 100)
	public String getFieldname()
	{
		return this.fieldname;
	}

	public void setFieldname(String fieldname)
	{
		this.fieldname = fieldname;
	}

	@Column(name = "CONST", length = 100)
	public String getConst_()
	{
		return this.const_;
	}

	public void setConst_(String const_)
	{
		this.const_ = const_;
	}

	@Column(name = "TYPE")
	public Integer getType()
	{
		return this.type;
	}

	public void setType(Integer type)
	{
		this.type = type;
	}

	@Column(name = "LENGTH")
	public Integer getLength()
	{
		return this.length;
	}

	public void setLength(Integer length)
	{
		this.length = length;
	}

	@Column(name = "FORMAT", length = 50)
	public String getFormat()
	{
		return this.format;
	}

	public void setFormat(String format)
	{
		this.format = format;
	}

	@Column(name = "ORDER")
	public Integer getOrder()
	{
		return this.order;
	}

	public void setOrder(Integer order)
	{
		this.order = order;
	}

}
