package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * BiodataUnit generated by hbm2java
 */
@Entity
@Table(name = "biodata_unit", schema = Constants.LIMS_TABLE_SCHEMA)
public class BiodataUnit implements java.io.Serializable
{

	private Long		id;
	private String	unitname;
	private String	description;

	public BiodataUnit()
	{
	}

	public BiodataUnit(Long id, String unitname)
	{
		this.id = id;
		this.unitname = unitname;
	}

	public BiodataUnit(Long id, String unitname, String description)
	{
		this.id = id;
		this.unitname = unitname;
		this.description = description;
	}

	@Id
	@SequenceGenerator(name = "biodataunit_generator", sequenceName = "BIODATAUNIT_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "biodataunit_generator")
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	@Column(name = "UNITNAME", nullable = false, length = 50)
	public String getUnitname()
	{
		return this.unitname;
	}

	public void setUnitname(String unitname)
	{
		this.unitname = unitname;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

}
