package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * BiodataGroupCriteria generated by hbm2java
 */
@Entity
@Table(name = "biodata_group_criteria", schema = Constants.LIMS_TABLE_SCHEMA)
public class BiodataGroupCriteria implements java.io.Serializable
{

	private Long					id;
	private BiodataGroup		biodataGroup;
	private BiodataCriteria	biodataCriteria;

	public BiodataGroupCriteria()
	{
	}

	public BiodataGroupCriteria(Long id, BiodataGroup biodataGroup, BiodataCriteria biodataCriteria)
	{
		this.id = id;
		this.biodataGroup = biodataGroup;
		this.biodataCriteria = biodataCriteria;
	}

	@Id
	@SequenceGenerator(name = "biodatagroupcriteria_generator", sequenceName = "BIODATAGROUPCRITERIA_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "biodatagroupcriteria_generator")
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID", nullable = false)
	public BiodataGroup getBiodataGroup()
	{
		return this.biodataGroup;
	}

	public void setBiodataGroup(BiodataGroup biodataGroup)
	{
		this.biodataGroup = biodataGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRITERIA_ID", nullable = false)
	public BiodataCriteria getBiodataCriteria()
	{
		return this.biodataCriteria;
	}

	public void setBiodataCriteria(BiodataCriteria biodataCriteria)
	{
		this.biodataCriteria = biodataCriteria;
	}

}
