package au.org.theark.core.model.lims.entity;

// Generated 14/06/2011 1:11:20 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BiodataGroupCriteria generated by hbm2java
 */
@Entity
@Table(name = "biodata_group_criteria", catalog = "lims")
public class BiodataGroupCriteria implements java.io.Serializable
{

	private int					id;
	private BiodataGroup		biodataGroup;
	private BiodataCriteria	biodataCriteria;

	public BiodataGroupCriteria()
	{
	}

	public BiodataGroupCriteria(int id, BiodataGroup biodataGroup, BiodataCriteria biodataCriteria)
	{
		this.id = id;
		this.biodataGroup = biodataGroup;
		this.biodataCriteria = biodataCriteria;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID", nullable = false)
	public BiodataGroup getBiodataGroup()
	{
		return this.biodataGroup;
	}

	public void setBiodataGroup(BiodataGroup biodataGroup)
	{
		this.biodataGroup = biodataGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRITERIA_ID", nullable = false)
	public BiodataCriteria getBiodataCriteria()
	{
		return this.biodataCriteria;
	}

	public void setBiodataCriteria(BiodataCriteria biodataCriteria)
	{
		this.biodataCriteria = biodataCriteria;
	}

}
