package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * BiodataFieldGroup generated by hbm2java
 */
@Entity
@Table(name = "biodata_field_group", schema = Constants.LIMS_TABLE_SCHEMA)
public class BiodataFieldGroup implements java.io.Serializable
{

	private Long				id;
	private BiodataGroup	biodataGroup;
	private BiodataField	biodataField;
	private Integer		position;

	public BiodataFieldGroup()
	{
	}

	public BiodataFieldGroup(Long id, BiodataGroup biodataGroup, BiodataField biodataField)
	{
		this.id = id;
		this.biodataGroup = biodataGroup;
		this.biodataField = biodataField;
	}

	public BiodataFieldGroup(Long id, BiodataGroup biodataGroup, BiodataField biodataField, Integer position)
	{
		this.id = id;
		this.biodataGroup = biodataGroup;
		this.biodataField = biodataField;
		this.position = position;
	}

	@Id
	@SequenceGenerator(name = "biodatafieldgroup_generator", sequenceName = "BIODATAFIELDGROUP_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "biodatafieldgroup_generator")
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID", nullable = false)
	public BiodataGroup getBiodataGroup()
	{
		return this.biodataGroup;
	}

	public void setBiodataGroup(BiodataGroup biodataGroup)
	{
		this.biodataGroup = biodataGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "FIELD_ID", nullable = false)
	public BiodataField getBiodataField()
	{
		return this.biodataField;
	}

	public void setBiodataField(BiodataField biodataField)
	{
		this.biodataField = biodataField;
	}

	@Column(name = "POSITION")
	public Integer getPosition()
	{
		return this.position;
	}

	public void setPosition(Integer position)
	{
		this.position = position;
	}

}
