/*******************************************************************************
 * Copyright (c) 2011  University of Western Australia. All rights reserved.
 * 
 * This file is part of The Ark.
 * 
 * The Ark is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * The Ark is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * BiodataGroupCriteria generated by hbm2java
 */
@Entity
@Table(name = "biodata_group_criteria", schema = Constants.LIMS_TABLE_SCHEMA)
public class BiodataGroupCriteria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long				id;
	private BiodataGroup		biodataGroup;
	private BiodataCriteria	biodataCriteria;

	public BiodataGroupCriteria() {
	}

	public BiodataGroupCriteria(Long id, BiodataGroup biodataGroup, BiodataCriteria biodataCriteria) {
		this.id = id;
		this.biodataGroup = biodataGroup;
		this.biodataCriteria = biodataCriteria;
	}

	@Id
	@SequenceGenerator(name = "biodatagroupcriteria_generator", sequenceName = "BIODATAGROUPCRITERIA_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "biodatagroupcriteria_generator")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "GROUP_ID", nullable = false)
	public BiodataGroup getBiodataGroup() {
		return this.biodataGroup;
	}

	public void setBiodataGroup(BiodataGroup biodataGroup) {
		this.biodataGroup = biodataGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CRITERIA_ID", nullable = false)
	public BiodataCriteria getBiodataCriteria() {
		return this.biodataCriteria;
	}

	public void setBiodataCriteria(BiodataCriteria biodataCriteria) {
		this.biodataCriteria = biodataCriteria;
	}

}
