package au.org.theark.core.model.lims.entity;

// Generated Jun 14, 2011 3:39:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BiodataField generated by hbm2java
 */
@Entity
@Table(name = "biodata_field", catalog = "lims")
public class BiodataField implements java.io.Serializable {

	private int id;
	private int typeId;
	private String format;
	private String columnname;
	private Integer unitId;
	private String lovtype;
	private String domain;
	private String fieldname;
	private Set<Biodata> biodatas = new HashSet<Biodata>(0);
	private Set<BiodataFieldGroup> biodataFieldGroups = new HashSet<BiodataFieldGroup>(
			0);

	public BiodataField() {
	}

	public BiodataField(int id, int typeId, String columnname) {
		this.id = id;
		this.typeId = typeId;
		this.columnname = columnname;
	}

	public BiodataField(int id, int typeId, String format, String columnname,
			Integer unitId, String lovtype, String domain, String fieldname,
			Set<Biodata> biodatas, Set<BiodataFieldGroup> biodataFieldGroups) {
		this.id = id;
		this.typeId = typeId;
		this.format = format;
		this.columnname = columnname;
		this.unitId = unitId;
		this.lovtype = lovtype;
		this.domain = domain;
		this.fieldname = fieldname;
		this.biodatas = biodatas;
		this.biodataFieldGroups = biodataFieldGroups;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "TYPE_ID", nullable = false)
	public int getTypeId() {
		return this.typeId;
	}

	public void setTypeId(int typeId) {
		this.typeId = typeId;
	}

	@Column(name = "FORMAT", length = 20)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@Column(name = "COLUMNNAME", nullable = false, length = 50)
	public String getColumnname() {
		return this.columnname;
	}

	public void setColumnname(String columnname) {
		this.columnname = columnname;
	}

	@Column(name = "UNIT_ID")
	public Integer getUnitId() {
		return this.unitId;
	}

	public void setUnitId(Integer unitId) {
		this.unitId = unitId;
	}

	@Column(name = "LOVTYPE", length = 20)
	public String getLovtype() {
		return this.lovtype;
	}

	public void setLovtype(String lovtype) {
		this.lovtype = lovtype;
	}

	@Column(name = "DOMAIN", length = 50)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "FIELDNAME", length = 50)
	public String getFieldname() {
		return this.fieldname;
	}

	public void setFieldname(String fieldname) {
		this.fieldname = fieldname;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "biodataField")
	public Set<Biodata> getBiodatas() {
		return this.biodatas;
	}

	public void setBiodatas(Set<Biodata> biodatas) {
		this.biodatas = biodatas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "biodataField")
	public Set<BiodataFieldGroup> getBiodataFieldGroups() {
		return this.biodataFieldGroups;
	}

	public void setBiodataFieldGroups(Set<BiodataFieldGroup> biodataFieldGroups) {
		this.biodataFieldGroups = biodataFieldGroups;
	}

}
