package au.org.theark.core.model.lims.entity;

// Generated Jun 14, 2011 3:39:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BiodataFieldLov generated by hbm2java
 */
@Entity
@Table(name = "biodata_field_lov", catalog = "lims")
public class BiodataFieldLov implements java.io.Serializable {

	private int id;
	private int listId;
	private String value;
	private int order;

	public BiodataFieldLov() {
	}

	public BiodataFieldLov(int id, int listId, String value, int order) {
		this.id = id;
		this.listId = listId;
		this.value = value;
		this.order = order;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "LIST_ID", nullable = false)
	public int getListId() {
		return this.listId;
	}

	public void setListId(int listId) {
		this.listId = listId;
	}

	@Column(name = "VALUE", nullable = false, length = 50)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ORDER", nullable = false)
	public int getOrder() {
		return this.order;
	}

	public void setOrder(int order) {
		this.order = order;
	}

}
