package au.org.theark.core.model.lims.entity;

// Generated 14/06/2011 1:11:20 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BioSampletype generated by hbm2java
 */
@Entity
@Table(name = "bio_sampletype", catalog = "lims")
public class BioSampletype implements java.io.Serializable
{

	private int		id;
	private String	sampletype;
	private String	samplesubtype;

	public BioSampletype()
	{
	}

	public BioSampletype(int id, String sampletype)
	{
		this.id = id;
		this.sampletype = sampletype;
	}

	public BioSampletype(int id, String sampletype, String samplesubtype)
	{
		this.id = id;
		this.sampletype = sampletype;
		this.samplesubtype = samplesubtype;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId()
	{
		return this.id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	@Column(name = "SAMPLETYPE", nullable = false)
	public String getSampletype()
	{
		return this.sampletype;
	}

	public void setSampletype(String sampletype)
	{
		this.sampletype = sampletype;
	}

	@Column(name = "SAMPLESUBTYPE")
	public String getSamplesubtype()
	{
		return this.samplesubtype;
	}

	public void setSamplesubtype(String samplesubtype)
	{
		this.samplesubtype = samplesubtype;
	}

}
