package au.org.theark.core.model.lims.entity;

// Generated Jun 14, 2011 3:39:29 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Version;

/**
 * Flag generated by hbm2java
 */
@Entity
@Table(name = "flag", catalog = "lims")
public class Flag implements java.io.Serializable {

	private int id;
	private String timestamp;
	private Integer deleted;
	private String domain;
	private int referenceId;
	private String user;

	public Flag() {
	}

	public Flag(int id, String domain, int referenceId, String user) {
		this.id = id;
		this.domain = domain;
		this.referenceId = referenceId;
		this.user = user;
	}

	public Flag(int id, Integer deleted, String domain, int referenceId,
			String user) {
		this.id = id;
		this.deleted = deleted;
		this.domain = domain;
		this.referenceId = referenceId;
		this.user = user;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Version
	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "DELETED")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Column(name = "DOMAIN", nullable = false, length = 50)
	public String getDomain() {
		return this.domain;
	}

	public void setDomain(String domain) {
		this.domain = domain;
	}

	@Column(name = "REFERENCE_ID", nullable = false)
	public int getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(int referenceId) {
		this.referenceId = referenceId;
	}

	@Column(name = "USER", nullable = false, length = 100)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

}
