package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * InvTray generated by hbm2java
 */
@Entity
@Table(name = "inv_box", schema = Constants.LIMS_TABLE_SCHEMA)
public class InvBox implements java.io.Serializable
{

	private Long				id;
	private String			timestamp;
	private InvTray			invTray;
	private Integer		deleted;
	private int				noofcol;
	private String			colnotype;
	private Integer		capacity;
	private String			name;
	private Integer		available;
	private int				noofrow;
	private String			rownotype;
	private Integer		transferId;
	private int				type;
	private Set<InvCell>	invCells	= new HashSet<InvCell>(0);

	public InvBox()
	{
	}

	public InvBox(Long id, InvTray invTray, int noofcol, String colnotype, int noofrow, String rownotype, int type)
	{
		this.id = id;
		this.invTray = invTray;
		this.noofcol = noofcol;
		this.colnotype = colnotype;
		this.noofrow = noofrow;
		this.rownotype = rownotype;
		this.type = type;
	}

	public InvBox(Long id, InvTray invTray, Integer deleted, int noofcol, String colnotype, Integer capacity, String name, Integer available, int noofrow, String rownotype, Integer transferId,
			int type, Set<InvCell> invCells)
	{
		this.id = id;
		this.invTray = invTray;
		this.deleted = deleted;
		this.noofcol = noofcol;
		this.colnotype = colnotype;
		this.capacity = capacity;
		this.name = name;
		this.available = available;
		this.noofrow = noofrow;
		this.rownotype = rownotype;
		this.transferId = transferId;
		this.type = type;
		this.invCells = invCells;
	}

	@Id
	@SequenceGenerator(name = "invtray_generator", sequenceName = "INVTRAY_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "invtray_generator")
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	
	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(String timestamp)
	{
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAY_ID", nullable = false)
	public InvTray getInvBox()
	{
		return this.invTray;
	}

	public void setInvBox(InvTray invTray)
	{
		this.invTray = invTray;
	}

	@Column(name = "DELETED")
	public Integer getDeleted()
	{
		return this.deleted;
	}

	public void setDeleted(Integer deleted)
	{
		this.deleted = deleted;
	}

	@Column(name = "NOOFCOL", nullable = false)
	public int getNoofcol()
	{
		return this.noofcol;
	}

	public void setNoofcol(int noofcol)
	{
		this.noofcol = noofcol;
	}

	@Column(name = "COLNOTYPE", nullable = false, length = 15)
	public String getColnotype()
	{
		return this.colnotype;
	}

	public void setColnotype(String colnotype)
	{
		this.colnotype = colnotype;
	}

	@Column(name = "CAPACITY")
	public Integer getCapacity()
	{
		return this.capacity;
	}

	public void setCapacity(Integer capacity)
	{
		this.capacity = capacity;
	}

	@Column(name = "NAME", length = 50)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "AVAILABLE")
	public Integer getAvailable()
	{
		return this.available;
	}

	public void setAvailable(Integer available)
	{
		this.available = available;
	}

	@Column(name = "NOOFROW", nullable = false)
	public int getNoofrow()
	{
		return this.noofrow;
	}

	public void setNoofrow(int noofrow)
	{
		this.noofrow = noofrow;
	}

	@Column(name = "ROWNOTYPE", nullable = false, length = 15)
	public String getRownotype()
	{
		return this.rownotype;
	}

	public void setRownotype(String rownotype)
	{
		this.rownotype = rownotype;
	}

	@Column(name = "TRANSFER_ID")
	public Integer getTransferId()
	{
		return this.transferId;
	}

	public void setTransferId(Integer transferId)
	{
		this.transferId = transferId;
	}

	@Column(name = "TYPE", nullable = false)
	public int getType()
	{
		return this.type;
	}

	public void setType(int type)
	{
		this.type = type;
	}

	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invTray")
	public Set<InvCell> getInvCells()
	{
		return this.invCells;
	}

	public void setInvCells(Set<InvCell> invCells)
	{
		this.invCells = invCells;
	}
	*/

}
