/*******************************************************************************
 * Copyright (c) 2011  University of Western Australia. All rights reserved.
 * 
 * This file is part of The Ark.
 * 
 * The Ark is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * The Ark is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * InvCell generated by hbm2java
 */
@Entity
@Table(name = "inv_cell", schema = Constants.LIMS_TABLE_SCHEMA)
public class InvCell implements java.io.Serializable {

	private static final long	serialVersionUID	= 1L;
	private Long					id;
	private String					timestamp;
	private InvBox					invBox;
	private Long					deleted;
	private Long					rowno;
	private Long					colno;
	private String					status;
	private Biospecimen			biospecimen;

	public InvCell() {
	}

	public InvCell(Long id, InvBox invBox) {
		this.id = id;
		this.invBox = invBox;
	}

	public InvCell(Long id, InvBox invBox, Long deleted, Long rowno, Long colno, String status) {
		this.id = id;
		this.invBox = invBox;
		this.deleted = deleted;
		this.rowno = rowno;
		this.colno = colno;
		this.status = status;
	}

	@Id
	@SequenceGenerator(name = "invcell_generator", sequenceName = "INVCELL_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "invcell_generator")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BOX_ID", nullable = false)
	public InvBox getInvBox() {
		return this.invBox;
	}

	public void setInvBox(InvBox invBox) {
		this.invBox = invBox;
	}

	@Column(name = "DELETED")
	public Long getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Long deleted) {
		this.deleted = deleted;
	}

	@Column(name = "ROWNO")
	public Long getRowno() {
		return this.rowno;
	}

	public void setRowno(Long rowno) {
		this.rowno = rowno;
	}

	@Column(name = "COLNO")
	public Long getColno() {
		return this.colno;
	}

	public void setColno(Long colno) {
		this.colno = colno;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "BIOSPECIMEN_ID")
	public Biospecimen getBiospecimen() {
		return this.biospecimen;
	}

	public void setBiospecimen(Biospecimen biospecimen) {
		this.biospecimen = biospecimen;
	}
}
