/*******************************************************************************
 * Copyright (c) 2011  University of Western Australia. All rights reserved.
 * 
 * This file is part of The Ark.
 * 
 * The Ark is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * The Ark is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

import au.org.theark.core.model.Constants;
import au.org.theark.core.model.study.entity.Study;

/**
 * InvSite generated by hbm2java
 * Note the hierarchy: site -< freezer -< rack -< box -< cell
 */
@Entity
@Table(name = "inv_site", schema = Constants.LIMS_TABLE_SCHEMA)
public class InvSite implements java.io.Serializable, InvTreeNode<InvFreezer> {

	private Long			id;
	private String			timestamp;
	private Integer		deleted;
	private String			contact;
	private String			address;
	private String			name;
	private String			phone;
	private String			ldapGroup;
	private Study			study;
	private List<InvFreezer>	invFreezers	= new ArrayList<InvFreezer>(0);

	public InvSite() {
	}

	public InvSite(Long id, String name) {
		this.id = id;
		this.name = name;
	}

	public InvSite(Long id, Integer deleted, String contact, String address, String name, String phone, String ldapGroup, List<InvFreezer> invFreezers) {
		this.id = id;
		this.deleted = deleted;
		this.contact = contact;
		this.address = address;
		this.name = name;
		this.phone = phone;
		this.ldapGroup = ldapGroup;
		this.invFreezers = invFreezers;
	}

	@Id
	@SequenceGenerator(name = "inv_site_generator", sequenceName = "INV_SITE_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "inv_site_generator")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "DELETED")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Column(name = "CONTACT", length = 50)
	public String getContact() {
		return this.contact;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}

	@Column(name = "ADDRESS", length = 65535)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PHONE", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "LDAP_GROUP", length = 50)
	public String getLdapGroup() {
		return this.ldapGroup;
	}

	public void setLdapGroup(String ldapGroup) {
		this.ldapGroup = ldapGroup;
	}

	/**
	 * @param study the study to set
	 */
	public void setStudy(Study study) {
		this.study = study;
	}

	/**
	 * @return the study
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STUDY_ID")
	public Study getStudy() {
		return study;
	}

	@OrderBy(value="name")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invSite")
	public List<InvFreezer> getInvFreezers() {
		return this.invFreezers;
	}

	public void setInvFreezers(List<InvFreezer> invFreezers) {
		this.invFreezers = invFreezers;
	}

	@Transient
	public List<InvFreezer> getChildren() {
		return getInvFreezers();
	}

	@Transient
	public String getNodeName() {
		return getName();
	}
	
	@Transient
	public String getNodeType() {
		return this.getClass().getCanonicalName();
	}
}