package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import au.org.theark.core.model.Constants;

/**
 * InvTank generated by hbm2java
 */
@Entity
@Table(name = "inv_tank", schema = Constants.LIMS_TABLE_SCHEMA)
public class InvTank implements java.io.Serializable
{

	private Long				id;
	private String			timestamp;
	private InvSite		invSite;
	private Integer		deleted;
	private String			location;
	private String			status;
	private Integer		capacity;
	private String			lastservicenote;
	private String			name;
	private Integer		available;
	private Date			decommissiondate;
	private Date			commissiondate;
	private Date			lastservicedate;
	private String			description;
	private Set<InvTray>	invTrays	= new HashSet<InvTray>(0);

	public InvTank()
	{
	}

	public InvTank(Long id, InvSite invSite, String name)
	{
		this.id = id;
		this.invSite = invSite;
		this.name = name;
	}

	public InvTank(Long id, InvSite invSite, Integer deleted, String location, String status, Integer capacity, String lastservicenote, String name, Integer available, Date decommissiondate,
			Date commissiondate, Date lastservicedate, String description, Set<InvTray> invTrays)
	{
		this.id = id;
		this.invSite = invSite;
		this.deleted = deleted;
		this.location = location;
		this.status = status;
		this.capacity = capacity;
		this.lastservicenote = lastservicenote;
		this.name = name;
		this.available = available;
		this.decommissiondate = decommissiondate;
		this.commissiondate = commissiondate;
		this.lastservicedate = lastservicedate;
		this.description = description;
		this.invTrays = invTrays;
	}

	@Id
	@SequenceGenerator(name = "invtank_generator", sequenceName = "INVTANK_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "invtank_generator")
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	
	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(String timestamp)
	{
		this.timestamp = timestamp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SITE_ID", nullable = false)
	public InvSite getInvSite()
	{
		return this.invSite;
	}

	public void setInvSite(InvSite invSite)
	{
		this.invSite = invSite;
	}

	@Column(name = "DELETED")
	public Integer getDeleted()
	{
		return this.deleted;
	}

	public void setDeleted(Integer deleted)
	{
		this.deleted = deleted;
	}

	@Column(name = "LOCATION", length = 65535)
	public String getLocation()
	{
		return this.location;
	}

	public void setLocation(String location)
	{
		this.location = location;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	@Column(name = "CAPACITY")
	public Integer getCapacity()
	{
		return this.capacity;
	}

	public void setCapacity(Integer capacity)
	{
		this.capacity = capacity;
	}

	@Column(name = "LASTSERVICENOTE", length = 65535)
	public String getLastservicenote()
	{
		return this.lastservicenote;
	}

	public void setLastservicenote(String lastservicenote)
	{
		this.lastservicenote = lastservicenote;
	}

	@Column(name = "NAME", nullable = false, length = 50)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "AVAILABLE")
	public Integer getAvailable()
	{
		return this.available;
	}

	public void setAvailable(Integer available)
	{
		this.available = available;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DECOMMISSIONDATE", length = 19)
	public Date getDecommissiondate()
	{
		return this.decommissiondate;
	}

	public void setDecommissiondate(Date decommissiondate)
	{
		this.decommissiondate = decommissiondate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "COMMISSIONDATE", length = 19)
	public Date getCommissiondate()
	{
		return this.commissiondate;
	}

	public void setCommissiondate(Date commissiondate)
	{
		this.commissiondate = commissiondate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "LASTSERVICEDATE", length = 19)
	public Date getLastservicedate()
	{
		return this.lastservicedate;
	}

	public void setLastservicedate(Date lastservicedate)
	{
		this.lastservicedate = lastservicedate;
	}

	@Column(name = "DESCRIPTION", length = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	/*
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "invTank")
	public Set<InvTray> getInvTrays()
	{
		return this.invTrays;
	}

	public void setInvTrays(Set<InvTray> invTrays)
	{
		this.invTrays = invTrays;
	}
	*/
}
