/*******************************************************************************
 * Copyright (c) 2011  University of Western Australia. All rights reserved.
 * 
 * This file is part of The Ark.
 * 
 * The Ark is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 3
 * of the License, or (at your option) any later version.
 * 
 * The Ark is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 ******************************************************************************/
package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * Listofvalues generated by hbm2java
 */
@Entity
@Table(name = "listofvalues", schema = Constants.LIMS_TABLE_SCHEMA)
public class Listofvalues implements java.io.Serializable {

	private Long		id;
	private String		timestamp;
	private Integer	studyId;
	private Integer	deleted;
	private String		type;
	private String		value;
	private Integer	sortorder;
	private Integer	groupId;
	private String		description;
	private String		parenttype;
	private String		parentvalue;
	private int			iseditable;
	private String		language;

	public Listofvalues() {
	}

	public Listofvalues(Long id, int iseditable, String language) {
		this.id = id;
		this.iseditable = iseditable;
		this.language = language;
	}

	public Listofvalues(Long id, Integer studyId, Integer deleted, String type, String value, Integer sortorder, Integer groupId, String description, String parenttype, String parentvalue,
			int iseditable, String language) {
		this.id = id;
		this.studyId = studyId;
		this.deleted = deleted;
		this.type = type;
		this.value = value;
		this.sortorder = sortorder;
		this.groupId = groupId;
		this.description = description;
		this.parenttype = parenttype;
		this.parentvalue = parentvalue;
		this.iseditable = iseditable;
		this.language = language;
	}

	@Id
	@SequenceGenerator(name = "listofvalues_generator", sequenceName = "LISTOFVALUES_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "listofvalues_generator")
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	@Column(name = "STUDY_ID")
	public Integer getStudyId() {
		return this.studyId;
	}

	public void setStudyId(Integer studyId) {
		this.studyId = studyId;
	}

	@Column(name = "DELETED")
	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

	@Column(name = "TYPE", length = 100)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "VALUE", length = 100)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "SORTORDER")
	public Integer getSortorder() {
		return this.sortorder;
	}

	public void setSortorder(Integer sortorder) {
		this.sortorder = sortorder;
	}

	@Column(name = "GROUP_ID")
	public Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(Integer groupId) {
		this.groupId = groupId;
	}

	@Column(name = "DESCRIPTION", length = 100)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "PARENTTYPE", length = 65535)
	public String getParenttype() {
		return this.parenttype;
	}

	public void setParenttype(String parenttype) {
		this.parenttype = parenttype;
	}

	@Column(name = "PARENTVALUE", length = 65535)
	public String getParentvalue() {
		return this.parentvalue;
	}

	public void setParentvalue(String parentvalue) {
		this.parentvalue = parentvalue;
	}

	@Column(name = "ISEDITABLE", nullable = false)
	public int getIseditable() {
		return this.iseditable;
	}

	public void setIseditable(int iseditable) {
		this.iseditable = iseditable;
	}

	@Column(name = "LANGUAGE", nullable = false, length = 20)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

}
