package au.org.theark.core.model.lims.entity;

// Generated 15/06/2011 1:22:58 PM by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import au.org.theark.core.model.Constants;

/**
 * ListofvaluesDescription generated by hbm2java
 */
@Entity
@Table(name = "listofvalues_description", schema = Constants.LIMS_TABLE_SCHEMA)
public class ListofvaluesDescription implements java.io.Serializable
{

	private Long		id;
	private String		timestamp;
	private Integer	deleted;
	private String		type;
	private String		description;
	private String		descId;

	public ListofvaluesDescription()
	{
	}

	public ListofvaluesDescription(Long id, String type, String description)
	{
		this.id = id;
		this.type = type;
		this.description = description;
	}

	public ListofvaluesDescription(Long id, Integer deleted, String type, String description, String descId)
	{
		this.id = id;
		this.deleted = deleted;
		this.type = type;
		this.description = description;
		this.descId = descId;
	}

	@Id
	@SequenceGenerator(name = "listofvaluesdesc_generator", sequenceName = "LISTOFVALUESDESC_SEQUENCE")
	@GeneratedValue(strategy = GenerationType.AUTO, generator = "listofvaluesdesc_generator")
	public Long getId()
	{
		return this.id;
	}

	public void setId(Long id)
	{
		this.id = id;
	}

	
	@Column(name = "TIMESTAMP", length = 55)
	public String getTimestamp()
	{
		return this.timestamp;
	}

	public void setTimestamp(String timestamp)
	{
		this.timestamp = timestamp;
	}

	@Column(name = "DELETED")
	public Integer getDeleted()
	{
		return this.deleted;
	}

	public void setDeleted(Integer deleted)
	{
		this.deleted = deleted;
	}

	@Column(name = "TYPE", nullable = false)
	public String getType()
	{
		return this.type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	@Column(name = "DESCRIPTION", nullable = false, length = 65535)
	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	@Column(name = "DESC_ID", length = 55)
	public String getDescId()
	{
		return this.descId;
	}

	public void setDescId(String descId)
	{
		this.descId = descId;
	}

}
