USE lims;

ALTER TABLE `inv_site` ADD COLUMN `STUDY_ID`  int(11) NULL DEFAULT NULL AFTER `LDAP_GROUP`;
ALTER TABLE `inv_site` ADD CONSTRAINT `FK_INV_SITE_STUDY` FOREIGN KEY (`STUDY_ID`) REFERENCES `study`.`study` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE `inv_tray` DROP INDEX `fk_inv_tray_tank_idx`;
CREATE INDEX `FK_INV_SITE_STUDY` USING BTREE ON `inv_site`(`STUDY_ID`) ;
CREATE INDEX `FK_INV__TRAY_IDX` USING BTREE ON `inv_tray`(`TANK_ID`) ;
