use study;
ALTER TABLE `study`.`custom_field_group` ADD COLUMN `STUDY_ID` INT NULL  AFTER `DESCRIPTION` , 
  ADD CONSTRAINT `FK_CUSTOM_FIELD_GROUP_STUDY_ID`
  FOREIGN KEY (`STUDY_ID` )
  REFERENCES `study`.`study` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_CUSTOM_FIELD_GROUP_STUDY_ID` (`STUDY_ID` ASC) ;


