use study;
CREATE  TABLE `pheno`.`pheno_data` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `CUSTOM_FIELD_DISPLAY_ID` INT NULL ,
  `PHENO_COLLECTION_ID` INT NULL ,
  `DATE_DATA_VALUE` DATE NULL ,
  `NUMBER_DATA_VALUE` DOUBLE NULL ,
  `TEXT_DATA_VALUE` TEXT NULL ,
  PRIMARY KEY (`ID`) )
ENGINE = InnoDB;


ALTER TABLE `pheno`.`pheno_data` 
  ADD CONSTRAINT `FK_PHENO_DATA_CFD_ID`
  FOREIGN KEY (`CUSTOM_FIELD_DISPLAY_ID` )
  REFERENCES `study`.`custom_field_display` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, ADD INDEX `FK_PHENO_DATA_CFD_ID` (`CUSTOM_FIELD_DISPLAY_ID` ASC) ;


ALTER TABLE `pheno`.`pheno_data` 
  ADD CONSTRAINT `FK_PHENO_DATA_PHENO_COLLECTION_ID`
  FOREIGN KEY (`PHENO_COLLECTION_ID` )
  REFERENCES `pheno`.`pheno_collection` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
, DROP PRIMARY KEY 
, ADD PRIMARY KEY (`ID`) ;




ALTER TABLE `pheno`.`questionnaire_status` CHANGE COLUMN `DESCRIPTION` `DESCRIPTION` VARCHAR(255) NULL DEFAULT NULL  ;


ALTER TABLE `pheno`.`pheno_collection` ADD COLUMN `DESCRIPTION` VARCHAR(500) NULL  AFTER `REVIEWED_BY_ID` ;

ALTER TABLE `pheno`.`pheno_collection` CHANGE COLUMN `RECORDED_DATE` `RECORDED_DATE` DATETIME NULL DEFAULT NULL  ;

ALTER TABLE `pheno`.`pheno_collection` CHANGE COLUMN `RECORDED_DATE` `RECORDED_DATE` DATETIME NOT NULL  ;





