USE lims;

CREATE  TABLE `lims`.`access_request` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `NAME` VARCHAR(100) NOT NULL ,
  `REQUEST_DATE` DATETIME NOT NULL ,
  `REQUIRED_DATE` DATETIME NULL ,
  `COMMENTS` VARCHAR(2000) NULL ,
  PRIMARY KEY (`ID`)
)
ENGINE = InnoDB;

CREATE TABLE `access_request_status` (
  `ID` int(11) NOT NULL auto_increment,
  `NAME` varchar(100) NOT NULL,
  PRIMARY KEY  (`ID`)
) ENGINE=InnoDB;