USE `study`;

INSERT INTO `study` (`ID`, `NAME`, `DESCRIPTION`, `DATE_OF_APPLICATION`, `ESTIMATED_YEAR_OF_COMPLETION`, `CHIEF_INVESTIGATOR`, `CO_INVESTIGATOR`, `AUTO_GENERATE_SUBJECTUID`, `SUBJECTUID_START`, `STUDY_STATUS_ID`, `SUBJECTUID_PREFIX`, `CONTACT_PERSON`, `CONTACT_PERSON_PHONE`, `LDAP_GROUP_NAME`, `AUTO_CONSENT`, `SUB_STUDY_BIOSPECIMEN_PREFIX`, `STUDY_LOGO`, `FILENAME`, `SUBJECTUID_TOKEN_ID`, `SUBJECTUID_PADCHAR_ID`, `SUBJECT_KEY_PREFIX`, `SUBJECT_KEY_START`, `PARENT_ID`, `AUTO_GENERATE_BIOSPECIMENUID`, `AUTO_GENERATE_BIOCOLLECTIONUID`, `SAVE_TO_PARENT`, `SAVE_TO_PARENT_LOCKED`)
VALUES
	(1, 'testLoadingFromSQL', 'Study to test loading data from SQL', NULL, NULL, 'John Doe', NULL, 0, 0, 1, NULL, NULL, NULL, NULL, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 0, 0, 0, 0);
