CREATE DATABASE IF NOT EXISTS `config`;
USE `config`;
DROP TABLE IF EXISTS `config_fields`;
CREATE TABLE IF NOT EXISTS `config_fields` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` text NOT NULL,
  `DESCRIPTION` text NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;

INSERT INTO `config_fields` (`ID`, `NAME`, `DESCRIPTION`) VALUES
(1, 'ROWS_PER_PAGE', 'Rows Per Page'),
(2, 'CUSTOM_FIELDS_PER_PAGE', 'Custom Fields Per Page');

DROP TABLE IF EXISTS `user_config`;
CREATE TABLE IF NOT EXISTS `user_config` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `FIELD_ID` int(11) NOT NULL,
  `VALUE` text NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `USER_ID` (`USER_ID`,`FIELD_ID`),
  KEY `FK_CONFIG_FIELD_ID` (`FIELD_ID`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1;


ALTER TABLE `user_config`
  ADD CONSTRAINT `user_config_ibfk_1` FOREIGN KEY (`FIELD_ID`) REFERENCES `config_fields` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  ADD CONSTRAINT `user_config_ibfk_3` FOREIGN KEY (`USER_ID`) REFERENCES `study`.`ark_user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION;

