package org.wager.biogenix.types;

// Generated 31/07/2007 12:08:37 by Hibernate Tools 3.1.0.beta5


import java.util.Date;

/**
 * IxBioTransactions generated by hbm2java
 */
public class BioTransactions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -272636517034828425L;
	// Fields    

	/**
	 * 
	 */

	private long biotransactionkey;
	private String timestamp;
	private long deleted;
	private String treatment;
	private long studykey;
	private long sourcestudykey;
	private String unit;
	private Date deliverydate;
	private String fixationtime;
	private Date transactiondate;
	private double quantity;
	private String owner;
	private long biospecimenkey;
	private String reason;
	private String status;
	private String study;
	private String collaborator;
	private String recorder;
	private String destination;
	private String action;

	// Constructors

	/** default constructor */
	public BioTransactions() {
	}

	/** minimal constructor */
	public BioTransactions(long biotransactionkey,
			Date transactiondate, double quantity, long biospecimenkey) {
		this.biotransactionkey = biotransactionkey;
		this.transactiondate = transactiondate;
		this.quantity = quantity;
		this.biospecimenkey = biospecimenkey;
	}

	/** full constructor */
	public BioTransactions(long biotransactionkey, long deleted,
			String treatment, long studykey, long sourcestudykey,
			String unit, Date deliverydate, String fixationtime,
			Date transactiondate, double quantity, String owner,
			long biospecimenkey, String reason, String status,
			String study, String collaborator, String recorder,
			String destination, String action) {
		this.biotransactionkey = biotransactionkey;
		this.deleted = deleted;
		this.treatment = treatment;
		this.studykey = studykey;
		this.sourcestudykey = sourcestudykey;
		this.unit = unit;
		this.deliverydate = deliverydate;
		this.fixationtime = fixationtime;
		this.transactiondate = transactiondate;
		this.quantity = quantity;
		this.owner = owner;
		this.biospecimenkey = biospecimenkey;
		this.reason = reason;
		this.status = status;
		this.study = study;
		this.collaborator = collaborator;
		this.recorder = recorder;
		this.destination = destination;
		this.action = action;
	}

	// Property accessors
	public long getBiotransactionkey() {
		return this.biotransactionkey;
	}

	public void setBiotransactionkey(long biotransactionkey) {
		this.biotransactionkey = biotransactionkey;
	}

	public String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(String timestamp) {
		this.timestamp = timestamp;
	}

	public long getDeleted() {
		return this.deleted;
	}

	public void setDeleted(long deleted) {
		this.deleted = deleted;
	}

	public String getTreatment() {
		return this.treatment;
	}

	public void setTreatment(String treatment) {
		this.treatment = treatment;
	}

	public long getStudykey() {
		return this.studykey;
	}

	public void setStudykey(long studykey) {
		this.studykey = studykey;
	}

	public long getSourcestudykey() {
		return this.sourcestudykey;
	}

	public void setSourcestudykey(long sourcestudykey) {
		this.sourcestudykey = sourcestudykey;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

	public Date getDeliverydate() {
		return this.deliverydate;
	}

	public void setDeliverydate(Date deliverydate) {
		this.deliverydate = deliverydate;
	}

	public String getFixationtime() {
		return this.fixationtime;
	}

	public void setFixationtime(String fixationtime) {
		this.fixationtime = fixationtime;
	}

	public Date getTransactiondate() {
		return this.transactiondate;
	}

	public void setTransactiondate(Date transactiondate) {
		this.transactiondate = transactiondate;
	}

	public double getQuantity() {
		return this.quantity;
	}

	public void setQuantity(double quantity) {
		this.quantity = quantity;
	}

	public String getOwner() {
		return this.owner;
	}

	public void setOwner(String owner) {
		this.owner = owner;
	}

	public long getBiospecimenkey() {
		return this.biospecimenkey;
	}

	public void setBiospecimenkey(long biospecimenkey) {
		this.biospecimenkey = biospecimenkey;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStudy() {
		return this.study;
	}

	public void setStudy(String study) {
		this.study = study;
	}

	public String getCollaborator() {
		return this.collaborator;
	}

	public void setCollaborator(String collaborator) {
		this.collaborator = collaborator;
	}

	public String getRecorder() {
		return this.recorder;
	}

	public void setRecorder(String recorder) {
		this.recorder = recorder;
	}

	public String getDestination() {
		return this.destination;
	}

	public void setDestination(String destination) {
		this.destination = destination;
	}

	public String getAction() {
		return this.action;
	}

	public void setAction(String action) {
		this.action = action;
	}

}
