<?xml version="1.0" encoding="utf-8"?>
<!-- admin_password.xsl, Administration channel -->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
    <xsl:include href="./admin_menu_b.xsl"/>
    
    
    <xsl:output method="html" indent="no" />
    <xsl:template match="search_case">

        <!-- Get variables into the stylesheet -->

        <!-- Form Fill -->
        <form action="{$baseActionURL}?current=search_case" method="post">
        <table width="100%">
            <tr><td class="uportal-channel-subtitle">Step 2. Select Basel Event for Loss Category<br/><hr/></td></tr>
            <tr><td class="uportal-label"> &gt; &gt; Staff defalcation/fraud<br/><hr/></td></tr>
        </table>
        <table width="100%" border="1">
             
            <tr><td id="neuragenix-form-row-input-label" class="neuragenix-table-header"  width="55%">Loss Category</td>
                <td id="neuragenix-form-row-input-label" class="neuragenix-table-header"  width="45%">Basel Event</td>
            </tr>
          <!-- ******************** Row 1 ************************ -->
            <tr class="uportal-text-small"><td  width="55%">Transactions not reported (intentional)</td>            
            <td width="55%" class="uportal-label">
                <select class="uportal-input-text" name="strDropDown">
                                <option>Select...</option>
                                <option>Internal Fraud</option>
                                <option>External Fraud</option>
                                <option>Employment Practices amd Workplace Safety</option>
                                <option>Clients, Products &amp; Business Practices</option>
                                <option>Damage to Physical Assets</option>
                                <option>Business disruption and system failure</option>
                                <option>Execution, Delivery &amp; Process Management</option>
                </select><img border="0" src="media/neuragenix/cross.gif" alt="Check"/> 
                            </td></tr>
            <tr class="uportal-text-small"><td>Transaction type unauthorised (w/monetary loss)</td>
            <td class="uportal-label"><select class="uportal-input-text" name="strDropDown">
             <option>Internal Fraud</option><option>Employment Practices amd Workplace Safety</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Mismarking of position (intentional)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"> <option>Internal Fraud</option>
                                <option>Employment Practices amd Workplace Safety</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>         
            
            <tr class="uportal-text-small"><td>Cheque fraud: Worthless deposits / valueless cheques</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"> <option>Internal Fraud</option>
                                <option>Employment Practices amd Workplace Safety</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Theft / extortion / embezzlement / robbery</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"> <option>Internal Fraud</option>
                                <option>Employment Practices amd Workplace Safety</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            
            <!--
            <tr class="uportal-text-small"><td>Misappropriation of assets</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Malicious destruction of assets</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Counterfeit other than cheques</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: kiting</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Smuggling</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Identity Fraud: Account takeover / impersonation etc</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Tax non-compliance / wilful evasion</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Bribes / kickbacks</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Insider trading (not on firm's account)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Forged signature or otherwise not within Account Mandate</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Counterfeit - originated</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Stolen Blank Cheque Book</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Skimming  (CARDS)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cards Merchant - Bogus Merchant  (CARDS)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cards Merchant - false sales  (CARDS)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cards Merchants - refunds  (CARDS)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cards Merchants - Third Party  (CARDS)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Staff Fraud</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Identity fraud: Using forged identification documents.</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Third Party Cheques </td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Fraudulently linked accounts</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Internet / Telephone banking fraud (e.g. B-Pay)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Counterfeit - non-originated</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Fraudulently Altered Payee</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Fraudulently Altered Amount</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cheque fraud: Fraudulently Altered Payee and Amount</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Debit Card fraud: ATM abuse</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Debit Card fraud: EFTPOS abuse</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Liability for motor vehicle fines</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Cardholder fraud</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Merchant fraud (cards)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Hacking damage</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Theft of information (with monetary loss)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Compensation/benefit or termination issues</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Organised labour activity</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Public Liability/General liability </td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Occupational Health &amp; Safety events</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Workers compensation</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Discrimination &amp; Harassment</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Fiduciary breaches / guideline violations</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Suitability / Incorrect Advice (know your customer, etc)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Incorrect Disclosure</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Privacy breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Aggressive sales practices</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Account churning</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Misuse of confidential information</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Lender liability</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Acting Unfairly or Outside Authority</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Misleading &amp; Deceptive conduct</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Payout Figure Disputes</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Code of Banking Practice breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Price fixing / exploitation</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Improper trade / market practices</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Market manipulation</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Insider trading (on firm's account)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Unlicensed activity</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Money laundering</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Compliance Breach</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>EFT Disputes</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Copyright breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Exclusive dealing</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Unconscionable conduct</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Harassment &amp; Coercion (Customers)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Collection / repossession practices</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Excess Fees or charges</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Handling of unclaimed monies</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Tax Breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Product defects (unauthorised etc)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Model errors</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Product defect - (loss incurred when product previously had defects - which have subsequently been addressed.)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>CARDS - Run-off refunds of travellers cheques</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Failure to investigate client per guidelines</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Exceeding client exposure limits</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Disputes over performance of advisory activities</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Counterclaim on lending debts</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Natural disaster losses</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Utility outage / disruptions</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Miscommunication</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Data entry, maintenance or loading error</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Missed deadline or responsibility or settlement or cut-off</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Model / system misoperation or processing failure</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Accounting error / entity attribution error</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Other task misperformance</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Delivery failure</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Collateral management failure</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Reference data maintenance</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Deal not Written</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Duplicated payments</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Loss on Account Closure/ Small balance write-off</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Unreconciled accounts</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Processing error external to BU (but within Bank - therefore excludes outsourced activities)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Missing cash, cheques, deposits</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Tellers' Differences</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Incorrect currency conversion</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Stamp Duty Penalties</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Mistaken payments</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Chargebacks (Cards)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Failed mandatory reporting obligation</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Inaccurate external report (loss incurred)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Significant Cash Transaction Reporting</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Suspect Transaction Reporting</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Document retention</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>REVS/VSR breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Late fees for lodgement of documents (ASIC)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Client permissions / disclaimers missing</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Legal documents missing incomplete</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Non-compliance with customer's instructions</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Tax File Number Breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Prospectus Breaches</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>100 Point Valids (Aus) / account opening Valids (NZ)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Titles office fines - Legal documents missing incomplete</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Letter of offer (not provided or incomplete)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Statement Disputes</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Improper execution of documents</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Clear title on goods not obtained from dealer/supplier</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Unapproved access given to accounts </td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Incorrect or insufficient client records (loss incurred)</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Negligent loss or damage of client assets</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Missing safe custody items</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Hardware failures</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Software failures</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Telecommunications</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>ATM dispensing error</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Non-client counterparty misperformance</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Non-client counterparty disputes</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Non-client counterparty liquidation</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Outsourcing</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
            <tr class="uportal-text-small"><td>Vendor disputes</td><td class="uportal-label"><select class="uportal-input-text" name="strDropDown"><option>Execution, Delivery &amp; Process Management</option></select><img border="0" src="media/neuragenix/tick.gif" alt="Valid"/></td></tr>
-->
        <!-- ************* Buttons ******************** -->
        
        </table>
        
        <table width="80%" border="0">
            <tr/>
            <tr>
                <td>
                <input type="submit" name="Return" value=" &lt;&lt;--Back" class="uportal-button" />
                <input type="submit" name="clear" value="Clear" class="uportal-button" />
                <input type="submit" name="Save" value="Save" class="uportal-button" />
                
                </td>                               
            </tr>

        </table>
        </form>
    </xsl:template>
</xsl:stylesheet>
