USE study;
ALTER TABLE `study`.`ark_role_policy_template` DROP FOREIGN KEY `FK_ROLE_TMPLT_ARK_MODULE_ID` , DROP FOREIGN KEY `FK_ROLE_TMPLT_ARK_FUNCTION_ID` ;
ALTER TABLE `study`.`ark_role_policy_template` CHANGE COLUMN `ARK_MODULE_ID` `ARK_MODULE_ID` INT(11) NULL  , CHANGE COLUMN `ARK_FUNCTION_ID` `ARK_FUNCTION_ID` INT(11) NULL  , 
  ADD CONSTRAINT `FK_ROLE_TMPLT_ARK_MODULE_ID`
  FOREIGN KEY (`ARK_MODULE_ID` )
  REFERENCES `study`.`ark_module` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION, 
  ADD CONSTRAINT `FK_ROLE_TMPLT_ARK_FUNCTION_ID`
  FOREIGN KEY (`ARK_FUNCTION_ID` )
  REFERENCES `study`.`ark_function` (`ID` )
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
